### ISSUE TITLE
[Requests] Progress Percent in HTML Title; Lock in Trinket and/or Ring in Top Gear

### ISSUE THREAD

**Issue by Pariah** [seriallos/raidbots-issues#10]
First of all, what an amazing site. Thank you very much for it.

I was wondering if two requests could possibly be addressed with the latter holding more weight with my request.

1. Could the current queue and sim progress be included in the title so I could eyeball the current situation. For example, instead of "Raidbots" it could be "Raidbots | 4/25" or "Raidbots | 33.3%".

2. Would it be possible when utilizing the top gear tool to let us lock-in one ring or one trinket so as to lower the amount of iterations that need to be completed?

**Comment by seriallos** [comment]
1. Maybe. I've thought about it but go back and forth. The progress indicator is nice but I also don't love random things changing on my screen - I personally tend to find it distracting. So /shrug! There are browser notifications for when the sim completes which might partially solve your use case.

2. It's definitely on my list, no ETA or promises or anything.

**Comment by Pariah** [comment]
Thank you very much for the follow-up. I appreciate it! Understandable on both accounts.

With respect to the second point, would it be possible in the interim to increase the amount of iterations available to Epic level patreons from 2.4m to 2.6m to allow for one more piece of gear to be chosen? I find myself consistently just barely missing out on what I'm looking for.
