### ISSUE TITLE
Blaster Master

### ISSUE THREAD

**Issue by vipomage** [seriallos/raidbots-issues#100]
Blaster Master nerf not reflected on site and sim calculations

**Comment by seriallos** [comment]
I just checked with one of the SimC mage devs and Blaster Master is up-to-date - I suspect what you're seeing is an incorrect/outdate tooltip from Wowhead.

You can try to force reload the site or clear your browser cache to see if there's a more recent version of the tooltip or just wait until Wowhead updates.

The results will be correct though, despite the inaccurate tooltip.
