### ISSUE TITLE
Captain's Signet of Command

### ISSUE THREAD

**Issue by gumshoetortis** [seriallos/raidbots-issues#101]
The captain's signet is simming @380 even though it is 395.

**Comment by gumshoetortis** [comment]
Thanks for the reply.  It was showing up as 380 under top gear, gear
compare, and quick sim.

https://www.raidbots.com/simbot/report/u7RCVYChHRu5hon2fA1QFa


# SimC Addon 1.10.8
paladin="Gumshoe"
level=120
race=dwarf
region=us
server=uldum
role=attack
professions=mining=150/engineering=150
talents=2323233
spec=retribution

head=,id=158025,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=396/38/14/13
neck=,id=158075,bonus_id=4936/4929/4930/1548,context=11,azerite_level=39
shoulder=,id=160641,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/44/13
back=,id=159293,bonus_id=5010/1552/4786,context=35
chest=,id=159448,bonus_id=5061/1557/4786/4775,context=35,azerite_powers=154/31/44/13
shirt=,id=3427,context=14
tabard=,id=160539,context=14
wrist=,id=160637,bonus_id=4799/1512/4784,context=5
hands=,id=159413,gem_id=154127,bonus_id=5010/4802/1552/4783,context=35
waist=,id=159410,bonus_id=5010/1552/4783,context=35
legs=,id=160639,bonus_id=4800/42/1512/4783,context=6
feet=,id=159452,bonus_id=5010/1567/4784,context=35
finger1=,id=166560,context=14
finger2=,id=160646,enchant_id=5943,gem_id=154127,bonus_id=4799/1808/1492/4786,context=5
trinket1=,id=159125,context=13
trinket2=,id=161474,bonus_id=5119/1492/4786,context=3
main_hand=,id=160679,enchant_id=5963,bonus_id=4800/41/1507/4786,context=6

### Gear from Bags
#
# Gridrunner Galea (375)
#
head=,id=160634,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=453/21/83/13
#
# Helm of the Defiled Laboratorium (375)
#
head=,id=160732,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=485/22/87/13
#
# AZ3-R1-T3 Orthogonal Optics (345)
# head=,id=160491,bonus_id=4775,context=13,azerite_powers=501/99/502/13
#
# Overseer's Riot Helmet (390)
#
head=,id=159414,bonus_id=5448/1557/4786/5402/4775,context=35,azerite_powers=154/18/14/13
#
# Bleakweald Pauldrons (375)
#
shoulder=,id=158028,bonus_id=1562/5140/5382/4775,context=28,azerite_powers=193/30/15/13
#
# Void-Drenched Cape (380)
# back=,id=159289,bonus_id=5010/1552/4786,context=35
#
# Desert Guardian's Breastplate (385)
# chest=,id=159424,bonus_id=5448/1557/4786/5401,context=35,azerite_powers=
#
# Breastplate of Arterial Protection (390)
#
chest=,id=159432,bonus_id=5061/1557/4786/4775,context=35,azerite_powers=187/22/87/13
#
# Gauntlets of Total Subservience (380)
# hands=,id=159421,bonus_id=5010/1552/4783,context=35
#
# Harbormaster Legplates (385)
# legs=,id=157995,bonus_id=4803/1577/4784,context=28
#
# Warboots of Absolute Eradication (390)
# feet=,id=160640,bonus_id=4799/43/1512/4784,context=5
#
# Charged Sandstone Band (385)
# finger1=,id=158366,enchant_id=5943,bonus_id=5010/1557/4784,context=35
#
# Band of Certain Annihilation (380)
# finger1=,id=160646,enchant_id=5943,bonus_id=4799/42/1502/4783,context=5
#
# Charged Sandstone Band (375)
# finger1=,id=158366,enchant_id=5943,bonus_id=5010/1547/4783,context=16
#
# Seal of Questionable Loyalties (380)
# finger1=,id=158314,enchant_id=5939,bonus_id=5010/1552/4786,context=35
#
# Rot-Scour Ring (370)
# finger1=,id=160645,bonus_id=4799/1492/4786,context=5
#
# Syringe of Bloodborne Infirmity (370)
# trinket1=,id=160655,bonus_id=4799/1492/4786,context=5
#
# Galecaller's Beak (355)
# trinket1=,id=161379,bonus_id=4798/1477/4786,context=3
#
# Gore-Crusted Butcher's Block (370)
# trinket1=,id=159616,bonus_id=5010/1542/4786,context=16
#
# Disc of Systematic Regression (375)
# trinket1=,id=160650,bonus_id=4799/1497/4783,context=5
#
# Blacksmith Hammer (1)
# main_hand=,id=5956
#
# Arclight Spanner (10)
# main_hand=,id=6219
#
# Gnarlwood Cutlass (345)
# main_hand=,id=158104,bonus_id=4803/1537/4783,context=28
#
# 7th Legionnaire's Shield (370)
# off_hand=,id=163895,bonus_id=5125/1562/4786,context=29
#
# 7th Legionnaire's Aegis (370)
# off_hand=,id=163891,bonus_id=5125/1562/4786,context=29

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

**Comment by seriallos** [comment]
It's probably some out-of-date game data I'm using on the site. I'm out of town right now but will update the game data on the site when I get back home next week.

**Comment by gumshoetortis** [comment]
No worries!  Thanks for the update.  Happy Holidays!

**Comment by seriallos** [comment]
Yup, was out of date game data. This is now fixed on the site.

**Comment by gumshoetortis** [comment]
Thanks for the update.  Your efforts are much appreciated.
