### ISSUE TITLE
[Request] Capitalizing letters with diacritics/accent marks

### ISSUE THREAD

**Issue by zielliger** [seriallos/raidbots-issues#103]
The character name on the simulation report page is (generally) capitalized except for the accented characters.

e.g. https://www.raidbots.com/simbot/report/vN13yxpR6EfR6XqCD29dDZ where the `ê` in `ZIêLLIGER` is not capitalized, even though a proper capital form `Ê` exists. 

I understand that this is a low-priority issue, as it does not affect the performance and functionality, but I thought I would mention it.

**Comment by seriallos** [comment]
This should be fixed now.

Hopefully I didn't break some other edge cases!
