### ISSUE TITLE
Sinister Combatant's Bow missing affix selection in gear compare

### ISSUE THREAD

**Issue by zealvurte** [seriallos/raidbots-issues#104]
Both versions of the Sinister Combatant's Bow (164670, 164711) are missing the dropdown to select an affix in gear compare.

**Comment by seriallos** [comment]
I'll look into this.

Current data I use doesn't appear to have these affix mappings - it may show up in the WoW API this week so I'll check back on it this week.

If not, I'll take another dig into the game data to see if I can find this information.

**Comment by seriallos** [comment]
Data has been updated and affixes should show up for these items now.
