### ISSUE TITLE
Droptimizer - Enhancement Shaman going over Time Limit

### ISSUE THREAD

**Issue by Vynka** [seriallos/raidbots-issues#106]
When running the Droptimizer for an Enhancement Shaman with SmartSim the simulation times out after more than 10 minutes.

**Comment by seriallos** [comment]
Could you give me some more details so I can reproduce the issue?

* URL of report that is timing out
* /simc input for your character (or armory region/realm/name)
* Which raid you are simming

Thanks!

**Comment by seriallos** [comment]
I believe this should be handled better now. I've extended the time limit for Droptimizer sims. Please let me know if you see timeouts in the future!
