### ISSUE TITLE
Upgrading ring ilvl lowers dps

### ISSUE THREAD

**Issue by Taijituw** [seriallos/raidbots-issues#107]
I was using Gear Compare to compare possible upgrades using a Warlord's Trophy. Somehow, upgrading my ring from 370 -> 385 ilvl lowered my dps instead of increasing it, which goes against all logic.

See: https://www.raidbots.com/simbot/report/s4d53VLEUeYGJLXo8byC1v

**Comment by Taijituw** [comment]
Thought I had figured out my mistake (leaving the new ring as slot 1 instead of slot 2), but even after I fixed that and increased the iterations my dps is still lower with the upgraded ring.
https://www.raidbots.com/simbot/report/ueSttMC334Q4T6ABkYWkzW

**Comment by seriallos** [comment]
Looks like your equipped ring has +27 haste enchant on it and the Gear Compare didn't have that set up.

Running with the enchants matched up shows the expected increase:

https://www.raidbots.com/simbot/report/tr4wdG8FTz8ndYQrSi1xVh
