### ISSUE TITLE
[Request] crit dmg reduce option in pvp

### ISSUE THREAD

**Issue by jaalli** [seriallos/raidbots-issues#109]
![aa](https://user-images.githubusercontent.com/46207899/51893188-86f2fe00-23e7-11e9-8dc5-883ea5f8794c.png)

Hello
Simcraft program has pvp crit damage reduction option, could you add that in simulation option?
thank you!

**Comment by seriallos** [comment]
SimC does not have particularly good support for PVP at all right now so I don't have plans to add these options in the main toolset. You can use them in Advanced for now.

If SimC gets better PVP support in the future, I'll take another look at this.
