### ISSUE TITLE
Upgrade of Patreon level hasn't applied to account

### ISSUE THREAD

**Issue by Lormsby** [seriallos/raidbots-issues#11]
Upgraded from Rare to top level and it has not been applied yet. I have tried logging out and back in, have claimed discord rewards via email link.

**Comment by seriallos** [comment]
Changes should be picked up within 30 minutes. Reloading the site should show the new icon in the header and show increased time/iteration limits.

If your account is still having issues, contact me in a PM on Discord with your user info and I can dig in deeper.
