### ISSUE TITLE
Droptimizer uses lowest item level for world bosses

### ISSUE THREAD

**Issue by jag1917** [seriallos/raidbots-issues#111]
I ran droptimizer for Azeroth (world bosses) and it ran the search using ilvl 355 items (i'm 381). I ran the bosses anyways and had a ilvl 400 drop as "Heroic", but I'm pretty sure I didn't do anything special besides just kill the dude. 

Is there a way to determine when blizz scales the ilvl on the rewards to have droptimizer catch that? Here's the report I ran. https://www.raidbots.com/simbot/report/i34xJ2fd2km68hPMRtrTJn   
Ivus's boots dropped ilvl 400. https://worldofwarcraft.com/en-us/character/sargeras/jimbojiggler

Great work in everything you're doing. I just subbed a couple days ago and I'm hooked. Your website makes simming so simple. Keep it up!

**Comment by seriallos** [comment]
Oh right, Ivus loot level was increased with this new cycle.

I'll take a look.

**Comment by seriallos** [comment]
Should be fixed for new sims

**Comment by jag1917** [comment]
Oh dang. Then it's an easier solution than I even thought! Thanks for the quick fix!

**Comment by seriallos** [comment]
Yeah, base level was increased just for Ivus

I do want to look into warforge/titanforge chance but am not currently sure if/when I'll tackle it.
