### ISSUE TITLE
Ancient Knot Of Wisdom - Can't use in topgear

### ISSUE THREAD

**Issue by taggii** [seriallos/raidbots-issues#112]
Can't make any combinations with this trinket. Like it is not even there.

**Comment by seriallos** [comment]
Can you share your /simc input?

**Comment by taggii** [comment]
# SimC Addon 1.10.10
druid="Taggii"
level=120
race=night_elf
region=eu
server=dragonblight
role=spell
professions=herbalism=150/enchanting=1
talents=1323322
spec=balance

head=,id=158364,bonus_id=5448/1557/4786/5402/4775,context=35,azerite_powers=122/18/15/13
neck=,id=158075,bonus_id=4936/4929/4930/1540,context=11,azerite_level=35
shoulder=,id=166557,bonus_id=5126/1502/4786/5403/4775,context=6,azerite_powers=522/20/15/13
back=,id=160643,bonus_id=4799/1512/4784,context=5
chest=,id=158038,bonus_id=1562/5138/5383/4775,context=28,azerite_powers=200/461/85/13
wrist=,id=165447,bonus_id=5126/1502/4786,context=6
hands=,id=160618,enchant_id=5932,bonus_id=4800/1512/4783,context=6
waist=,id=166690,bonus_id=5479/1502/4786,context=3
legs=,id=162486,bonus_id=1710,context=13
feet=,id=162485,bonus_id=1678,context=13
finger1=,id=158314,enchant_id=5943,bonus_id=5009/1547/4783,context=35
finger2=,id=159461,enchant_id=5943,gem_id=153709,bonus_id=5010/4802/1552/4783,context=35
trinket1=,id=161417,bonus_id=5479/1808/42/1517/4786,context=3
trinket2=,id=160651,bonus_id=4800/1507/4786,context=6
main_hand=,id=165587,enchant_id=5963,gem_id=154127,bonus_id=4798/1808/1517/4783,context=3

### Gear from Bags
#
# Fairweather Helm (375)
# head=,id=158041,bonus_id=1562/5136/5381/4775,context=28,azerite_powers=195/18/83/13
#
# Talisman of True Treasure Tracking (58)
# neck=,id=27944,context=14
#
# Usurper's Bloodcaked Spaulders (375)
# shoulder=,id=160620,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/30/44/13
#
# Cracked Hide Shoulders (108)
# shoulder=,id=154775
#
# Jerkin of the Aberrant Chimera (375)
# chest=,id=160619,bonus_id=4823/1492/4786/4775,context=5,azerite_powers=483/21/15/13
#
# Stonemason's Guild Band (370)
# finger1=,id=165678,bonus_id=4803/4802/1562/4786,context=28
#
# Rotcrusted Voodoo Doll (370)
# trinket1=,id=159624,bonus_id=5010/1542/4786,context=16
#
# Kezan Stamped Bijou (375)
# trinket1=,id=165662,bonus_id=4803/1567/4783,context=28
#
# Sea Giant's Tidestone (365)
# trinket1=,id=165664,bonus_id=4803/4802/1557/4781,context=27
#
# Bent Punching Blade (108)
# main_hand=,id=160938
#
# G3T-00t (415)
# main_hand=,id=159641,bonus_id=5010/1587/4784,context=35
#
# Sinister Combatant's Etched Vessel of the Peerless (340)
# off_hand=,id=164697,bonus_id=1689

# Stacks of reorigination array based on hidden quest completion
# bfa.reorigination_array_stacks=10

**Comment by taggii** [comment]
Dunno why gear from bags is so big. But There is some hashtags in front of them

**Comment by seriallos** [comment]
It's working for me. Are you selecting additional items to compare?

What items are you selecting and what is the site showing you?

**Comment by seriallos** [comment]
Here's what I see when I select a 3rd trinket:

![image](https://user-images.githubusercontent.com/1010294/52095532-1c24fc80-2578-11e9-8f1f-8a95c2fa6395.png)

**Comment by taggii** [comment]
Yeah. But if you sim with that. It will only show with the 385 and 375 not the 400. Look at my pictures. 
![alltrinkets](https://user-images.githubusercontent.com/47215680/52095699-50260f00-25c4-11e9-967e-45ec119f8c0d.PNG)
![alltrinkets2](https://user-images.githubusercontent.com/47215680/52095700-50260f00-25c4-11e9-9514-7a09d23fe978.PNG)

**Comment by taggii** [comment]
5 selected, still only 3 combinations. Only showing 385 - 375 - 370 trinket.

**Comment by seriallos** [comment]
Hmm, I'm able to select all of them. Selecting all trinkets results in 10 combinations with this report: https://www.raidbots.com/simbot/report/ofVNLepKBeTrdLa8tr8waN

Somethings to try:

* Reload the site
* Remove the Paste input from the text box, reload, paste it back in
* Use the Raidbots data reset: https://www.raidbots.com/reset

**Comment by seriallos** [comment]
Are you still having issues with this?

**Comment by taggii** [comment]
No thanks, works great
