### ISSUE TITLE
[Request] Copy a top gear result as SimulationCraft addon text

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#115]
It would be nice if we could use a top gear result as input for other simulations.

I think the most versatile solution would be to provide a "copy" button in the table that lists the top gear results. This button would then put a text in the clipboard that exactly represents that specific top gear result as if we would have equipped and talented it ingame and then exported with the SimulationCraft addon.

**Comment by seriallos** [comment]
Yeah, something like this has been on my list for a while. I'd definitely like to look into it but haven't gotten there yet

**Comment by cremor** [comment]
Thanks for implementing this!

Just one additional request (which I also didn't think about when creating this issue):
Right now only the equipped gear is exported, so you can't easily use the export as input for a new top gear run. It would be great if the export contained modified gear in bags.

**Comment by seriallos** [comment]
I may look into that later once I'm sure the current code is reliable. Resolving the gear in bags is a bit trickier to get right so I left it for later
