### ISSUE TITLE
[Request] Twin-pipe Buster Cannon wrong value

### ISSUE THREAD

**Issue by franikV** [seriallos/raidbots-issues#118]
Since the new update came in, the twin-pipe buster cannon effect got buffed. The new value has to be updated on Raidbots.

**Comment by seriallos** [comment]
It's up-to-date when using Nightly SimC on the site (was updated last week in simc: https://github.com/simulationcraft/simc/commit/5a11e577b572d774dca0bb9538542a4035b66539). The tooltip may be out-of-date but that comes from Wowhead, SimC itself is using the correct numbers when running the sim.
