### ISSUE TITLE
Demonology Warlock Explosive Potential

### ISSUE THREAD

**Issue by cultz021** [seriallos/raidbots-issues#119]
It seems as though sims are still displaying the trait explosive potential as the same before it was nerfed by 35% in patch 8.1.5. I'm wondering if this is a bug or just something that hasn't been updated yet.

**Comment by seriallos** [comment]
It's probably an out-of-date tooltip from Wowhead. 99% of the time SimC is using the correct spell data under-the-hood but it may take up to a week for tooltips to catch up to changes.

Do you have a report URL I can look at?

**Comment by cultz021** [comment]
https://www.raidbots.com/simbot/report/osYAE9G6NEoG2wAhtKHATw

**Comment by cultz021** [comment]
It seems as though the helm and shoulders were fixed. The chest is still the same. Thanks for the help and quick response!

**Comment by seriallos** [comment]
Yeah, definitely a tooltip issue. The old tooltips will fall out of cache eventually and show up correctly probably within a few days.
