### ISSUE TITLE
Outlaw Sample incorrect

### ISSUE THREAD

**Issue by kolibri2304** [seriallos/raidbots-issues#120]
https://gyazo.com/9b1abf11fbbb439c5909e4c03784c4b8

you cannot adrelanine rush, while in stealth.. AR is always gonna get you out of stealth.. pls correct it. thx

**Comment by seriallos** [comment]
Under the hood, the rogue SimC module is properly simming the outlaw opener (AR then pot then stealth 1 second before pull) but the code is slightly non-standard SimC code so it doesn't show up properly in the sample output.

So the results are correct, it's a display issue in that sample. I've passed it on to the SimC devs.
