### ISSUE TITLE
Option to mark an azerite trait as "required" to have 1 when simming top gear

### ISSUE THREAD

**Issue by wheatbread** [seriallos/raidbots-issues#121]
Outlaw rogues need exactly 1 Keep Your Wits About You, and demon hunters need exactly 1 Chaotic Transformation for m+ dungeons.  There are probably other classes with this, too.  When simming gear with multiple copies of this trait + other good traits, I don't see a way to make the simulation understand that I need 1 of these as the sim doesn't like those traits and eliminates them altogether.  

It would be great if we could have an extra dropdown or something where we could select a must-have trait and how many, when simming.

**Comment by seriallos** [comment]
It's definitely something I'm interested in looking into but don't have any specific plans right now.

**Comment by AegirLeet** [comment]
I'd love this too.

**Comment by seriallos** [comment]
Never got around to this in BfA
