### ISSUE TITLE
Epic isnt allowing guild skip the line

### ISSUE THREAD

**Issue by cmlnine** [seriallos/raidbots-issues#123]
Upgraded to epic to integrate discord bot, sim works but no skip the line for guildies

**Comment by seriallos** [comment]
Have you assigned the reward on your account page?

https://www.raidbots.com/account - Discord > Guild Reward section:

![image](https://user-images.githubusercontent.com/1010294/55838052-03851580-5ad8-11e9-8aed-158b90f1c1c7.png)

If you have and are still having problems, please contact me via the support@raidbots.com email address or on Discord and provide your username and email so I can check your account specifically.

**Comment by seriallos** [comment]
Closing, please follow up via support if you are still running into problem.
