### ISSUE TITLE
Mythic+/BoD Droptimizer bugged - item level 1,level required 20, no stats

### ISSUE THREAD

**Issue by quinter89** [seriallos/raidbots-issues#125]
Hello, i wanted to check droptimizer for my character.
There is bug at many items. It shows, that ilvl is 1, no matter what key i chose. There are no stats, such as haste, crit, etc...

I tried it in 3 different internet browsers, and its all the same.
2 days ago everything worked perfectly.

I send you screenshot, where you can see bug
![Raidbots bug](https://user-images.githubusercontent.com/49895309/56557459-5f9d6e80-659b-11e9-8996-ea40e311f7ec.JPG)

**Comment by seriallos** [comment]
Looks like an issue with the Wowhead tooltips, I've sent them a message and will follow up.

SimC is still simulating them at the correct level/stats/procs so results should be fine, just tooltips are weird right now.

**Comment by quinter89** [comment]
OK, thanks for fast reply, i wanted to have all rewards from M+ in one place, thats why i opened ticket.
Or is there some other way to show all items drops from all dungeons?

**Comment by seriallos** [comment]
Not on Raidbots, not sure about elsewhere.

**Comment by seriallos** [comment]
According to Wowhead, this should go away within ~12 hours or so - temporary bug that has been resolved, just a matter of waiting for various caches to expire now.
