### ISSUE TITLE
Cannot stop getting "One of your gearsets is empty or has an empty item in it"

### ISSUE THREAD

**Issue by maikul222** [seriallos/raidbots-issues#127]
Used it without issue yesterday. There has been no changes or updates to the addon since then. Here is what simC has been giving me that is causing this to come up. You can also armory me as Tohtoh

https://docs.google.com/document/d/1ffoN3qXdyq-GvdcE6S5jVJZGyM3UnkoTTvIyOKLno1g/edit?usp=sharing

**Comment by seriallos** [comment]
If your goal is a simple sim without changing items around, switch from the Gear Compare tool to the Quick Sim tool using the navigation near the top of the page:

![image](https://user-images.githubusercontent.com/1010294/58751831-23421580-8459-11e9-8a7d-eb4544dd9122.png)

**Comment by maikul222** [comment]
No my goals are to compare items in my bag.

**Comment by seriallos** [comment]
Top Gear is the easiest for comparing item you already have.

If you're still having issues using Gear Compare, please provide a screenshot or a filled out page that is showing an error. Make sure you scroll down and add something to the "Compare Sets of Gear" section:

![image](https://user-images.githubusercontent.com/1010294/58753887-133b2d80-847b-11e9-9ba4-ca13e713b9fe.png)
