### ISSUE TITLE
Upgraded patreon from heirloom to epic

### ISSUE THREAD

**Issue by altieri43** [seriallos/raidbots-issues#13]
I upgraded my patreon from $5 to $10 but it won't upgrade on the raidbot website. how can i get it to upgrade on raidbots?

**Comment by seriallos** [comment]
Pledge updates can take up to 30 minutes to process. Reload the page after waiting a bit and you should see the higher limits.

**Comment by altieri43** [comment]
thank you

**Comment by altieri43** [comment]
Do sims include buffs from defiled runes and flasks?

**Comment by seriallos** [comment]
Yes, SimC default is to run with all buffs (lust, flask, rune, food, double pot).
