### ISSUE TITLE
Top Gear and Stat Weights do not work with Enhancement Shaman

### ISSUE THREAD

**Issue by njbongo** [seriallos/raidbots-issues#131]
Level 24 Highmountain Tauren Shaman, constant error:

Invalid SimC Input (check for copy/paste errors):

Error: Actor 'Quagul': Action 'furyCheck_FB': Cannot parse expression from 'maelstrom>=(talent.fury_of_air.enabled*(6+action.frostbrand.cost))': No expression found.

AND

SimC input is invalid, details above

**Comment by seriallos** [comment]
Looks like your SimC input has APL commands in it which won't work. Delete the SimC input and paste in what you get from the addon without adding anything else.

Raidbots/SimC also focuses on max level character and the shaman APL may not work at level 24.
