### ISSUE TITLE
Unable to run Advanced Simulation while Armory Character is Loading

### ISSUE THREAD

**Issue by Dorovon** [seriallos/raidbots-issues#132]
When a character name is entered while no realm is selected for a simulation, such as on the Quick Sim page here, a green circle is shown as the character tries to load even though no realm is selected. Because this process cannot complete without a realm, this will continue indefinitely until the fields are changed.
![no realm selected](https://user-images.githubusercontent.com/50294688/60762331-7ab84000-a01a-11e9-903d-566ae233a966.png)

While this is happening, the "Run Simulation" button is grayed out in the Advanced tab regardless of the input there.

As soon as I select any realm on the Quick Sim page, this issue goes away.

There also appears to be some issue that will cause the realm field to get cleared on those pages unexpectedly, which can trigger this issue, but I haven't been able to reproduce that.

**Comment by seriallos** [comment]
This is now fixed.

Thanks for the detailed report, I've been trying to track down some of these issues for a long time but could never figure out how to reproduce it!
