### ISSUE TITLE
Can't find any char on Aggra EU server

### ISSUE THREAD

**Issue by DancingShoes** [seriallos/raidbots-issues#133]

**Comment by seriallos** [comment]
Can you provide some character names that I can test with?

**Comment by Navalhas** [comment]
Hey there I can provide some if you need. Navalhinha 120 rogue aggra alliance.

Armory. 
https://worldofwarcraft.com/en-gb/character/eu/aggra-portugu%C3%AAs/navalhinha

**Comment by seriallos** [comment]
Thanks, I think the underlying issue is that the new Armory API maintains accents in realm names while the old API got rid of accents.

Should be able to fix this today or tomorrow, probably.

**Comment by seriallos** [comment]
Character lookup has been updated and these should now work. Please let me know if you run into any other issues!
