### ISSUE TITLE
Simulation problem

### ISSUE THREAD

**Issue by Kntbr0** [seriallos/raidbots-issues#135]
Normally and before patch 8.2, when I needed to change gems with tagged ones, I would get the most optimistic in simulation. Now it never changes me even though I'm not the most optimistic, I check it out manually by taking out of the code enchantments and gems. What can be because of this that happens to me?

**Comment by seriallos** [comment]
If you're talking about Top Gear, you might need to click "Replace Existing Gems/Enchants". Otherwise it will only put gems into items that don't have one already.
