### ISSUE TITLE
Azerite Essences Advanced Controls

### ISSUE THREAD

**Issue by wheatbread** [seriallos/raidbots-issues#137]
Azerite essences advanced controls currently shows essences you don't have that you can mark as having.  However, it does not let you choose from a minor if you're not yet level 55 on your neck.

This needs to be allowed in advanced controls so that you can see already what your BIS minor essences are ahead of time and start farming for them.

**Comment by seriallos** [comment]
Current workaround is to find the neck in your /simc input and edit the `azerite_level=` section to the level you're interested in and the UI will adjust.

**Comment by wheatbread** [comment]
Will do that, thanks!
