### ISSUE TITLE
Top Gear requires additional combinations although there are plenty of them

### ISSUE THREAD

**Issue by Hypothalannus** [seriallos/raidbots-issues#138]
I was trying to sim between a few gear pieces and azerites + a trinket on my enhancement shaman and I selected 5 azerite pieces with all of the primary traits. When clicking on find top grear,  it advises you that there are not enough combinations for the simulation,  but after a select a couple more and it displays the warning message that I cannot sim more than the maximum of 1.2mil cobinations. This seemed to be happening on this character only (Aceshaman-Laughing Skull) as I've tried simming other characters and it did what it was supposed to.

**Comment by seriallos** [comment]
Please provide your /simc input and a full list of what options you have selected so I can test this out.

**Comment by baj37q** [comment]
Hello, 
I recently purchased a premium account and am having this exact same issue. No matter what combination I put together, I get the same error.
Character = Zosox - Kil'jaeden
https://worldofwarcraft.com/en-us/character/us/kiljaeden/Zosox

**Comment by Vae2009** [comment]
Having this same issue for over a week now. I have not been able to use Top Gear for my priest.

# SimC Addon 1.12.2
# Requires SimulationCraft 820-01 or newer

priest="Vaeccine"
level=120
race=nightborne
region=us
server=area_52
role=spell
professions=tailoring=151/enchanting=150
talents=3313111
spec=shadow

azerite_essences=27:2/300573
# azerite_essences_available=5:1/12:1/27:2

head=,id=158315,bonus_id=5445/1572/4786/5417/4775,context=35,azerite_powers=405/166/30/44/13
neck=,id=158075,bonus_id=6316/4932/4933/1576,context=11,azerite_level=53
shoulder=,id=157907,bonus_id=1577/4786/5415/4775,context=28,azerite_powers=236/405/30/15/13
back=,id=159294,bonus_id=5007/1562/4786,context=16
chest=,id=165834,bonus_id=4823/1522/4786/5416/4775,context=5,azerite_powers=405/562/461/87/13
tabard=,id=157759,context=11
wrist=,id=159240,bonus_id=5005/4802/1587/4786,context=16
hands=,id=159247,bonus_id=5010/1582/4783,context=35
waist=,id=159226,gem_id=153709,bonus_id=5007/4802/1597/4784,context=35
legs=,id=168876,bonus_id=4798/1487/4786,context=3
feet=,id=163285,gem_id=154127,bonus_id=5125/4802/1582/4783,context=28
finger1=,id=165679,bonus_id=4803/1607/4786,context=28
finger2=,id=165683,enchant_id=5943,bonus_id=4803/41/1577/4786,context=28
trinket1=,id=165571,bonus_id=4798/42/1507/4786,context=3
trinket2=,id=161414,bonus_id=1517/4786,context=25
main_hand=,id=165587,enchant_id=5963,bonus_id=4799/1532/4783,context=5

### Gear from Bags
#
# Crown of the Seducer (390)
# head=,id=165818,bonus_id=4822/1507/4786/5414/4775,context=3,azerite_powers=166/405/18/537/13
#
# Shadra Silk Headband (390)
# head=,id=157905,bonus_id=1577/4786/5414/4775,context=28,azerite_powers=114/165/104/14/13
#
# Fen Spirit Headdress (390)
# head=,id=157873,bonus_id=1577/4786/5414/4775,context=28,azerite_powers=399/227/19/83/13
#
# Shadra Silk Headband (415)
# head=,id=157905,bonus_id=1607/4786/6264,context=28,azerite_powers=
#
# Fathom-Feeder's Mantle (415)
# shoulder=,id=168342,bonus_id=4822/1487/4786/6265,context=3,azerite_powers=
#
# Brood Cleanser's Amice (415)
# shoulder=,id=159254,bonus_id=5448/1587/4786/5421,context=35,azerite_powers=
#
# Shirakess Mantle (385)
# shoulder=,id=167756,bonus_id=6296/6300/1472/4786/5415,azerite_powers=
#
# Pauldrons of Vile Corruption (375)
# shoulder=,id=159267,bonus_id=4819/1542/4786/5412/4775,context=23,azerite_powers=401/165/463/15/13
#
# High Tinker's Cape (385)
# back=,id=165924,bonus_id=4798/1507/4786,context=3
#
# Azsh'ari Stormsurger Cape (385)
# back=,id=169489,bonus_id=6288/6300
#
# Wrap of Unity (35)
# back=,id=63207,context=14
#
# Silverback Cloak (405)
# back=,id=165513,bonus_id=4799/1527/4783,context=5
#
# Inmate's Straight Robe (405)
# chest=,id=159268,bonus_id=5445/1572/4786/5416/4775,context=35,azerite_powers=164/399/38/83/13
#
# Siren Mystic's Vestments (415)
# chest=,id=168341,bonus_id=4822/1487/4786/6263,context=3,azerite_powers=
#
# Vestments of the Afterlife (405)
# chest=,id=165498,bonus_id=4823/1522/4786/5416/4775,context=5,azerite_powers=401/165/105/15/13
#
# Renowned Guild Tabard (1)
# tabard=,id=69210,context=14
#
# Silk Cuffs of the Skycap'n (390)
# wrist=,id=159227,bonus_id=5002/4802/1562/4783,context=35
#
# Waveblade Farseer's Bindings (385)
# wrist=,id=170306,bonus_id=6288/6300/4802
#
# Twisted Sisters Handwraps (420)
# hands=,id=159272,bonus_id=5005/43/1592/4783,context=35
#
# Leggings of Dire Research (400)
# legs=,id=165499,bonus_id=4799/1522/4786,context=5
#
# Fortified Deep Sea Breeches of the Aurora (400)
# legs=,id=165386,bonus_id=1707,context=13
#
# Shirakess Footwraps (400)
# feet=,id=167752,bonus_id=6300/6289/1487/4786
#
# Jade Ophidian Band (400)
# finger1=,id=162544,bonus_id=5010/1572/4786,context=16
#
# Lord Waycrest's Signet (410)
# finger1=,id=158362,bonus_id=5010/1582/4783,context=35
#
# Pocket-Sized Computation Device (410)
# trinket1=,id=167555,gem_id=167556/168744,gem_bonus_id=0/1472:4786,bonus_id=1482,context=11
#
# Ancient Knot of Wisdom (385)
# trinket1=,id=166793,bonus_id=5479/1502/4786,context=3
#
# Goblet of Glittering Favor (400)
# main_hand=,id=165592,bonus_id=4799/1522/4786,context=5
#
# Fishing Pole (1)
# main_hand=,id=6256,context=14
#
# Rattling Jar of Eyes (410)
# off_hand=,id=159668,bonus_id=5010/1582/4783,context=35

**Comment by seriallos** [comment]
It's likely an issue with an item/gem/essence not selected. Check each section of the page for an error message to see if there's something wrong (invalid gem selections, missing azerite essence, etc).

Alternatively, you can use the Reset page to "factory reset" the Raidbots client settings for your browser: https://www.raidbots.com/reset - this will often resolve weird issues or other options that may be causing problems that you aren't able to diagnose.
