### ISSUE TITLE
Weird Auto-fill Issue

### ISSUE THREAD

**Issue by Potaetoe** [seriallos/raidbots-issues#14]
I use Google Chrome 59.0.3071.115. I've cleared my cache, cookies, etc. But the input element for the armory search seems to auto-fill a previous guildmate of mine automatically. This happens on two separate computers. I've disabled all extensions to make sure they were not causing the issue either. This is problematic when using Top Gear, Gear Compare, Relic Compare, and Talent Compare because after changing the input (to SimC string or another name) it'll revert back after making a few selections.

**Comment by seriallos** [comment]
That's definitely a weird one... Going to ask you to some possible duplicate work just to make sure there's not something weird going on with how Chrome handles cache clearing / extensions.

Have you looked specifically at Chrome's autofill settings to see if there's an entry there? Possibly looked at saved passwords, too. Not sure if it's possible for a random field to get "stuck" as a password but I can imagine it happening.

Do you use a password manager (either as an extension or a standalone program)? Sounds like you tried turning off extensions but some of the managers can be really aggressive about auto filling stuff.

You might want to try specifically nuking the Local Storage for www.raidbots.com (and/or raidbots.com). I believe to get to that section you have to go to Chrome Settings > Advanced > Content Settings > Cookies > Search for "raidbots" > "www.raidbots.com" > Delete all "Local storage" options. I'm not sure if this would be deleted with a higher level "clear cache/cookies" or not so it's worth a double check.

**Comment by Potaetoe** [comment]
Seems to be LastPass, but not sure where it's saving the form data. Thanks for the help.

**Comment by seriallos** [comment]
LastPass is _really_ aggressive at saving inputs that look like usernames.  I'll take another look at the fields and LastPass, could be that either you or I have an older version (I've taken at least one pass on fiddling with the fields to try to make LastPass not autocomplete).

I might be able to play around with field names a bit more to see if I can make LastPass believe these are not login forms.
