### ISSUE TITLE
Cannot connect patreon subscription on raidbots when existing card paid subscription exists

### ISSUE THREAD

**Issue by Chaosaze** [seriallos/raidbots-issues#141]
Issue: Patreon cannot be connected to raidbots when an existing card paid subscription exists (done with stripe). This happens even if the patreons subscription "level" is higher.

Below is an image of the view in raidbots account page where an existing "Rare"-level card subscription was cancelled. Even though the the newer patreon made subscription was up and running, it was not possible to connect that subscription to the raidbots. This issue existed after 48 hours of the patreon purchase.

![image](https://user-images.githubusercontent.com/32591935/62718840-5384d200-ba0f-11e9-893d-32301ab34236.png)

**Comment by seriallos** [comment]
Closing due to age. This is not currently on the roadmap.
