### ISSUE TITLE
Patreon Link Problem 

### ISSUE THREAD

**Issue by Dafreqshow** [seriallos/raidbots-issues#147]
**Describe the bug**
When I try to link my account to patreon i get the error
Uh oh, something went wrong.
invalid json response body at https://api.patreon.com/oauth2/token reason: Unexpected token < in JSON at position 

**To Reproduce**
1. www.raidbots,com
2. Click on account-> Connect to patreon
3. the site shows the error 

**Expected behavior**
Well that i could link the accounts 

**Screenshots**
https://prnt.sc/pbyllz

**Comment by seriallos** [comment]
There were some intermittent problems with the Patreon API a couple days ago that I believe were the source of the problem you ran into. _Should_ be working now.
