### ISSUE TITLE
Multiple same name weapon but different result

### ISSUE THREAD

**Issue by liuxuan30** [seriallos/raidbots-issues#148]
link:https://www.raidbots.com/simbot/report/bcRAaNTACZeH3LMAwJ7bLX

So I was comparing `Notorious Gladiator's Bonegrinder` and `Tentacle Crusher`, both are lvl 430, on switching between Main hand and off hand for my fury warrior build.

The only difference is the damage range, the in game damage range of `Notorious Gladiator's Bonegrinder` is 11xx ~ 15xx(which is not shown by raidbot), and `Tentacle Crusher` is `8xx ~ 18xx`(which is the same as raidbot displays). they are the same item lvl 430, so the weapon DPS is the same.

The issue for raidbot is, when I search for Bonegrinder, it will prompt 4 exact same name weapon, I compared them one by one, with name bone1 - bone4 as the original index, and all modified their item lvl to 430, however, the result is different.

For example:
![image](https://user-images.githubusercontent.com/4375169/65842558-f0ecea00-e35e-11e9-9d02-53584391401e.png)
it shows the item is 430, however the weapon damage is obviously low. And it's seems adding Int rather than Strength. It's kind of weird for a double hand mace.

I'm thinking this is a bug and very confusing when you tried to search for this weapon, you should understand my point now. It's not clear which item I should pick exactly where comparing. It should add more information to help decide when searching

**Comment by seriallos** [comment]
I just updated Gear Compare to show tooltips in the dropdown menu which should help identify items of the same name with different stats.

The annoyance here is that there is are both int and str versions for both alliance and horde which is why there are 4 items.

https://www.wowhead.com/search?q=Notorious+Gladiator%27s+Bonegrinder

**Comment by liuxuan30** [comment]
thanks!
