### ISSUE TITLE
Crafted items such as jewelry sim with no stats in Gear Compare

### ISSUE THREAD

**Issue by NoSavingThrow** [seriallos/raidbots-issues#15]
Need a way to choose the stat configuration for crafted items that have multiple stat spreads when choosing items from the dropdowns in Gear Compare. An example is Grim Furystone Gorget - sims as if it has nothing but stamina. 

See report here: https://www.raidbots.com/simbot/report/5H7AjmCSxxRMc6VY9amtoT

**Comment by seriallos** [comment]
This is a known limitation right now. I haven't built in full knowledge of random affix gear (it's all bonus ID shenanigans). This is on my list but I haven't gotten to it yet.

That said, if you have a piece of gear already, it will work when using something like Top Gear (and SimC will handle it correctly if simulated with the proper bonus IDs)

**Comment by seriallos** [comment]
Months later, this just got fixed! Gear Compare now lets you choose the affix for crafted gear.
