### ISSUE TITLE
Haze of Rage set to 70 Agi when testing

### ISSUE THREAD

**Issue by TheWombatman** [seriallos/raidbots-issues#150]
**Describe the bug**
I have been regularly running raidbots, but currently, the Azerite Trait "Haze of Rage" does not display the appropriate amount of agility bonus per the gear ilevel. my 435 Scalemail of Unnatural Selection is showing 1,322 which is more appropriate for my level skewing intended results.

**To Reproduce**
1. Simulate gear with the azerite trait on raidbots.
2. Scroll down to check buff uptime, haze of rage hover shows only 70 additional agi given for that ilevel.

**Expected behavior**
An increase in dps since the different show is approximately 1,250 agi.

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here
https://www.raidbots.com/simbot/report/biPGqtaMkrkkjnK7LE3tQm

**Character or /simc input**

For "Load from Armory":

* US
* Illidian
* Kruellá

For "Load from SimC Addon":

Paste your /simc input
# SimC Addon 1.12.3
# Requires SimulationCraft 820-01 or newer

hunter="Kruellá"
level=120
race=orc
region=us
server=illidan
role=attack
professions=leatherworking=175/skinning=175
talents=1223211
spec=beast_mastery

azerite_essences=5:3/300573/12:4/300575/300576/14:3/300577
# azerite_essences_available=4:4/5:3/6:4/12:4/14:3/15:2/22:2/23:2/27:3/28:4/32:1

head=,id=159398,bonus_id=5448/1617/4786/6270/4775,context=35,azerite_powers=211/193/459/15/13
neck=,id=158075,bonus_id=6316/4932/4933/1610,context=11,azerite_level=70
shoulder=,id=159393,bonus_id=5448/1617/4786/6271/4775,context=35,azerite_powers=211/366/31/85/13
back=,id=155884,gem_id=168639,bonus_id=5010/4802/1612/5860/4784,context=35
chest=,id=167767,bonus_id=6300/6299/1517/4786/6266/4775,azerite_powers=211/366/30/15/13
wrist=,id=159380,bonus_id=5010/40/1612/5850/4784,context=35
hands=,id=159399,bonus_id=5010/1612/4783,context=35
waist=,id=168870,bonus_id=4800/1517/4786,context=6
legs=,id=168727,gem_id=168639,bonus_id=1679,context=13
feet=,id=168724,gem_id=168639,bonus_id=1676,context=13
finger1=,id=159461,enchant_id=6108,bonus_id=5010/1602/5850/4783,context=16
finger2=,id=162542,enchant_id=6108,gem_id=168639,bonus_id=5010/4802/1612/4783,context=35
trinket1=,id=169311,bonus_id=4798/1487/4786,context=3
trinket2=,id=169314,bonus_id=4799/1502/4786,context=5
main_hand=,id=168273,enchant_id=5955,bonus_id=4800/1517/4786,context=6

### Gear from Bags
#
# Gardbrace of Fractured Reality (435)
# shoulder=,id=169588,bonus_id=4823/1502/4786/6268/4775,context=5,azerite_powers=367/211/30/15/13
#
# Shoulderguards of Crushing Depths (435)
# shoulder=,id=168354,bonus_id=4823/1502/4786/6268/4775,context=5,azerite_powers=211/369/459/14/13
#
# Azsh'ari Stormsurger Cape (385)
# back=,id=169489,bonus_id=6288/6300
#
# Scalemail of Unnatural Selection (435)
# chest=,id=168352,bonus_id=4823/1502/4786/6266/4775,context=5,azerite_powers=211/161/21/203/13
#
# Ori's Tidal Bracers (425)
# wrist=,id=170304,gem_id=168639,bonus_id=6300/4802/6294/1512/4786
#
# Poen's Deepsea Handgrips (425)
# hands=,id=170335,gem_id=168639,bonus_id=6300/4802/6294/1512/4786
#
# Vim's Scalecrusher Chain (425)
# waist=,id=170369,gem_id=168639,bonus_id=6300/4802/6294/1512/4786
#
# Akana's Reefstrider Treads (425)
# feet=,id=170142,gem_id=168639,bonus_id=6300/4802/6294/1512/4786
#
# Dribbling Inkpod (430)
# trinket1=,id=169319,bonus_id=4799/1502/4786,context=5
#
# Harlan's Loaded Dice (440)
# trinket1=,id=155881,bonus_id=5010/1612/4783,context=35
#
# Dead-Eye Spyglass (430)
# trinket1=,id=159623,bonus_id=5010/1602/4786,context=16

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
This is a Wowhead tooltip error and I've passed it along to them.

SimC is using the correct value which you can look at in the full HTML report:

https://www.raidbots.com/simbot/report/biPGqtaMkrkkjnK7LE3tQm/simc

![image](https://user-images.githubusercontent.com/1010294/69302839-2af8a080-0bd8-11ea-932f-0660797f854f.png)
