### ISSUE TITLE
disc priest - death throes azerite/cyclotronic blast not working

### ISSUE THREAD

**Issue by ropedope** [seriallos/raidbots-issues#151]
The sim thinks disc can't use death throes because it's a shadow "specific" trait and isn't calculating SWP/purge the wicked properly. Also, the sim isn't using cyclo at all simming disc.

I understand it's not popular to sim healer dps, but it's quite relevant for disc m+.

**Comment by seriallos** [comment]
Posted this to SimC issues.

Do you have Raidbots report URLs that show each of these unexpected behaviors?
