### ISSUE TITLE
[Request] Droptimizer, add option to sim with a socket

### ISSUE THREAD

**Issue by mdk12** [seriallos/raidbots-issues#152]
Could you please add the option to add a socket while simming with droptimizer, like we already have for benthic armor. Would be a huge improvement instead of doing gear compares/advanced sims for it.

**Comment by seriallos** [comment]
Sockets can be simmed for "farmable" content (M+, Benthic) in Droptimizer. I do not currently have any plans to allow simming sockets on weekly lockout content in Droptimizer as the chance is very low (~10%) and would likely make analyzing the results much more difficult.

I am interested in hearing more about your specific use case - what question are you trying to answer and what are you doing to try to sim it?

**Comment by seriallos** [comment]
I changed my opinion on this and now you can choose to sim sockets in most cases on Droptimizer.
