### ISSUE TITLE
[Request] Support for Timewarped Trinkets.

### ISSUE THREAD

**Issue by awRobinson** [seriallos/raidbots-issues#153]
I received a Timwarped, Warforged Variable Pulse Lightning Capacitor. In practice, if it pulling very high dps. In the simulation, it's not so hot. I believe the equip effect may not being simulated correctly. Might be worth a look for this trinket and other Timewarped trinkets.

**Comment by seriallos** [comment]
SimulationCraft generally only supports items from the most recent expansion or two.

I'm not aware of any plans to add older items but you can always voice a request on the SimC project page: https://github.com/simulationcraft/simc
