### ISSUE TITLE
Quick Sim on DH

### ISSUE THREAD

**Issue by Agoostoos** [seriallos/raidbots-issues#154]
https://www.raidbots.com/simbot/report/sN5XCn27kL7U8VrBVUpHDn
Click the link of my SIM on my demon hunter. It will show that Cyclotronic Blast was used 3 times in a 300 second fight. Something seems wrong there.

![unknown](https://user-images.githubusercontent.com/59544446/71788352-5a7c3480-2fef-11ea-82cc-fad84d05dc81.png)

**Comment by seriallos** [comment]
I'm not sure what the issue is. 300 seconds is 5 minutes, cyclo cooldown is 2 minutes (120 seconds).

So cyclo is roughly used at the start of the fight (at 0 seconds), 2 minutes later (at 120 seconds), and then 2 minutes later again (at 240 seconds).

**Comment by Agoostoos** [comment]
Doesn’t that mean 6 minutes? 3 uses of cyclo is 6 minutes. 


Sent from Yahoo Mail for iPhone


On Sunday, January 5, 2020, 10:37 PM, Dave Hendler <notifications@github.com> wrote:


I'm not sure what the issue is. 300 seconds is 5 minutes, cyclo cooldown is 2 minutes (120 seconds).

So cyclo is roughly used at the start of the fight (at 0 seconds), 2 minutes later (at 120 seconds), and then 2 minutes later again (at 240 seconds).

**Comment by Agoostoos** [comment]
Nvm. We are all lacking brain cells. 


Sent from Yahoo Mail for iPhone


On Sunday, January 5, 2020, 10:37 PM, Dave Hendler <notifications@github.com> wrote:


I'm not sure what the issue is. 300 seconds is 5 minutes, cyclo cooldown is 2 minutes (120 seconds).

So cyclo is roughly used at the start of the fight (at 0 seconds), 2 minutes later (at 120 seconds), and then 2 minutes later again (at 240 seconds).
