### ISSUE TITLE
Weapon "Devastation's Hour" is missing its fixed corruption effect

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#155]
**Describe the bug**
The weapon "Devastation's Hour" always comes with the "Twilight Devastation" corruption effect but neither the Droptimizer nor Gear Compare seem to know this.

**To Reproduce**
1. Run the Droptimizer for Ny'alotha with "default" corruption effects for a character that can use two-handed swords.
2. Check the result and see that the weapon doesn't have a corruption effect.

OR

1. Search for "Devastation's Hour" in Gear Compare.
2. Notice that it offers all corruption effects instead of just the one it always comes with (like other weapons with a fixed corruption effect do).

**Expected behavior**
"Devastation's Hour" should have its fixed corruption effect applied.

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/r7LYwMRx97Jf3WTiJzqAr4

**Character or /simc input**
For "Load from Armory":

* Region (US, EU, etc): EU
* Realm / Server: Blackmoore
* Character Name: Cremor

**Comment by seriallos** [comment]
👍 Added the "static" corruption to a bunch of weapons I had missed. Thanks for the note.

Should be live on the site shortly
