### ISSUE TITLE
[Request] Support for flashpoint_threshold in Custom APL

### ISSUE THREAD

**Issue by neoxz04** [seriallos/raidbots-issues#157]
The `flashpoint_threshold` option for destruction warlocks was implemented on this commit: https://github.com/simulationcraft/simc/commit/e7c91df0da20a8c5d753c1443c78c2b43ad567be

and documented on this page: https://github.com/simulationcraft/simc/wiki/Warlocks

Raidbots currently flags this option as invalid or unsupported, as shown in the attached screenshot.
![raidbots-fp](https://user-images.githubusercontent.com/19227594/73129823-2ae5a880-4040-11ea-96b6-f2ecc5ba8705.png)

**Comment by seriallos** [comment]
That option should now be available for use in the Custom APL and SimC Options
