### ISSUE TITLE
Two identical sims showing vastly different results for trinkets, 12 hours apart.

### ISSUE THREAD

**Issue by Spanky2k** [seriallos/raidbots-issues#162]
I ran a droptimiser sim for heroic raid loot in Ny'alotha 12 hours ago. The sims were done on my Brewmaster monk with Windwalker loot spec. I ran the same sim again just now and the results for the trinkets are very different. 12 hours ago, Writhing Segment was simming as a 1.3% upgrade but now it is simming as a 0.3% downgrade. Torment in a Jar also went from a 0.8% upgrade to a 1.0% downgrade. The simc builds are the same. My gear, HoA, cloak, essences etc is all identical. The only difference that I can see is that the newer sim seems to think my ilvl is 457 when it was 455 in the sim 12 hours ago (and is 455 in game). The ilvl on each item within both sims in the report is identical; I hovered over every one to check.

Sim from last night: https://www.raidbots.com/simbot/report/xshw549su1ug9n6tfVnsie
Sim from now: https://www.raidbots.com/simbot/report/pP7L55TSdSKRYgXbv9imRs

**Comment by seriallos** [comment]
My guess is something is with the Mechagon trinket when loading from Armory.

Last night's sim used an Armory lookup, today's sim used /simc input. I'll take a look to see if something is funny with the Armory data.

**Comment by seriallos** [comment]
Something is definitely weird with the Armory API for this item and/or how SimC is handling it. Looks like the mech trinket is evaluated at its base item level (410) when using an Armory lookup. It does use the right item level from /simc input.

I've forwarded the bug over to the SimC folks to see if there's something they can do.

**Comment by seriallos** [comment]
This is now fixed, Mech trinket should have the right item level when loading from Armory

**Comment by Spanky2k** [comment]
Awesome, thanks!
