### ISSUE TITLE
Strength of the warden sims without 10 corruption resistance

### ISSUE THREAD

**Issue by Riketta** [seriallos/raidbots-issues#169]
**Strength of the warden (tank essence) sims without 10 corruption resistance**
In my case I used to sim it as level 2 minor essence.
Also top result with 68 corruption marked as best solution with corruption cap 59. Which right if you count -10 by essence, but wrong if you don't.

Example:
You can see sim result with 68 corruption instead of 58 in real.
https://www.raidbots.com/simbot/report/7MCkfQNFm9DsWoXoK29JJZ

**Comment by seriallos** [comment]
This should be fixed in the Nightly SimC version. I’ll roll it out to Weekly in the next day or two


-Dave
