### ISSUE TITLE
No upgrade & 1.2mio or 2.4 mio ?

### ISSUE THREAD

**Issue by Dagoberrto** [seriallos/raidbots-issues#17]
Yesterday i had view days left of status "Heirloom" but i decide to test "Epic" for 10$. 9 hours later i log in and i was still "Heirloom". I log out on raidbots, patreaon, discord. Than i logged in on discord and patreaon again . Patreon is showing me the : 

http://imgur.com/a/MfAPk  (When hover over this link, you see only 1 of 2 images)

And on this site https://www.patreon.com/settings/account i see "disconnect" so i am connected already.

So my questions are : 

What i need to do to get status "Epic" ?
And what i get - you write 2 diffent things 1.2mio or 2.4 mio ?

**Comment by Dagoberrto** [comment]
Could it bee some trouples with payment ? Because i did 2 times clicked on "update pledge" and than i see a happy Hamster telling me : "Woo! Here's a note from Seriallos:....." But when i login on Paypall i dont see the -10$

**Comment by seriallos** [comment]
You need to choose the higher level reward level, not just increase the amount you are pledging.  Right now you have Heirloom selected but you are paying more than the minimum for that pledge level.

You should be able to change your pledge to choose Epic and you'll get the updated rewards.

Payment happens at the beginning of the month, not when you pledge.

**Comment by Dagoberrto** [comment]
Nice..now i feel dump ^^ Thanks a lot!
