### ISSUE TITLE
BM Hunter, Animal Companion Damage

### ISSUE THREAD

**Issue by Beeblebug** [seriallos/raidbots-issues#170]
Even though the in game toolttip says it only does melee, it also does Stomp, so this should be included in Sims

**Comment by seriallos** [comment]
SimC does trigger Stomp for the animal companion.

If you run a Quick Sim you can check the Full HTML Report from SimC which shows some more details. Stomp from Animal Companion is listed under Barbed Shot and you can see the Stomp from your pet as well:

![image](https://user-images.githubusercontent.com/1010294/73876490-f033fb00-480b-11ea-8cc3-13c7161b40e4.png)
