### ISSUE TITLE
Character not found

### ISSUE THREAD

**Issue by jeremyw74** [seriallos/raidbots-issues#171]
I keep getting "Character not found" error for my character on Zul'jin, Elyassdemon.

**Comment by seriallos** [comment]
This is an issue with the Blizzard API. You can try logging in and out again and hope that Blizzard updates your character in that system.

Alternatively, you can use the SimC addon in-game to get input that you can run on the website. This is always up-to-date, doesn't require logging out, and has more details about your character than the Blizzard API import.
