### ISSUE TITLE
Echoing Void item simulation bug

### ISSUE THREAD

**Issue by Weper0** [seriallos/raidbots-issues#172]
I did a simulation with multiple gloves, one of them has Echoing Void rank 2 and it does much less DPS than a non-corrupted item.

**For example:** [Handguards of the Insatiable Maw](https://www.wowhead.com/item=173508/handguards-of-the-insatiable-maw&bonus=6412:4803:6513:6516:1502:4786) (**445 ilvl** | **non-corrupted**) + [Cincture of the Azerite Arsenal](https://www.wowhead.com/item=159333/cincture-of-the-azerite-arsenal&bonus=6534:6578:6579:6538:6515:1642:4786) (470 ilvl | Twilight Devastation rank 2) does **-3.1%** less damage than my current gear, that's okay.
**But:** [Grips of Electrified Defense](https://www.wowhead.com/item=159337/grips-of-electrified-defense&bonus=6536:6578:6579:6550:6515:1647:4786) (**475 ilvl** | **Echoing Void rank 2**) + [Cincture of the Azerite Arsenal](https://www.wowhead.com/item=159333/cincture-of-the-azerite-arsenal&bonus=6534:6578:6579:6538:6515:1642:4786) (470 ilvl | Twilight Devastation rank 2) does **-25.1%** less damage, that's not really okay. 
I mean how can a **475 ilvl corrupted item** with BiS stats do much **less damage** than a **445 ilvl non-corrupted item** with crappy stats?

**Link:** [https://www.raidbots.com/simbot/report/8iopnatWhiYvasfc1BLDG3](https://www.raidbots.com/simbot/report/8iopnatWhiYvasfc1BLDG3)

**Comment by seriallos** [comment]
That sim configuration (40 seconds, Hectic Add Cleave, 5 bosses) is a **very** unusual configuration and is not well supported by SimC. I believe Rogue is a class that generally doesn't handle Hectic Add Cleave particularly well and the 40 seconds and multiple bosses is just adding additional layers of things that go sideways.

40 second patchwerk seems fine: https://www.raidbots.com/simbot/report/qKpRrZkmgxpRtapToAPtk3

5 minute Hectic Add Cleave seems fine: https://www.raidbots.com/simbot/report/bfSCJNxf9sAoGWLHJCmoGd

I recommend checking with your class Discord to see what they recommend for whatever scenario you are trying to sim. Support for short/multitarget adds varies a lot between classes and class experts on Discord will give you a better idea of what might be useful.
