### ISSUE TITLE
Corrupted weapon pourcentage damage bug 

### ISSUE THREAD

**Issue by Redsayan** [seriallos/raidbots-issues#173]
Hi All,
On wowhead i see Echoing void spell damage have:
    Tier 1: 25 Corruption: 0.4% of Max Health per stack
    Tier 2: 35 Corruption: 0.6% of Max Health per stack
    Tier 3: 60 Corruption: 1% of Max Health per stack

But on Raidbots sim i see for my character 
Tier 2 corruption: 6% of maw health per stack

Why this diffrence? is it Bug?

**Comment by seriallos** [comment]
Wowhead tooltips often lag behind for a bit. The values are correct in the actual sim. Tooltips are just used for reference, they are not used internally in SimC.
