### ISSUE TITLE
Incorrect DPS increase

### ISSUE THREAD

**Issue by ruudvdlinden** [seriallos/raidbots-issues#174]
https://www.raidbots.com/simbot/report/dLec3tEd6hdQbaP3CcDax4 suggests that the new waist, with a corruption trait that clearly doesn't contribute to my DPS, is an upgrade. Yet, when I sim the same item purified, it's a DPS loss, which is to be expected.

**Comment by seriallos** [comment]
The Top Gear set has 63 corruption which activates your Heart of Darkness Azerite power which is where the extra DPS is coming from. Your current gear has 23 corruption which is not enough to activate Heart of Darkness.
