### ISSUE TITLE
Frost Mage (Ice Lance / Thermal Void) Icicle damage is way off.

### ISSUE THREAD

**Issue by Pringleblast** [seriallos/raidbots-issues#175]
Icicle damage on Sim seems to be ten times too low.

On the Raidbots Sim, Icicle makes up roughly 2.4% of my damage, with a total of 21 hits over a 6 minute Patchwerk style fight.

However, when I hit the target dummy for 6 minutes, Icicle damage is 25% of my damage and hit roughly 10x  more often than simmed.

My results hitting the dummy are also 2-4k dps greater than the sim. (Seems to be based on tentacle mind flay variance).

 Int buffed, 2x potion, heroism, greater flask, 93 crit food, 

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/kFTkJzoKadj6UHknLEwQ5d

Results consistent over several pulls and several sims.

* Region (US, EU, etc): US
* Realm / Server: Dath'Remar
* Character Name: Pringleblast

**Screenshots**

![World Of Warcraft - Retail Screenshot 2020 02 21 - 14 27 01 04](https://user-images.githubusercontent.com/61300050/74995700-81ff6180-54b6-11ea-8a3f-d0c63fdaca7f.png)
![World Of Warcraft - Retail Screenshot 2020 02 21 - 14 26 31 00](https://user-images.githubusercontent.com/61300050/74995724-90e61400-54b6-11ea-9e1f-3bdb6b25809d.png)

**Comment by seriallos** [comment]
Icicles are reported differently in SimC. They are bundled with the spell that procced them so you have toggle Frostbolt and Flurry to see those values:

![image](https://user-images.githubusercontent.com/1010294/75001561-ff779300-541e-11ea-9b39-a502dd00b946.png)

In that sim, Icicles are about ~25% of your damage which matches your in-game testing.
