### ISSUE TITLE
Outlaw Rogue - Changing Simc Defaults APL with Weaponmaster talent

### ISSUE THREAD

**Issue by Mysthen** [seriallos/raidbots-issues#176]
Hello,

I'd like to report a feature request for Outlaw Rogue playing with Weaponmaster talent instead of the commonly used Quick Draw.

With this talent set, we never use the spell Pistol Shot even while having an Opportunity proc. But the Simc Defaults APL uses Pistol Shot with Opportunity procs, resulting in a simulated DPS loss.

Also, while playing with 3x Keep your wits about you azerite traits, according to my in game tests, the roll of dice Skull and Crossbones brings a lot DPS but the Simc Defaults APL re-roll the dices while having it.

So is it possible to modify the Outlaw Rogue Simc Defaults APL in this way ?

Thank you very much for your support,
Best regards,
Mysthenia

**Comment by seriallos** [comment]
SimC issues are best reported on the SimC project itself so the rogue class module folks see it:

https://github.com/simulationcraft/simc/issues

You might also be able to find a rogue maintainer in the Ravenholdt or SimcMinMax Discord.
