### ISSUE TITLE
Reverse Harm

### ISSUE THREAD

**Issue by Sephirithane** [seriallos/raidbots-issues#178]
**Describe the bug**
Reverse Harm is not appearing in sims anymore. It used to but now it does not.

**To Reproduce**
I simply ran a sim.

**Expected behavior**
I expected to see Reverse Harm on the Damage Breakdown list.

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/jdPxVKCFV3vyh4Ava3gwt2

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

US
Thunderlord
Juvi

**Comment by seriallos** [comment]
Looks like this is a display issue on the Raidbots report. If you look at the full HTML report from SimC, (https://www.raidbots.com/simbot/report/jdPxVKCFV3vyh4Ava3gwt2/simc) Reverse Harm from C&S _is_ being simmed, it's just not being picked up by the Raidbots result page for some reason.

I'll look into why it's not showing up on the Raidbots page!

**Comment by Sephirithane** [comment]
Thanks, Seriallos!

**Comment by seriallos** [comment]
Reverse Harm now shows up on Quick Sims.

Underlying issue is that SimC reports it as a heal with a sub-spell that does damage and my report was not handling that correctly. The report now properly handles this kind of data properly.
