### ISSUE TITLE
Critical: Site not loading due to JS issue (Sentry integration)

### ISSUE THREAD

**Issue by mirague** [seriallos/raidbots-issues#179]
**Describe the bug**
raidbots.com does not load due to a JS error:
```
integration.js:49 Uncaught TypeError: e.setupOnce is not a function
    at integration.js:49
    at integration.js:63
    at Array.forEach (<anonymous>)
    at oe (integration.js:61)
    at t.e (baseclient.js:54)
    at new t (client.js:21)
    at sdk.js:14
    at dsn (sdk.js:84)
    at Module.<anonymous> (index.js:38)
    at o (bootstrap:63)
    at Object.<anonymous> (_charsEndIndex.js:16)
    at o (bootstrap:63)
    at bootstrap:198
    at simbot.6f650cefb27f87204d03.js:1
```

Tested in both Firefox and Chrome (Brave) with AdBlockers turned off.

**To Reproduce**
1. Turn off all adblockers 
1. Go to raidbots.com
2. See site not loading
3. Look at console and observe error

**Expected behavior**
The site should load

**Screenshots**
![image](https://user-images.githubusercontent.com/178117/76297772-b2b60800-62b8-11ea-8621-b481fdc0785d.png)

**Comment by mirague** [comment]
Pretty major issue I would say @seriallos

**Comment by seriallos** [comment]
It's fixed now, reload and you should be good

**Comment by mirague** [comment]
Cheers for quick turnaround! 🚀
