### ISSUE TITLE
Relic sims brewmaster 

### ISSUE THREAD

**Issue by FBM96** [seriallos/raidbots-issues#18]
I simmed with 910 same trait and left the other 2 unchanged and get 10k lower sim https://www.raidbots.com/simbot/report/wXYNGga9q5gFU6Joju1toZ

then i simmed with 910 same trait and manualy changed to my current relics for the other 2 and still got 10k lower, i then simmed with nightly build on my pc and got 2k more with raw imput from your site.
https://www.raidbots.com/simbot/report/ridErtiXNNUZ2SrTWDjcdd

my own sim in attached files
![29995767d269d4724255a56ea14d98b8](https://user-images.githubusercontent.com/30320111/28421330-21d9d9d8-6d65-11e7-842a-e126fe2826f7.png)

**Comment by FBM96** [comment]
sorry forgot to mention my current relic is 905 :)

**Comment by seriallos** [comment]
Is the issue that Raidbots and local SimC are showing different values?  If so, that's generally expected - Raidbots and local SimC are almost always going to be slightly different versions of the code and it's often very likely that there is a configuration difference between the site and local.

**Comment by FBM96** [comment]
well even then it doesnt make sense that a 905 relic sims higher than a 910 with the same trait

**Comment by seriallos** [comment]
Ahhhh, gotcha. Now I understand.

I believe this is an issue with the simulation mode that Raidbots uses (single actor batch). There are some issues with tanks where the enemy only attacks the "base" actor and so copies end up never being attacked which can change the results. Local simc doesn't use single actor batch by default.

It's on my list to look at this but I haven't delved into it yet. I also believe that Top Gear is not affected by this issue (it uses a third simulation mode, profilesets) but I'll need to double check on that.
