### ISSUE TITLE
Display recent simulation jobs

### ISSUE THREAD

**Issue by mirague** [seriallos/raidbots-issues#180]
**Is your feature request related to a problem? Please describe.**
When running a simulation and browsing through the site after that, your hard waiting time work is lost unless you dig through your browser history to find the unique link for the simulation report.

**Describe the solution you'd like**
It would be very useful to show the X latest simulations you've run so you can easily find your way back to them. Would be fine to store these in the browser's local storage.

**Comment by seriallos** [comment]
The button in the top right corner of the site opens up a sidebar with up to 50 of your recent sims if you are logged in:

![image](https://user-images.githubusercontent.com/1010294/76300239-7f478f00-6260-11ea-9ad0-ee61eb32abab.png)

**Comment by mirague** [comment]
Ah didn't notice that button, thanks! :)
