### ISSUE TITLE
working around my sims

### ISSUE THREAD

**Issue by Italist** [seriallos/raidbots-issues#181]
My workflow when simming usually involves 4-5 sims to evaluate gear around different fight conditions.
I also sim for multiple corruption levels as some encounters require lower corruption than usual.
To retrieve my sims,  compare them, and better understand my builds I look at my gear's history...
I'm currently filtering on my google chrome history page "chrome:history" querying "top gear - 'charactername'".
I often compare different hecticaddcleave builds and patchwerk builds for my toon. 
On my hunter, I run both BM and Surv sims, and they return similar dps. They are indistinguibile when I  look them up on my browser's history.
Today I discussed this with guildmates: all had the same workflow, but only 3 out of 5 used google chrome search history.

Therefore I have found the following assumptions:

- _Design assumption 1:_ Players sim and compare different builds inthe context of the same character specialization
- _Design assumption 2:_ Players compare different gear builds within the same fight styles
- _Design assumption 3:_ Players distinguish their builds (and store them as sets in wow character pane) per fight style and corruption level

I highly suggest to add means to filter the sim history within raidbots per character/spec/fightstyle/corruptionlevel. 
Alternatively, it would be simple to add fight style, spec, corruption level to the title of the webpage.

Thank you
Ita

**Comment by Mirimes** [comment]
Idk if it can be useful, but to search a specific sim i use a chrome extension called "rename tab", so when a sim is done i just rename the tab how i want and if i'll ever need it again it's saved in browser history with the name i choose

**Comment by seriallos** [comment]
Closing due to age. This is not currently on the roadmap.
