### ISSUE TITLE
Add a " Sim socket " button/feature in Top Gear

### ISSUE THREAD

**Issue by Betaskill** [seriallos/raidbots-issues#183]
**Is your feature request related to a problem? Please describe.**
No it isnt.

**Describe the solution you'd like**

With the possibility to buy a socket for your current items for 25k Corrupted Mementos it would be nice if you can simulate a socket on your items. I think this would be a nice improvement so that ppl can take a look in combination with their corruption which setup would bring the most out of the socket.

**Describe alternatives you've considered**
The only one that comes up in my mind is the possibility to write the text ingame in /simc from wowhead for each item and this is simply just meh.

**Additional context**
None

Hope this would be possible

Regards

**Comment by seriallos** [comment]
Closing due to age. This is not currently on the roadmap.
