### ISSUE TITLE
Manifesto of Madness being used after Focusing Iris instead of before.

### ISSUE THREAD

**Issue by ropedope** [seriallos/raidbots-issues#186]
**Describe the bug**
Manifesto of Madness being used after Focusing Iris instead of before, making the crit buff basically useless and reporting it's worse than a single target trinket in a dungeon simulation (surprising this hasn't been fixed yet).

**To Reproduce**
1. Equip Manifesto of Madness + Focusing Iris and run dungeon sim (shadow priest)
2. Witness the sim using the trinket after popping beam on pull and never holding Manifesto for a few seconds to sync them back up

**Expected behavior**
The expected behavior is that both the trinket and focusing iris have the same cd.. they should be used in the correct order. Also, the sim should be holding both for a few seconds if void form is about to drop to get 100% crit for the beam.

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/5YSwUo6gDp664ZDZ2XnfDb

**Comment by ropedope** [comment]
hi?

**Comment by seriallos** [comment]
I've relayed this to SimC devs.

Rotation specific issues are generally best reported directly to the simc project (https://github.com/simulationcraft/simc/issues). Can also check in the SimcMinMax Discord or your class discord to find one of the SimC devs who can take a closer look.

**Comment by lgkern** [comment]
Hello snarky person,

A small change was added to sync Manifesto with FAB (https://github.com/simulationcraft/simc/commit/cdf7bcb5c1b59059897e8ff4472635aa4763610f). Note, however, that the APL doesn't fully support FAB to its full extent, as the complete optimization takes a lot more effort to write than it is worth pursuing, as in practice you need to minmax first the number of targets, then your CoI stacks, all while maximizing the number of uses. All-in-all leads to basically using it on cooldown in dungeons.

Also, remember that DungeonSlice shouldn't be used as a DPS measure, but as a way to get somewhat reliable stat weights for M+, which isn't affected by the missing optimizations from FAB.
