### ISSUE TITLE
Frost mage icicles completely wrong

### ISSUE THREAD

**Issue by viocristi** [seriallos/raidbots-issues#187]
My sim shows icicles at 2.7%, where it's usually the first or second ability. This can't be, it's automatic from the rotation dependent on the mastery, it's not a good/bad player ability/skill/button
https://www.raidbots.com/simbot/report/99mUWBZYbzgGbUvHXZdy1s

example of what I mean, take this log for instance: https://www.warcraftlogs.com/reports/8f7kPZBA3tbaKXmY#fight=7&type=damage-done
not 100% the same gear, as I was just using 1x rank 2 infinite stars and in the sim there are 2x rank 2 infinite stars, but the icicle damage is not really dependent on that

**Comment by seriallos** [comment]
SimC tracks Icicles differently than WCL or an in-game DPS meter. You can open up details for spells and see there is more Icicles damage from Frostbolt and Flurry. In that Quick Sim, the actual total is more like 27.8%

![image](https://user-images.githubusercontent.com/1010294/78169128-cbbc5f80-7405-11ea-8b3f-53f3f994735e.png)

**Comment by viocristi** [comment]
thank you for the comment, didn't see that
