### ISSUE TITLE
VDH sim bug

### ISSUE THREAD

**Issue by realchromie** [seriallos/raidbots-issues#189]
**Describe the bug**
Vengeance DH skill 'Soul Cleave' is used by sim bot in the rotation constantly, but the damage does not count for the resulting damage meter, or does not count correctly. 
It is shown in the full HTML report though, but all skill percentages are different there. 
(At first glance it seems like Soul Cleave damage portions count as damage from other sources in the Raidbots damage breakdown, but is measured correctly in the full report, since other sources have lower % there)

**To Reproduce**
1. Go to any sim type (considering the damage is the same I assume it happens everywhere), but is clearly shown in Quick Sim damage breakdown.

**Expected behavior**
Skill is used and its damage should be correctly reflected in Raidbots default overall sim and damage breakdown page. 

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here
https://www.raidbots.com/simbot/report/afQHp1oMHCWV9ensUUbvzK
**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc) EU
* Realm / Server Gordunni
* Character Name Хармасана

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**
![Безымя++нный](https://user-images.githubusercontent.com/63398001/78883467-3868d700-7a62-11ea-9318-3074cd066f83.png)
![Безымя+нный](https://user-images.githubusercontent.com/63398001/78883472-399a0400-7a62-11ea-9a12-0981858b301e.png)
![Безымя+++нный](https://user-images.githubusercontent.com/63398001/78884734-18d2ae00-7a64-11ea-8b80-c9e64738aa7c.png)

**Additional context**

**Comment by seriallos** [comment]
Looks like a small stat reporting bug in SimC. The wonderful DH SimC dev Kojiyama just fixed it:

https://github.com/simulationcraft/simc/commit/bab5b3bfcd787b6c94276b69498de9fd9b52de77

This will be fixed in the Raidbots Nightly SimC Version tonight and will hit Weekly next week.
