### ISSUE TITLE
Top Gear requires at least two combinations. Make sure to select some additional items, enhancements, or talents

### ISSUE THREAD

**Issue by Berndinox** [seriallos/raidbots-issues#190]
"Incomplete Character: Top Gear requires all items/slots filled. Check for specific errors on this screen. Also check for a 1-hand main hand without an offhand."
"Top Gear requires at least two combinations. Make sure to select some additional items, enhancements, or talents"

That error is not really specific...
I copy paste my character settings with the ingame addon

**Comment by seriallos** [comment]
Please provide more details so I can test this.

* Your /simc input
* Which items you are selecting on Top Gear

**Comment by seramir88** [comment]
i am also having this issue trying to sim out an azerite piece and nothing else... can dm info

**Comment by seriallos** [comment]
@seramir88 I'm not seeing any problems simming your Azerite gear - selecting some additional azerite traits is generating multiple combinations:

![image](https://user-images.githubusercontent.com/1010294/79490881-699d5600-7fd2-11ea-9156-b2cfcbcce755.png)

What items/powers are you selecting and what options do you have selected?

**Comment by seramir88** [comment]
![myissue](https://user-images.githubusercontent.com/63809109/79502830-0963df80-7fe5-11ea-846a-b98b3ada07ed.jpg)

**Comment by seriallos** [comment]
@seramir88 Do you have "Require 25 Corruption for heart of Darkness" checked? Only way I see your issue is when I check that box but that is intended behavior (your gear has 0 net corruption given the resist from your cloak and breath of the dying essence which is less than the 25 minimum)

**Comment by seramir88** [comment]
ok i see that let me sim it out... now i know if it doesnt work again
