### ISSUE TITLE
Problem with the iterations

### ISSUE THREAD

**Issue by Ganjatzen** [seriallos/raidbots-issues#192]
Hello ! 

I've got a problem with the iterations, my account is currently a heirloom subscription but i can't make a sim with more than 2M iterations.

![Heirloom](https://user-images.githubusercontent.com/64751291/80924367-c5b0fa00-8d88-11ea-8579-820c36544c65.PNG)

![Iterations](https://user-images.githubusercontent.com/64751291/80924371-cb0e4480-8d88-11ea-9615-cf178d000c48.PNG)

How can i fixe this ?

Thanks

**Comment by seriallos** [comment]
Click the "Switch to Smart Sim" button - this will change the mode and allow sims larger than 2m iterations.

**Comment by Ganjatzen** [comment]
Ok perfect, thanks a lot !
