### ISSUE TITLE
Iterations not increasing with gem selection

### ISSUE THREAD

**Issue by DJZike** [seriallos/raidbots-issues#193]
**Describe the bug**
When i choose multiple gems the iterations dont increase.

**To Reproduce**
1. Go to 'Top Gear'
2. Click on 'Gems'
3. Scroll down to 'Bottom'

**Expected behavior**
I expect Iterations to increase when i select all gems

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/xz1HnJoqMQnYMKcdL6oDyF

****

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**
Only thing I have done recently is clear caches.  Same issue repeated in firefox and chrome.

**Comment by seriallos** [comment]
By default, Top Gear only fills empty sockets. If you want to try replacing gems, check the "Replace Existing Gems/Enchants" checkbox.
