### ISSUE TITLE
Top Gear telling me my main hander is not equipped and I am not an active character.

### ISSUE THREAD

**Issue by Finneas98** [seriallos/raidbots-issues#194]
SimulationCraft 830-02 for World of Warcraft 8.3.0 Live (wow build 33051, git build HEAD 28d8fa7442)
Simulating... ( iterations=100000, threads=32, target_error=0.050, max_time=360, vary_combat_length=0.20, optimal_raid=1, fight_style=DungeonSlice )
Player Jenwx has no weapon equipped at the Main-Hand slot.
Error: No active players in sim!

rogue="Jenwx"
race="blood_elf"
level="120"
spec="outlaw"
role="attack"
azerite_essences="23:3/300573/27:3/300575/300576/22:3/300577/312927/35:2/312928"
name="Jenwx"

# Simulation Configs
iterations="5000"
fight_style="DungeonSlice"
desired_targets="1"
max_time="360"
calculate_scale_factors="0"
scale_only="strength,intellect,agility,crit,mastery,vers,haste,weapon_dps,weapon_offhand_dps"
override.bloodlust="1"
override.arcane_intellect="1"
override.power_word_fortitude="1"
override.battle_shout="1"
override.mystic_touch="1"
override.chaos_brand="1"
override.bleeding="1"
bfa.zuldazar="0"
bfa.nazjatar="0"
bfa.worldvein_allies="0"
bfa.loyal_to_the_end_allies="0"
bfa.covenant_chance="1"
bfa.undulating_tides_lockout_timer="5"
bfa.undulating_tides_lockout_chance="0"
bfa.nyalotha="0"
bfa.void_ritual_increased_chance_active="0"
bfa.symbiotic_presence_interval="22"
report_details="0"
single_actor_batch="1"
optimize_expressions="1"

SIMULATION FAILED
Unknown reason! Seri will look into it

Happening over and over again, Im even simming every main hander in my inventory in both main and off hand slots.

**Comment by seriallos** [comment]
Can you post your full /simc input and/or a link to the failed report?

**Comment by seriallos** [comment]
Actually, I believe this is fixed. Reload the site and you should get some fixes I just deployed

**Comment by Finneas98** [comment]
Looks like its fixed, thanks for the reply and Im impressed with the swift
response and fix great work!
