### ISSUE TITLE
Raidbots API Error: avgWait missing from job status response

### ISSUE THREAD

**Issue by chutermcgavin** [seriallos/raidbots-issues#197]
When attempting to run the simbot from discord, a few seconds into the sim it stops with the above eror

**To Reproduce**
1. Go to discord
2. Attempt to run simbot (!sim us/cenarius/chutermcgavn)
3. Sim starts to run for a few seconds

Provides a link to go to the sim but not some of the other items it usually provides.

Results:
![image](https://user-images.githubusercontent.com/65831096/82740219-b2a0a280-9d14-11ea-8c57-aebb728dc64a.png)

Expected:
![image](https://user-images.githubusercontent.com/65831096/82740226-c946f980-9d14-11ea-8b49-f6d7e910e40c.png)

**Comment by seriallos** [comment]
I'm deploying a fix right now, should be resolved in 15 minutes or so.
