### ISSUE TITLE
Visual bug: Progress box does not properly escales the content's page 

### ISSUE THREAD

**Issue by melinerunen** [seriallos/raidbots-issues#198]
When running the sim the progress box is resizable and if you resize it, the rest of the page doesn't move properly 

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/1240420/83185589-9a0ffe00-a101-11ea-90d5-4f60c67e5b6e.png">

Tested with Firefox 77 under mac OS 10.15.4  Catalina

**Comment by seriallos** [comment]
Yeah, known issue. A fix would require some significant rewriting of the browser code which isn't on the table right now.

**Comment by melinerunen** [comment]
Is nice to have it as a backlog :)
