### ISSUE TITLE
"Unable to generate valid combinations. Incomplete Character: Top Gear requires all items/slots filled. Check for specific errors on this screen. Also check for a 1-hand main hand without an offhand."

### ISSUE THREAD

**Issue by Silverwing999** [seriallos/raidbots-issues#199]
I can't seem to sim my character and when I try I get the above message. As well as "Top Gear requires at least two combinations. Make sure to select some additional items, enhancements, or talents" when I select Find Top Gear. This is not true as my character has equipment in every single slot and I have also tried selecting multiple items in different slots to sim, as well as tried to only change out my helmet for example. Nothing works.
My max corruption is set to 100. 
Require 25 Corruption + copy and Purify All Corrupted Items are **unticked**.
I have also tried to change some pieces manually and got my corruption to 0 before simming, which makes no difference and I still get the above errors.

If anyone has a clue as to why I can't sim any pieces on my character the advice would be much appreciated.

Region: EU
Realm: Draenor
Character name: Lineglaive

Character/simc input below:
Pastebin: https://pastebin.com/wVnaNmsb

# Lineglaive - Havoc - 2020-05-28 23:15 - EU/Draenor
# SimC Addon 1.12.5
# Requires SimulationCraft 820-01 or newer

demonhunter="Lineglaive"
level=120
race=blood_elf
region=eu
server=draenor
role=attack

talents=2312231
spec=havoc

azerite_essences=35:1/300573/12:1/300575/300576
# azerite_essences_available=12:1/33:1/34:1/35:1

head=,id=174132,bonus_id=4825/1472/4786/6502/4775,context=4,azerite_powers=159/582/20/83/13
neck=,id=158075,bonus_id=4932/4933/6316/1600,context=11,azerite_level=65
shoulder=,id=157979,bonus_id=1607/4785/6259/4775,context=25,azerite_powers=220/85/13
back=,id=169223,bonus_id=6273/1472,context=11
chest=,id=173843,bonus_id=1487/4786/6501/4775,context=9,azerite_powers=159/582/31/15/13
wrist=,id=174138,bonus_id=4825/6578/6579/6474/6455/6513/1472/4786,context=4
hands=,id=170350,bonus_id=1682,context=13
waist=,id=158044,bonus_id=4803/4802/6516/6515/1612/4785,context=27
legs=,id=174247,bonus_id=4822/6578/6579/6437/6455/6515/1487/4786,context=3
feet=,id=173439,bonus_id=6412/6515/6516/1487/4786,context=9
finger1=,id=174268,bonus_id=4822/6516/6515/1487/4786,context=3
finger2=,id=158152,bonus_id=4803/41/6516/6515/1607/4785,context=26
trinket1=,id=165667,bonus_id=4803/6515/1602/4785,context=25
trinket2=,id=169321,context=13
main_hand=,id=155271,bonus_id=41/4803/1607/4785,context=26
off_hand=,id=160969,bonus_id=4803/1602/4785,context=25

### Gear from Bags
#
# Honorbound Outrider's Headpiece (390)
# head=,id=170532,bonus_id=1577/4786/5414/4775,context=11,azerite_powers=159/352/21/466/13
#
# Fairweather Helm (420)
# head=,id=158041,bonus_id=1607/4785/6258/4775,context=25,azerite_powers=159/83/13
#
# Gonk Outrunner Shoulderguards (375)
# shoulder=,id=157915,bonus_id=1562/4785/6256/4775,context=26,azerite_powers=353/15/13
#
# Wristwraps of the Insatiable Maw (440)
# wrist=,id=174954,bonus_id=6578/6579/4803/6515/6540,context=28
#
# Bindings of the Insatiable Maw (370)
# wrist=,id=173480,bonus_id=6412/4803/40/6515/6578/6579/6538/1427/4785,context=28
#
# Seafarer Grips (410)
# hands=,id=157976,bonus_id=4803/6578/6579/6560/6513/1602/4785,context=25
#
# Fairweather Belt (365)
# waist=,id=158044,bonus_id=4803/6578/6579/6564/6513/1557/4785,context=27
#
# Seafarer Belt (410)
# waist=,id=157980,bonus_id=4803/6516/6515/1602/4785,context=25
#
# Footguards of the Insatiable Maw (420)
# feet=,id=173516,bonus_id=6412/4803/6515/6578/6579/6562/1477/4786,context=30
#
# Uncanny Combatant's Cutlass of the Quickblade (400)
# main_hand=,id=170302,bonus_id=1676/5804,context=13
#
# Uncanny Combatant's Cutlass of the Quickblade (400)
# off_hand=,id=170302,bonus_id=1676/5804,context=13
```

**Comment by Silverwing999** [comment]
Well seems half my simc info became bold somehow.

**Comment by melinerunen** [comment]
Write it inside a code block or do a pastebin

**Comment by Silverwing999** [comment]
Made a pastebin. https://pastebin.com/wVnaNmsb

**Comment by seriallos** [comment]
You don't have enough essences available to fill your neck slots.

Until you learn more essences, you'll have to manually adjust the azerite level of your neck to be low.

Change the `azerite_level=` part of the `neck=` line to a lower level

**Comment by Silverwing999** [comment]
Ah I see. That makes sense. Thank you for your time.
