### ISSUE TITLE
BOTE Essence problem

### ISSUE THREAD

**Issue by Sylix77** [seriallos/raidbots-issues#200]
**Describe the bug**
My character is using blood of the enemy as a major essence however during sims, it is showing me the minor essence haste buff (blood soaked) on top of it using the major essence in the rotation section.

**To Reproduce**
See Log link below

**Link a sim with the problem (if available)**
If you have a sim report that shows the problem, please provide the URL here
https://www.raidbots.com/simbot/report/ZsiwWWq63B7Ah2EDAuEDe

**Comment by seriallos** [comment]
When using an essence in the major slot, you get both the major and the minor abilities of the essence. In-game, the tooltip for the major power will show both the major and minor effects.

https://worldofwarcraft.com/en-us/news/22956187/rise-of-azshara-preview-heart-of-azeroth-updates

> Placing an Essence in the Major slot grants you that Essence’s Major active ability, which is added to your Spellbook. You’ll also gain the benefit of any Minor passive abilities from the Essence.
