### ISSUE TITLE
Destruction lock stat weights need reevaluated.. 

### ISSUE THREAD

**Issue by jsonn97** [seriallos/raidbots-issues#201]
My reason being ---> https://www.raidbots.com/simbot/report/8RmFxtRcatC9VDfZSKuKG5 theres no way versatility should be top. When you look at all top warlocks they run mad expedient and haste..

**Comment by seriallos** [comment]
Personal stat weights are a pretty outdated tool nowadays. I wrote up a blog post about this a while ago that digs into some of the deficiencies of the approach: https://medium.com/raidbots/beware-of-stat-weights-240769a5323e

The destruction channel in the Warlock discord has this macro as well when folks ask about stat weights:

> Personal stat weights are often disingenuous. They don't factor the rating you lose in other stats swapping between different items. It might tell you haste is your best stat for the next 1000 rating, but it doesn't account for losing the 1000 mastery you would need to move into haste.

> The best thing to do is just sim potential upgrades on https://www.raidbots.com/simbot/topgear and have a good idea of which stats are usually best.
