### ISSUE TITLE
IceCap FrostDk Rotation (BotE)

### ISSUE THREAD

**Issue by Xavantor** [seriallos/raidbots-issues#202]
0:15:942
Chains of Ice
Fluffy Pillow
0:16:695
Pillar of Frost
0:17:449
Blood of the Enemy
Fluffy Pillow

This is what actually is Simed.
But the more DPS rotation is planed other... since Icecap redurces the cooldown so much that we can have a full effect on Icy citadel combined with Pillar of Frost additionally we wanna use BotE BEFORE Chains of Ice since its the hardest hitting ability on our Kit.

Exampel:
Pillar of Frost
"normal rotation"
Pillar ends -> Icy Citadell is uo
Instand new Pillar
"normal rotation untill the last 7-8 sek of both buffs"
Blood of the Enemy 
maybe (procc) one more Rune to spend
Then a 400k Monstertruck hitting Chains of Ice with critical damage buff, max % Strength from PoF
and the additional Strength from Icy Citadell

Sorry for some writing issues, my english is not the yellow from the egg (a german guy will understand this joke).. and have a nice day =)

**Comment by seriallos** [comment]
Rotation-specific issues/enhancements should be reported to the SimC project directly: https://github.com/simulationcraft/simc

This source is mostly for Raidbots-specific UI bugs and issues, it's not for the actual simulation software.
