### ISSUE TITLE
[Request] Droptimizer Improvements

### ISSUE THREAD

**Issue by spaceghost1589** [seriallos/raidbots-issues#204]
With the ability to add sockets and corruption of choice, it would be nice to see an option on the droptimizer to match sockets and corruption of equipped pieces to possible drops. Or have droptimizer simply drop sockets/gems and corruption from all gear (except guaranteed corruptions) being simmed.

This should give a better representation of the difference in gear based on raw gear stats.

**Comment by buola** [comment]
That would be a great feature.
Dropping corruption from all would not be a good option since best stats are heavily dependent on corruptions such as Masterful.
