### ISSUE TITLE
[Request] 475 Weekly Droptimizer

### ISSUE THREAD

**Issue by garnetshepherd** [seriallos/raidbots-issues#207]
**Is your feature request related to a problem? Please describe.**
I can't easily SIM for top Weekly 475 chest gear. I want to know what the best case would be from a lucky weekly.

**Describe the solution you'd like**
In the M+ Droptimizer tab, add an option for 475 Weekly.

**Describe alternatives you've considered**
Manually adding all these pieces to Top Gear with ilvl override :(

**Comment by seriallos** [comment]
Weekly Chest item levels are now available in Droptimizer
