### ISSUE TITLE
Boots of Hallucinatory Reality Socket Bug

### ISSUE THREAD

**Issue by Buckwyld** [seriallos/raidbots-issues#210]
When you attempt to socket a gem into a Boots of Hallucinatory Reality, Raidbots does not place a gem into the socket during the sim and does not report a gem on the final report. This is a repeatable sim that occurs with the boot.

feet=,id=174173,gem_id=153707,bonus_id=4823/1808/6516/6515/1502/4786,context=5
https://www.wowhead.com/item=174173/boots-of-hallucinatory-reality&bonus=4822:1487

**Comment by seriallos** [comment]
Can you a link a sim where the gem isn't showing up?

If you're using Top Gear and you want to try out different gems, make sure the "Replace Existing Gems/Enchants" checkbox is checked.
