### ISSUE TITLE
Prot Warr - "could not find spell data for action ignore_pain"

### ISSUE THREAD

**Issue by kimse-** [seriallos/raidbots-issues#214]
I'm trying to sim prot warrior in pre-patch and when I run the sim I get this the below error message.
Raw Input: https://www.raidbots.com/reports/eHcF6mH81fwymuuFSbczPG/input.txt

SimulationCraft 901-01 for World of Warcraft 9.0.2.36165 shadowlands-BETA (hotfix 2020-10-13/36165, git build HEAD ecaa556805)
Simulating... ( iterations=100000, threads=32, target_error=1.000, max_time=240, vary_combat_length=0.20, optimal_raid=1, fight_style=Patchwerk )
Player Drunkenclap could not find spell data for action ignore_pain
Simulation has been canceled after 1 iterations! (thread=0)                     
Player Drunkenclap could not find spell data for action ignore_pain
Player Drunkenclap could not find spell data for action ignore_pain
Generating reports...
JSON report version 2.0.0 took 0.00046948000000000004seconds.

**Comment by seriallos** [comment]
Protection warriors are not currently supported in SimC. Yesterday I disabled sims for prot warriors on Raidbots. I will re-enable them if/when prot warrior support comes back.
