### ISSUE TITLE
Rogue :Master Assassin talent and Use of Vanish on the Rotation 

### ISSUE THREAD

**Issue by Coitos** [seriallos/raidbots-issues#217]
**Describe the bug**
When we sim on the rogue has Assassination , and The " Master Assassin" talent is spec, the sim don´t use the "Vanish" spell on the rotation to proc the buf.

**To Reproduce**

1.Quick sim a Assassination Rogue with Master Assassin talent and  check the sample ability log.

**Expected behavior**

The sim should when the talent is spec, use " Vanish"on the rotation to proc the Buf "Master Assassin", Maybe in the opener along side the Vendeta and every time the vendeta is up !

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/pX1wGNo3s9YtptSZMKdfbf

**Comment by seriallos** [comment]
This is an issue for SimC itself, not Raidbots.
