### ISSUE TITLE
Seed of corruption not used with Sow of Seeds in a good way

### ISSUE THREAD

**Issue by FrozenBrainFarts** [seriallos/raidbots-issues#218]
**Describe the bug**
When the talent Sow of Seeds is selected then Seed of Corruption should be used as the main shard spender if more than X targets

**To Reproduce**
1. Run quick sim
2. Click on Full HTML Report
3. Scroll down to Profile
4. See 'actions+=/malefic_rapture,if=talent.sow_the_seeds.enabled'

**Expected behavior**
'actions+=/seed_of_corruption,if=talent.sow_the_seeds.enabled

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/xkz8eXx9NisWWwCqyDTp32

Input:
warlock="Brainback"
source=default
spec=affliction
level=50
race=gnome
role=spell
position=back
professions=enchanting=1/
talents=3121123
azerite_essences=23:3/300573/27:3/300575/300576/12:3/300577/312927/37:3/312928

# Default consumables
potion=unbridled_fury
flask=greater_flask_of_endless_fathoms
food=famine_evaluator_and_snack_table
augmentation=battle_scarred

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/summon_pet
actions.precombat+=/grimoire_of_sacrifice,if=talent.grimoire_of_sacrifice.enabled
actions.precombat+=/snapshot_stats
actions.precombat+=/use_item,name=azsharas_font_of_power
actions.precombat+=/seed_of_corruption,if=spell_targets.seed_of_corruption_aoe>=3&!equipped.169314
actions.precombat+=/haunt
actions.precombat+=/shadow_bolt,if=!talent.haunt.enabled&spell_targets.seed_of_corruption_aoe<3&!equipped.169314

# Executed every time the actor is available.
actions=phantom_singularity
actions+=/vile_taint,if=soul_shard>1
actions+=/siphon_life,if=refreshable
actions+=/agony,if=refreshable
actions+=/unstable_affliction,if=refreshable
actions+=/unstable_affliction,if=azerite.cascading_calamity.enabled&buff.cascading_calamity.remains<3
actions+=/corruption,if=refreshable
actions+=/haunt
actions+=/call_action_list,name=darkglare_prep,if=cooldown.summon_darkglare.remains<2&(dot.phantom_singularity.remains>2|!talent.phantom_singularity.enabled)
actions+=/dark_soul,if=cooldown.summon_darkglare.remains>time_to_die
actions+=/call_action_list,name=cooldowns
actions+=/use_items
actions+=/malefic_rapture,if=dot.vile_taint.ticking
actions+=/malefic_rapture,if=talent.phantom_singularity.enabled&(dot.phantom_singularity.ticking||cooldown.phantom_singularity.remains>12||soul_shard>3)
actions+=/malefic_rapture,if=talent.sow_the_seeds.enabled
actions+=/drain_life,if=buff.inevitable_demise.stack>30
actions+=/drain_life,if=buff.inevitable_demise_az.stack>30
actions+=/drain_soul
actions+=/shadow_bolt

actions.cooldowns=worldvein_resonance
actions.cooldowns+=/memory_of_lucid_dreams
actions.cooldowns+=/blood_of_the_enemy
actions.cooldowns+=/guardian_of_azeroth
actions.cooldowns+=/ripple_in_space
actions.cooldowns+=/focused_azerite_beam
actions.cooldowns+=/purifying_blast
actions.cooldowns+=/reaping_flames
actions.cooldowns+=/concentrated_flame
actions.cooldowns+=/the_unbound_force,if=buff.reckless_force.remains

actions.darkglare_prep=vile_taint
actions.darkglare_prep+=/dark_soul
actions.darkglare_prep+=/potion
actions.darkglare_prep+=/fireblood
actions.darkglare_prep+=/blood_fury
actions.darkglare_prep+=/berserking
actions.darkglare_prep+=/summon_darkglare

head=visage_of_nightmarish_machinations,id=174118,bonus_id=4823/1502/4786/6508/4775,azerite_powers=123/582/21/83/13
neck=heart_of_azeroth,id=158075,bonus_id=4932/4933/6316/1558,azerite_level=90
shoulders=spaulders_of_miasmic_mycelia,id=174117,bonus_id=4823/1502/4786/6509/4775,azerite_powers=123/582/30/44/13
back=ashjrakamas_shroud_of_resolve,id=169223,bonus_id=6599/1472
chest=blooddrenched_robes,id=159241,bonus_id=5448/1543/4786/6510/4775,azerite_powers=123/425/21/44/13
wrists=cuffs_of_grim_conjuration,id=174129,bonus_id=4823/6516/6515/1502/4786
hands=mine_rats_handwarmers,id=159231,bonus_id=6534/6578/6515/1538/4786/6516
waist=excavators_safety_belt,id=159226,bonus_id=6536/4802/6516/6513/1533/4786,gem_id=168640
legs=downlined_breeches,id=159234,bonus_id=6536/6578/6513/1543/4786/6476/6470
feet=hyperthread_boots,id=168964,bonus_id=6536/6515/1524/4786
finger1=ring_of_cosmic_potential,id=174533,bonus_id=4823/6513/1502/4786/6476/6470,enchant_id=6109
finger2=seal_of_questionable_loyalties,id=158314,bonus_id=6536/4802/6578/6579/6557/6513/1533/4786,gem_id=168640,enchant_id=6110
trinket1=vitacharged_titanshard,id=174500,bonus_id=4823/6513/1502/4786
trinket2=manifesto_of_madness,id=174103,bonus_id=4823/1808/6515/1502/4786,gem_id=168638
main_hand=shglayos_astral_malignity,id=174108,bonus_id=4823/6553/6578/6579/1502/4786/6513,enchant_id=5963
off_hand=aureus_vessel,id=158322,bonus_id=6536/6578/6515/1543/4786/6516

# Gear Summary
# gear_ilvl=128.38
# gear_stamina=681
# gear_intellect=513
# gear_crit_rating=180
# gear_haste_rating=236
# gear_mastery_rating=170
# gear_versatility_rating=95
# gear_corruption=105
# gear_corruption_resistance=113
# gear_armor=153
default_pet=imp

Fix?
https://www.raidbots.com/simbot/report/9jpByNkspeoyMqEfYo8sq1
Input:
warlock="Brainback"
source=default
spec=affliction
level=50
race=gnome
role=spell
position=back
professions=enchanting=1/
talents=3121123
azerite_essences=23:3/300573/27:3/300575/300576/12:3/300577/312927/37:3/312928

# Default consumables
potion=unbridled_fury
flask=greater_flask_of_endless_fathoms
food=famine_evaluator_and_snack_table
augmentation=battle_scarred

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/summon_pet
actions.precombat+=/grimoire_of_sacrifice,if=talent.grimoire_of_sacrifice.enabled
actions.precombat+=/snapshot_stats
actions.precombat+=/use_item,name=azsharas_font_of_power
actions.precombat+=/seed_of_corruption,if=spell_targets.seed_of_corruption_aoe>=3&!equipped.169314
actions.precombat+=/haunt
actions.precombat+=/shadow_bolt,if=!talent.haunt.enabled&spell_targets.seed_of_corruption_aoe<3&!equipped.169314

# Executed every time the actor is available.
actions=phantom_singularity
actions+=/vile_taint,if=soul_shard>1
actions+=/siphon_life,if=refreshable
actions+=/agony,if=refreshable
actions+=/unstable_affliction,if=refreshable
actions+=/unstable_affliction,if=azerite.cascading_calamity.enabled&buff.cascading_calamity.remains<3
actions+=/corruption,if=refreshable
actions+=/haunt
actions+=/call_action_list,name=darkglare_prep,if=cooldown.summon_darkglare.remains<2&(dot.phantom_singularity.remains>2|!talent.phantom_singularity.enabled)
actions+=/dark_soul,if=cooldown.summon_darkglare.remains>time_to_die
actions+=/call_action_list,name=cooldowns
actions+=/use_items
actions+=/malefic_rapture,if=dot.vile_taint.ticking
actions+=/malefic_rapture,if=talent.phantom_singularity.enabled&(dot.phantom_singularity.ticking||cooldown.phantom_singularity.remains>12||soul_shard>3)
actions+=/seed_of_corruption,if=talent.sow_the_seeds.enabled
actions+=/drain_life,if=buff.inevitable_demise.stack>30
actions+=/drain_life,if=buff.inevitable_demise_az.stack>30
actions+=/drain_soul
actions+=/shadow_bolt

actions.cooldowns=worldvein_resonance
actions.cooldowns+=/memory_of_lucid_dreams
actions.cooldowns+=/blood_of_the_enemy
actions.cooldowns+=/guardian_of_azeroth
actions.cooldowns+=/ripple_in_space
actions.cooldowns+=/focused_azerite_beam
actions.cooldowns+=/purifying_blast
actions.cooldowns+=/reaping_flames
actions.cooldowns+=/concentrated_flame
actions.cooldowns+=/the_unbound_force,if=buff.reckless_force.remains

actions.darkglare_prep=vile_taint
actions.darkglare_prep+=/dark_soul
actions.darkglare_prep+=/potion
actions.darkglare_prep+=/fireblood
actions.darkglare_prep+=/blood_fury
actions.darkglare_prep+=/berserking
actions.darkglare_prep+=/summon_darkglare

head=visage_of_nightmarish_machinations,id=174118,bonus_id=4823/1502/4786/6508/4775,azerite_powers=123/582/21/83/13
neck=heart_of_azeroth,id=158075,bonus_id=4932/4933/6316/1558,azerite_level=90
shoulders=spaulders_of_miasmic_mycelia,id=174117,bonus_id=4823/1502/4786/6509/4775,azerite_powers=123/582/30/44/13
back=ashjrakamas_shroud_of_resolve,id=169223,bonus_id=6599/1472
chest=blooddrenched_robes,id=159241,bonus_id=5448/1543/4786/6510/4775,azerite_powers=123/425/21/44/13
wrists=cuffs_of_grim_conjuration,id=174129,bonus_id=4823/6516/6515/1502/4786
hands=mine_rats_handwarmers,id=159231,bonus_id=6534/6578/6515/1538/4786/6516
waist=excavators_safety_belt,id=159226,bonus_id=6536/4802/6516/6513/1533/4786,gem_id=168640
legs=downlined_breeches,id=159234,bonus_id=6536/6578/6513/1543/4786/6476/6470
feet=hyperthread_boots,id=168964,bonus_id=6536/6515/1524/4786
finger1=ring_of_cosmic_potential,id=174533,bonus_id=4823/6513/1502/4786/6476/6470,enchant_id=6109
finger2=seal_of_questionable_loyalties,id=158314,bonus_id=6536/4802/6578/6579/6557/6513/1533/4786,gem_id=168640,enchant_id=6110
trinket1=vitacharged_titanshard,id=174500,bonus_id=4823/6513/1502/4786
trinket2=manifesto_of_madness,id=174103,bonus_id=4823/1808/6515/1502/4786,gem_id=168638
main_hand=shglayos_astral_malignity,id=174108,bonus_id=4823/6553/6578/6579/1502/4786/6513,enchant_id=5963
off_hand=aureus_vessel,id=158322,bonus_id=6536/6578/6515/1543/4786/6516

# Gear Summary
# gear_ilvl=128.38
# gear_stamina=681
# gear_intellect=513
# gear_crit_rating=180
# gear_haste_rating=236
# gear_mastery_rating=170
# gear_versatility_rating=95
# gear_corruption=105
# gear_corruption_resistance=113
# gear_armor=153
default_pet=imp

**Comment by seriallos** [comment]
This is an issue for SimC, not Raidbots. I also believe this has been addressed.
