### ISSUE TITLE
Top Gear changing talents

### ISSUE THREAD

**Issue by vaeevictiss** [seriallos/raidbots-issues#22]
So for example, when i pull my info over it shows my talents as 3111213 but when the sim is complete, at the top of the screen, under my name it has my talents set to 2211211. Cant seem to get it to run the way it should.

**Comment by seriallos** [comment]
Can you provide links to reports that are having issues?

**Comment by vaeevictiss** [comment]
https://www.raidbots.com/simbot/report/dbCRiQWybLJeW93hK7Sh1i

is the latest one.


This shows the correct talent images matching the talents "number string"



​this is from the results page showing different talents, this string would
be 2211211



​this is at the bottom of the results page and it still shows the correct
spec string.


thanks for any help​

**Comment by seriallos** [comment]
I see the issue, you're seeing the talents you chose to override from an Armory import on another screen. I should be able to fix it in the next few days, probably.

**Comment by seriallos** [comment]
Also, it simulated correctly using the talents shown on the Top Gear page, it's just showing the wrong ones on the report.

**Comment by vaeevictiss** [comment]
Ahh ok, is there a way I could fix that on my end?

**Comment by seriallos** [comment]
Nope. Again, it's just a display error on the report. Top Gear used the talents from your /simc input and did not use the talent override from the Armory import. So what you intended to simulate was properly run.

**Comment by vaeevictiss** [comment]
yea i sent that last one b4 i saw your second one come in. Thanks for
clearing it up tho!

**Comment by seriallos** [comment]
Fix deployed, that report is now showing the correct talents.
