### ISSUE TITLE
Unbound Changeling Is Wrong

### ISSUE THREAD

**Issue by lotsoftoons** [seriallos/raidbots-issues#223]
The Unbound Changeling trinket is wrong in RaidBots' database. It shows it with just intellect without it's haste proc. This causes it to sim as the worst caster trinket.

**Comment by seriallos** [comment]
I'm looking into improving support for this item.

As a workaround until then, I believe you can use the "Custom APL and SimC Options" to set which version of the trinket to use - this will only be able to run one version of the item but might help out a little bit for right now.

`shadowlands.unbound_changeling_stat_type=all` will use the version that provides all the stats
`shadowlands.unbound_changeling_stat_type=crit` will use the version that provides crit
`shadowlands.unbound_changeling_stat_type=haste` will use the version that provides haste
`shadowlands.unbound_changeling_stat_type=mastery` will use the version that provides mastery

**Comment by seriallos** [comment]
This item now has better default handling (it will use the all stats proc if there's no bonus ID and no overrides specified). The "Custom APL and SimC Options" are still available to test variations of the item.
