### ISSUE TITLE
Raidbots Lowercase 'r' Character Omission in Boss Names

### ISSUE THREAD

**Issue by APills** [seriallos/raidbots-issues#224]
**Describe the bug**
Any boss names with the lowercase letter 'r' are shown incorrectly with the 'r' removed. 
Some items do not show a boss name when hovered over.

**To Reproduce**
1. Hover over any item that shows a boss' name
2. If the gear is from any boss with an 'r' in their name (Dealer Xy'exa, Hakkar the Soulflayer, (Nalthor the Rimebinder only has his lowercase 'r's removed making his name appear as "Naltho the Rimebinde")) any 'r's are missing
3. See error

**Expected behavior**
Bosses such as Margrave Stradama have 'r' characters in their names

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/56s8fUjf8h1txtWKQR9Shj

**Character or /simc input**

For "Load from Armory":

* US
* Illidan
* Brylonk

For "Load from SimC Addon":

```
# Brylonk - Windwalker - 2020-12-02 23:21 - US/Illidan
# SimC Addon 9.0.2-05
# Requires SimulationCraft 901-01 or newer

monk="Brylonk"
level=60
race=zandalari_troll
zandalari_loa=paku
region=us
server=illidan
role=attack
professions=mining=109/engineering=97
talents=2322232
spec=windwalker

# azerite_essences=0:0/300573/0:0/300575/300576/0:0/300577/312927/0:0
# azerite_essences_available=12:1/22:1/33:1/35:1

covenant=venthyr
soulbind=nadjia_the_mistblade:8,331586/19:3/331576
# soulbind=theotar_the_mad_duke:9,
# conduits_available=19:3/22:3/24:4/28:2/31:3/44:2/46:3/54:2/57:3/62:2/37:2/41:4/42:3/15:1/25:2/33:1/47:3/56:4
# renown=6

head=,id=178760,bonus_id=6807/6652/7194/1498/6646
neck=,id=178827,bonus_id=6806/6652/7194/1485/4785
shoulder=,id=178763,bonus_id=6807/6652/1498/6646
back=,id=184758,enchant_id=6208
chest=,id=178835,enchant_id=6216,bonus_id=6807/6652/1498/6646
shirt=,id=16060
tabard=,id=69210
wrist=,id=178702,bonus_id=6807/6652/7194/1498/6646
hands=,id=178832,bonus_id=6807/6652/1498/6646
waist=,id=178699,gem_id=173129,bonus_id=6806/6652/6935/1485/4785
legs=,id=172318,bonus_id=7071/6716/6650/6647/1487
feet=,id=178731,bonus_id=6807/6652/1498/6646
finger1=,id=178781,bonus_id=6807/6652/6935/1498/6646
finger2=,id=178848,enchant_id=6164,bonus_id=6807/6652/7194/1498/6646
trinket1=,id=173087
trinket2=,id=180116,bonus_id=6807/6652/1498/6646
main_hand=,id=178754,bonus_id=6807/6652/1498/6646
off_hand=,id=178754,enchant_id=6229,bonus_id=6806/6652/1485/4785

### Gear from Bags
#
# Flexible Ectoplasmic Specs (151)
# head=,id=172905,bonus_id=6893,drop_level=60
#
# Mist-Piercing Goggles (30)
# head=,id=87213
#
# Cloak of Coordination (29)
# back=,id=65274
#
# Grim-Veiled Cape (190)
# back=,id=173242,bonus_id=6716/1487
#
# Wrap of Unity (20)
# back=,id=63207
#
# Shroud of Cooperation (20)
# back=,id=63353
#
# Rocket Boots Xtreme (32)
# feet=,id=23824,enchant_id=2940
#
# Fleshfused Circle (184)
# finger1=,id=178869,enchant_id=6164,bonus_id=6807/6652/7193/1498/6646
#
# Sinful Aspirant's Medallion (158)
# trinket1=,id=184052,bonus_id=6793/1472/6616
#
# Devos's Cacophonous Poleaxe (184)
# main_hand=,id=180096,bonus_id=6807/1498/6646
#
# Age-Worn Shortblade (1)
# main_hand=,id=174021
#
# The Brokers Angle'r (40)
# main_hand=,id=180136
#
# Age-Worn Shortblade (1)
# off_hand=,id=174021
```

**Screenshots**
https://imgur.com/a/6EJnEbM

**Additional context**
Nalthor the Rimebinder's 'R' character is unaffected, likely due to being handled separately

**Comment by seriallos** [comment]
What the

**Comment by seriallos** [comment]
Pretty sure this is a bug with the Wowhead tooltips so I've forwarded it to them for now. This is definitely one of the strangest bugs I have seen in a long time!

**Comment by APills** [comment]
What's worse is I don't think it was happening yesterday, I pray for the dev that has to find what's causing it and fix this one.

**Comment by seriallos** [comment]
This was a bug on all of wowhead, apparently. Regular expression gone wrong! Should be good now if you force refresh pages as that should ensure you get the fixed tooltips.
