### ISSUE TITLE
BFA gems are simming with old values

### ISSUE THREAD

**Issue by djodars89** [seriallos/raidbots-issues#225]
On the top gear page, the new values shows correctly (+6 / +7 to the main stats) but after simming (maybe even in the calculations?) it shows the old values (+12 / +18).

**Comment by seriallos** [comment]
Wowhead's tooltips are out-of-date. The actual sim is using the nerfed stat amounts. You can verify if you run a Quick Sim that has one of these gems and check the Full HTML Report from SimC to see how much main stat was applied:

![image](https://user-images.githubusercontent.com/1010294/101197678-4aae0b80-3617-11eb-9e08-6e0d839e01ae.png)
