### ISSUE TITLE
Sockets on equipped gear not being seen with TopGear

### ISSUE THREAD

**Issue by zenots** [seriallos/raidbots-issues#226]
It doesn't seem to notice a socket on your equipped item? WITH BOAT (a legendary that gives 50%/100% crit chance to my spells over 5s) it's recommending upgrading a 151 neck HASTE/mastery (bis stats) with socket into a 171 CRIT/vers (dead stat) neck with socket and using mastery gem. It also doesn't recommend doing anything to the socket when I sim the 151 neck alone with +7 int in atm.

**Comment by seriallos** [comment]
Can you link some sims showing the behavior you are seeing (ideally as simple as possible with as few items as possible).

**Comment by zenots** [comment]
https://www.raidbots.com/simbot/report/fc3W5sJE275RW7UHKS9Lw7

**Comment by seriallos** [comment]
By default, Top Gear will not replace gems. You have to enable the "Replace Existing Gems/Enchants" checkbox to test out replacing gems in sockets that you have already filled.

In terms of the 171 simming higher, it seems reasonable to me (without knowing a lot of details about stat interactions for Balance druids). The 13 item level increase results in about 20% more secondary stats overall (104 total on the 158 neck, 125 total on the 171 neck). While haste does generally look best on patchwerk sims for your character, the other stats are still increasing your DPS but at a slightly lower rate (maybe 90% as valuable). So enough of those "worse" stats can be better overall.

**Comment by zenots** [comment]
Crit on balance with BOAT legendary should be extremely low value due to it giving us 100% crit every single damage phase of our rotation so even with 21 more total stats there should be no way a crit primary item should outweigh our 2 best stats at those levels. Fair enough about the replace gems checkbox, didn't know of it.

**Comment by seriallos** [comment]
I'm not a balance expert, but BoAT's uptime looks to be in the range of about 15-20% so it only devalues crit by approximately that much. It's a significant decrease but not complete so there will be a point at which enough crit overcomes other stats.

Your best bet for getting a more detailed analysis will probably be in the Druid class discord.

**Comment by zenots** [comment]
It's actually more than that because most of our damage happens inside that BOAT window and the rest of the time is spent maintaining dots and filler until next eclipse starts to dump again (and our main damaging ability double dips on BOAT benefit to actually get 100% crit)
