### ISSUE TITLE
Furious Gaze buff of havoc demon hunters at least incorrectly labeled as a flat haste buff, instead of a percentage based buff.

### ISSUE THREAD

**Issue by Bathurstc** [seriallos/raidbots-issues#228]
**Describe the bug**

I am unsure if this is an actual bug, or just an error in current text. The demon hunter gain the buff "Furious Gaze" on completion of a full eye beam cast. When looking closely at the buffs active reported in the 'quick sim' for my demon hunter, the buff is reported at a flat haste buff of 164. In live, this buff is in fact 15% haste, scaling off the haste of the character. I am unsure if this is being applied correctly in the sim, or if this is just an out of date piece of text.

**To Reproduce**

Should be easy to reproduce through a quick sim of a havoc demon hunter.

**Expected behavior**

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/nDBT8GqGGg97zHdAHnZWCV

I felt that if this is a bug, it would have a significant effect of a havoc demon hunter sim.

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
Wowhead tooltips are only for display convenience and are not indicative of the actual simulation. SimC has its own database/handling of spell data which is separate from the tooltips. You can often get more details by digging into the Full HTML Report generated by SimC.
