### ISSUE TITLE
Issue when simulating Hateful Chain trinket

### ISSUE THREAD

**Issue by Philboisvert** [seriallos/raidbots-issues#230]
**When using any sim with the trinket Hateful Chain (https://www.wowhead.com/item=184026/hateful-chain?bonus=6805), no procs are shown since the fluffy pillow is always 100% health** 

**To Reproduce**
Just simulating any character with the hateful chain trinket

**Expected behavior**
When simulating causing the trinket to proc with a target that would lose health. 
I'm not sure if it's something that is doable.

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/2PqXbLZNGxHb8qFvZLaknV

**Screenshots**

![image](https://user-images.githubusercontent.com/45600929/102138138-e286d300-3e29-11eb-8f7d-1304dec81a47.png)
![image](https://user-images.githubusercontent.com/45600929/102138227-08ac7300-3e2a-11eb-82de-5438b995aadb.png)

**Additional context**
_**Not sure if a bug or intended or not implemented yet.**_

**Comment by seriallos** [comment]
Hateful Chain was only added to SimC this week so it's only available in the Nightly build: https://www.raidbots.com/simbot/report/u2nn359BpzQsyZbtqofH1B

You can find the Raidbots SimC Version selector in the "Simulation Options" section:

![image](https://user-images.githubusercontent.com/1010294/102143310-a1d28e00-3e18-11eb-9512-3a1640743336.png)
