### ISSUE TITLE
Crafted Item Appears with No Secondary Stats

### ISSUE THREAD

**Issue by wheatbread** [seriallos/raidbots-issues#231]
**Describe the bug**

**To Reproduce**
1. Go to Gear Compare
2. Add 'Shadebound Armguards' as the gear for comparison
3. This item will have random secondary stats and I expected to be able to select it and sim it, but there is no such option.  Item just lists as pure primary stats.

There are several possible versions of this item due to Crafter's Mark.  It doesn't seem to change, though, no matter what item level I put in (I wanted to sim the 168 version).

**Comment by seriallos** [comment]
There's now a "secondary stats" dropdown for crafted items. This had been on my todo list for a bit and I was finally able to finish it today.
