### ISSUE TITLE
Haunting Apparitions Conduit: Incorrect Value

### ISSUE THREAD

**Issue by adamkbice** [seriallos/raidbots-issues#232]
In game, my ilvl 200 Haunting Apparitions conduit adds 43.4% more damage to Shadowy Apparitions, but in Raidbots it's only adding 35%. 
Ingame: 
![image](https://user-images.githubusercontent.com/11094595/103101629-87ea3580-45e6-11eb-8368-b1b960955ce9.png)
Raidbots: 
![image](https://user-images.githubusercontent.com/11094595/103101834-6473ba80-45e7-11eb-93de-3d3b9b2bda65.png)

It may only be a display issue, but all other conduit values are displaying the exact values I see in game.
Thanks

**Comment by seriallos** [comment]
It's just a tooltip issue. Tooltips are from Wowhead and only used for display, SimC uses its own game data parsing.

**Comment by adamkbice** [comment]
Odd that all other tooltips in Raidbots are exactly the same as in-game, including decimal places. Nothing I'm looking at in Raidbots matches Wowhead. But as long as the team's aware, I guess.

**Comment by seriallos** [comment]
Wowhead having slightly incorrect tooltips is very common. I've let Wowhead know about the discrepancy.
