### ISSUE TITLE
Inaccurate sims for affliction warlock with item dots

### ISSUE THREAD

**Issue by Daxerious** [seriallos/raidbots-issues#236]
**Describe the bug**
For Affliction Warlock simulations, I believe non player spell dots (e.g. dots from trinkets) are counting towards malefic rapture dot count for damage. This should not be the case as I tested this in game with 2 trinkets including “Vial of Caustic liquid” tinker by proving the dot, and was unable to cast malefic rapture, but yet in the sims it shows the damage per cast of malefic rapture is higher with a trinket like that then without.

**To Reproduce**
1. Create 2 simulations (1 with a dot trinket, and one without) and compare the malefic rapture damage per cast.

**Expected behavior**
I expected higher Ilvl trinkets (e.g. 213ilvl glyph) to out sim a low ilvl trink (e.g. 187ilvl caustic liquid) but it didn’t (even though the proc dmg for 213 was higher and stats were higher). So I dug into the reports... found that malefic rapture was hitting harder. Tested in-game the opposite effect.

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/vFCe6MTWanNu6bXzx6cvv1

I have a feeling this extends to other item dots which don’t actually count.

**Comment by seriallos** [comment]
I don't directly maintain the warlock module so your best bet is to report this to SimC project itself: https://github.com/simulationcraft/simc/issues

I'll forward it on to the SimC devs as well to get their attention.
