### ISSUE TITLE
QuickSim set to 5 min runtime but completed in 4 mins @ Sample Ability Log

### ISSUE THREAD

**Issue by Shywawa** [seriallos/raidbots-issues#237]
Hi,

Not sure if a bug or not but i had the Quick Sim set for 5 mins but in the Sample Ability Log the actions finished 1 min earlier.
Fight ended at 4.12 min. While siming 4 mins fight this ended at 3,52. 
is this intended?

Kind regards,

Shywawa

**Comment by seriallos** [comment]
By default, Raidbots/SimC uses a 20% variance on the fight duration so choosing "5 minutes" will result in fights that last 4-6 minutes. The fight duration for the iteration shown in the Sample Ability Log is random and will change every time you run a quick sim. This variance is desirable to make sure that there aren't specific/weird fight timings that would result in outlier results.

SimC also has a lot of other options that you can play around with in advanced mode or using your own local copy of SimC: https://github.com/simulationcraft/simc/wiki/Options#configuration
