### ISSUE TITLE
Legendary comparisons for top gear don't seem to be factoring in iLvl increases

### ISSUE THREAD

**Issue by raysmith59** [seriallos/raidbots-issues#239]
I loaded in my hunter, added in the 235 legendaries with my best secondaries, picked a 235 chest with a utility effect (something about feign death) so the effect wouldn't impact the results to compare via my equipped 197 in Top Gear and it came back as a +9 dps upgrade.  I had originally tried doing a full comparison set with actual dps legendaries in various slots but all of the dps upgrade results were underwhelming and about what I expected to get just from the legendary effects which got me to try it with just the iLvl in play.

Obviously, I'd like the dps increase due to the iLvl increase to show up in the results.

**Comment by seriallos** [comment]
Please provide the sim URL where this is happening, not something I can diagnose otherwise

**Comment by raysmith59** [comment]
Is there a way I can send it to you privately rather than posting it here publicly?

**Comment by seriallos** [comment]
Email support@raidbots.com or DM me in Discord (seriallos#0001)

SimC definitely takes item level into account for legendaries so something else is going on.

It's pretty easy to set up examples, here's my character for reference:

Top Gear with one of my legendaries at various item levels: https://www.raidbots.com/simbot/report/5NDo1maKTbykJBEpY3kMT4

**Comment by raysmith59** [comment]
I just re-tested and it seems to be working correctly now and I didn't keep the old URL so I don't have any reference for it not working at this point.  Closing.
