### ISSUE TITLE
No artifact traits found from /simc input. Try running /simc again and/or update your addon

### ISSUE THREAD

**Issue by raymondgoho** [seriallos/raidbots-issues#24]
I cant run the quick sim suddenly

**Comment by seriallos** [comment]
Can you share your /simc input?

**Comment by raymondgoho** [comment]
demonhunter=""
level=101
race=night_elf
region=us
server=frostmourne
role=attack
professions=alchemy=1/enchanting=16
talents=2200000
spec=havoc
artifact=3:0:0:0:0:1010:1

head=,id=128879,bonus_id=1683/3392/3408
neck=,id=141588,bonus_id=1808/1502/3528
shoulder=,id=128950
back=,id=141589,bonus_id=1507/3336
chest=,id=141570,bonus_id=43/1522/3337
wrist=,id=141571,bonus_id=1502/3528
hands=,id=128954
waist=,id=128949
legs=,id=141569,bonus_id=1808/40/1502/3528
feet=,id=146669,bonus_id=1811/3570
finger1=,id=128948
finger2=,id=141580,bonus_id=1808/1502/3528
trinket1=,id=141585,bonus_id=41/1502
trinket2=,id=128958
main_hand=,id=127829
off_hand=,id=127830

### Gear from Bags
#
# Helm of Reaffirmed Purpose (690)
# head=,id=138970
#
# Inquisitor's Glowering Eye (680)
# neck=,id=128945
#
# Voras' Silk Drape (680)
# back=,id=128944
#
# Torment Ender's Chestguard (680)
# chest=,id=128952
#
# Pit Lord's Cuffs (680)
# wrist=,id=128947
#
# Telubis' Binding of Patience (850)
# waist=,id=141564,bonus_id=1512/3336
#
# Leggings of Sacrifice (680)
# legs=,id=128951
#
# Treads of Illidari Supremacy (680)
# feet=,id=128953
#
# Illidari Ring (660)
# finger1=,id=112459
#
# Seal of House Wrynn (695)
# trinket1=,id=128959,bonus_id=545
#
# Fel-Etched Glaive (685)
# main_hand=,id=128956
#
# Fel-Etched Glaive (685)
# main_hand=,id=132243
#
# Fel-Etched Glaive (685)
# off_hand=,id=128956
#
# Fel-Etched Glaive (685)
# off_hand=,id=132243
#

**Comment by seriallos** [comment]
Raidbots basically doesn't support fresh 101s particularly well, you'll need to get a relic in the artifact before you can sim that character.
