### ISSUE TITLE
Covenant gear set bonuses aren't included in Raidbots results (top gear or quick sim)

### ISSUE THREAD

**Issue by raysmith59** [seriallos/raidbots-issues#240]
Both my mage and hunter covenant sets have 5pc set bonuses that work in M+ and raids but don't show up in the Raidbots results.

Hunter - 5pc Venthyr - Penance Brand - Contributes ~1.7% of my damage in raid fights and shows up in WL parses
Mage - 5pc Necrolord - Flesh Infusion - +100 Int when Fleshcraft is active - I've confirmed this works in M+ (I get the buff) so it should work in raids, too

(don't mock the covenant choices, I know they're bad)

**Comment by seriallos** [comment]
These are not currently implemented in SimC. Issue should be reported on the SimC project: https://github.com/simulationcraft/simc/issues
