### ISSUE TITLE
Shadowcore Oil Blast included in Target Dummy sims

### ISSUE THREAD

**Issue by turtlshell** [seriallos/raidbots-issues#241]
Target Dummy sims are described as "Always 100% health, raid buffs/debuffs disabled, no consumables". Shadowcore Oil is a consumable, and yet is included in Target Dummy sims, which skews the results by 1% or so.

Sim a character for Target Dummy damage, check damage breakdown.

Expected behaviour is for Target Dummy sims to not include Shadowcore Oil damage.

Example: https://www.raidbots.com/simbot/report/9Mwvz9UaQhYRhpQXS2Usux

https://imgur.com/a/Oh6URtq

**Comment by seriallos** [comment]
Good catch. I'll have this fixed shortly.
