### ISSUE TITLE
PvP Conquest droptimizer is suggesting an unobtainable item

### ISSUE THREAD

**Issue by deamonized** [seriallos/raidbots-issues#245]
**Describe the bug**
The PvP Season 1 (Conquest) droptimizer is simming [Sinful Gladiator's Greatcloak](https://www.wowhead.com/item=180424/sinful-gladiators-prestigious-cloak), an item that does not exist on the conquest vendor

**To Reproduce**
1. Go to Droptimizer
2. Run a PvP Conquest sim
3. See error

**Expected behavior**
The list of simmed items is obtainable

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/fbUu3P3rjH8KfYBWSxQov

**Character or /simc input**

For "Load from Armory":

* Region: EU
* Realm: Tarren Mill
* Character Name: Dæmondk

**Comment by seriallos** [comment]
Thanks for the report! This is now fixed.
