### ISSUE TITLE
Fury warrior sim not using rampage or raging blow.

### ISSUE THREAD

**Issue by s2kallday** [seriallos/raidbots-issues#246]
Fury warrior patchwerk and dungeonslice sims do not utilize rampage nor raging blow causing HUGELY inaccurate simulations.

**Comment by seriallos** [comment]
Can you link a sim?

**Comment by s2kallday** [comment]
Link for example:
https://www.raidbots.com/simbot/report/a2p9xgdrqDD1xhSYV7BsYC

**Comment by seriallos** [comment]
You have a shield equipped in your off-hand, not a weapon. That prevents a whole bunch of things to not work in the sim when you are Fury.

Make sure you log out with your fury weapons equipped (or use the /simc addon) and it should sim fine.
