### ISSUE TITLE
Double summer on pull

### ISSUE THREAD

**Issue by Chknmasala** [seriallos/raidbots-issues#248]
**Describe the bug**
Looks like the sim is using Blessing of Summer for Ret Palading Night Fae 2x in a row before getting to the other blessing: Autum, Winter, Spring and back to Summer.

**To Reproduce**
Steps to reproduce the behavior: Quick sim to see the rotation used by the sim.
1. Go to 'quick sim'
2. Click on 'sim'
3. Scroll down to 'rotations'

**Expected behavior**
If you cast Summer before the pull or after the Pull you will only get 1 summer regardless, and the next blessing of seasons should be autum and so forth, double summer is a big dps increase and it's not possible.

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/gLrkwtQFR8mHGCzC56DDAX

For "Load from Armory":
* Region US
* Realm / Server Proudmoure
* Character Name CHKNPARMESAN

**Screenshots**
![image](https://user-images.githubusercontent.com/78102885/106033654-d5930b80-6086-11eb-862b-9c062bab0d93.png)
![image](https://user-images.githubusercontent.com/78102885/106033696-e17ecd80-6086-11eb-9ade-3ff05f110c63.png)

**Additional context**
as you can see the next blessing after summer was summer again which is not possible and is boosting the dps noticeably

**Comment by seriallos** [comment]
From what I can tell from some quick research (I'm not a pally expert), if you pre-cast summer before the pull it gets reset so you can use it twice. This seems intended.

If you find this is not true, I'd recommend following up in the Pally Discord or directly with the SimC project.

**Comment by Chknmasala** [comment]
if you cast before pull it will continue the cd to autumn (45sec) if you have other blessings it will reset it to Summer but only if you don't use the current blessing otherwise it continue where you triggered it. 

It's only designed to grantee you have summer on pull. It will not reset the CD if you pop it before pull and have the blessing active.

**Comment by seriallos** [comment]
Open an issue on the SimC project: https://github.com/simulationcraft/simc/issues
