### ISSUE TITLE
[Bug?]Wrong item stats on Foul-Sadist's Seal. 

### ISSUE THREAD

**Issue by morph4037** [seriallos/raidbots-issues#25]
Currently trying to sim my character Kegstand-Cenarion Circle and the Foul-Sadist's Seal has the wrong stats on here and in the wowdb link. [Foul-Sadist's Seal](http://www.wowdb.com/items/150989-foul-sadists-seal?bonusIDs=3573,1808,1572,3528&setPieces=142134,134495,147053,138372,147743,147747,138341,134251,147746,137035,150989,137050,141536,134204,128935,128936) The numerical values are correct however the 1,158 stat is versitility and 1,960 is mastery. 
[Ring on live](http://i.imgur.com/vQYJOYb.jpg?2)
Wasn't to sure how to go about reporting this and hope it helps.

**Comment by seriallos** [comment]
Problem with WoWDB tooltips, I'll pass it on.
