### ISSUE TITLE
Fire mage haste showing negative value in stat weights

### ISSUE THREAD

**Issue by pyrozr** [seriallos/raidbots-issues#251]
**Describe the bug**
Siming Mage Fire spec in Stat weights showing haste as a negative value (More haste reducing dps)

**Expected behavior**
I can understand certain stats having little value due to diminishing returns but a negative value seems like an error of some sort. How could a fire mage's ability to produce more spells during their power windows cause a drop in dps?

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/skKo6LkkAYC6yeukJihacD

# Pyrozr - Fire - 2021-02-02 21:36 - US/Mal'Ganis
# SimC Addon 9.0.2-15
# Requires SimulationCraft 901-01 or newer

mage="Pyrozr"
level="60"
race="troll"
region="us"
server="malganis"
role="spell"
professions="tailoring=100/enchanting=115"
talents="3231111"
spec="fire"

covenant="venthyr"
# soulbind=nadjia_the_mistblade:8,331586/20:5/331576/29:4/331579/48:5/21:5
soulbind="theotar_the_mad_duke:9,336239/61:5/336140/30:5/336184/45:4/249:4"
# soulbind=general_draven:3,340159/319982/332756
# conduits_available=17:5/18:5/20:5/21:5/30:5/32:4/34:5/36:4/43:5/51:4/53:5/55:5/249:4/23:4/26:5/29:4/58:5/45:4/48:5/61:5
# renown=28

head=",id=180913,bonus_id=7201/1514/6646"
neck=",id=183040,bonus_id=7188/6652/6935/1485/6646"
shoulder=",id=178859,bonus_id=7203/6652/1501/5852/6646"
back=",id=183032,enchant_id=6202,bonus_id=7189/1472/6646"
chest=",id=180901,enchant_id=6230,bonus_id=7201/1514/6646"
wrist=",id=178782,enchant_id=6220,bonus_id=7209/6652/7193/1501/5878/6646"
hands=",id=184170,bonus_id=6652/42/1492/6646"
waist=",id=173248,bonus_id=6931/6716/7193/6647/6649/1487"
legs=",id=180107,bonus_id=7206/6652/1501/5871/6646"
feet=",id=182979,bonus_id=7189/6652/1472/6646"
finger1=",id=178824,enchant_id=6166,bonus_id=7207/6652/7193/1501/5858/6646"
finger2=",id=178871,enchant_id=6170,bonus_id=6807/6652/7194/1498/6646"
trinket1=",id=184030,bonus_id=7189/6652/1472/6646"
trinket2=",id=178809,bonus_id=7206/6652/1501/5858/6646"
main_hand=",id=179339,enchant_id=6229,bonus_id=7210/6652/1501/5878/6646"

### Gear from Bags
#
# Sin Stained Pendant (216)
# neck=,id=178827,bonus_id=7207/6652/7193/1501/5874/6646
#
# Shadowlace Mantle (168)
# shoulder=,id=173220,bonus_id=6893/7185,drop_level=60,crafted_stats=49/32
#
# Blighted Margrave's Cloak (200)
# back=,id=178755,enchant_id=6208,bonus_id=7206/6652/1501/5858/6646
#
# Cinch of Infinite Tightness (200)
# waist=,id=183028,bonus_id=7189/6652/7194/1472/6646
#
# Icebringer (235)
# legs=,id=173246,bonus_id=6830/6647/6649/6758/1532
#
# Frostburn (190)
# legs=,id=173246,bonus_id=6823/6716/6649/6647/1487
#
# Entwined Gorger Tendril (187)
# finger1=,id=178848,enchant_id=6170,bonus_id=6808/6652/7194/1501/6646
#
# Sprigthistle Loop (181)
# finger1=,id=175713,bonus_id=6652/7193/1472/5878/6616
#
# Kaal's Gloomblade (194)
# main_hand=,id=178856,enchant_id=6229,bonus_id=7203/6652/1501/5852/6646
#
# Lakali's Spire of Knowledge (200)
# main_hand=,id=178714,enchant_id=6229,bonus_id=7206/6652/1501/5858/6646
#
# The Brokers Angle'r (40)
# main_hand=,id=180136,enchant_id=5357
#
# Master Stonewright's Chisel (207)
# off_hand=,id=182400,bonus_id=7189/6652/1505/6646
#
# Nathrian Tabernacle (203)
# off_hand=,id=178828,bonus_id=7210/6652/1501/5861/6646
name="Pyrozr"

temporary_enchant="main_hand:shadowcore_oil"
shadowlands.stone_legionnaires_in_party="0"
shadowlands.crimson_choir_in_party="0"
shadowlands.disable_iqd_execute="0"
shadowlands.iqd_stat_fail_chance="0"
shadowlands.unbound_changeling_stat_type=""

# Simulation Configs
iterations="5000"
fight_style="DungeonSlice"
desired_targets="1"
max_time="360"
calculate_scale_factors="1"
scale_only="strength,intellect,agility,crit,mastery,vers,haste,weapon_dps,weapon_offhand_dps"
override.bloodlust="1"
override.arcane_intellect="1"
override.power_word_fortitude="1"
override.battle_shout="1"
override.mystic_touch="0"
override.chaos_brand="0"
override.windfury_totem="0"
override.bleeding="1"
report_details="1"
single_actor_batch="1"
optimize_expressions="1"

**Comment by seriallos** [comment]
The mage module only fully supports Patchwerk at this time. Sims on other fight styles are not optimized and may behave strangely (especially in regards to discontinuities in the value of haste)
