### ISSUE TITLE
Gear Compare Results - Can't run run output results in other simulations

### ISSUE THREAD

**Issue by asangster** [seriallos/raidbots-issues#252]
If I run top gear - I can re-run the results of my simulation into another simulation ie talent compare. 
![image](https://user-images.githubusercontent.com/12052782/106899446-45d80780-66ed-11eb-943a-b3d384566810.png)

I cannot do this in Gear compare - it would be great if I could.
![image](https://user-images.githubusercontent.com/12052782/106899662-89cb0c80-66ed-11eb-949d-6b320637215b.png)

Reason: I'm trying to sim Legendary items that I do not yet own. However I'd like to change my talent setup before or after I run the compare sim. If I would run a Gear Compare sim, click the "..." (like in top gear) and run that setup in talent compare, I can achieve this.

**Comment by seriallos** [comment]
Not planned at this time.
