### ISSUE TITLE
Niya's Tools: Poisons applies no Paralytic Poison on Casting Patchwerk

### ISSUE THREAD

**Issue by nb41** [seriallos/raidbots-issues#255]
**Describe the bug**
Casting Patchwerk sims aren't actually simming any interrupts, that I can tell. I set a Top Gear sim to Casting Patchwek, and asked it to compare Niya's Tools: Burrs to Niya's Tools: Poisons. Poisons insists there is no Paralytic Poison damage, and that no interrupts were cast. But if it's set to Casting Patchwerk, shouldn't I get some? Note that pet interrupts WILL apply Paralytic Poison so even if it's only the per interrupt I should still see i (if much lower).

**To Reproduce**
Take a DK character (I'm UH, maybe that's relevant?), run a Top Gear sim of Nightfae Soulbind for Niya, Burrs vs. Poisons. Set the simulation type to Casting Patchwerk (or any sim type which would include interrupts).

**Expected behavior**
There should be *some* Paralytic Poison damage, assuming not all interrupts were missed.

**If you have a sim report that shows the problem, please provide the URL here**
https://www.raidbots.com/simbot/report/jCTECixnGjUztYN6Z7g8uh

**Character or /simc input**
```
# Grimdarque - Unholy - 2021-02-08 19:27 - US/Proudmoore
# SimC Addon 9.0.2-15
# Requires SimulationCraft 901-01 or newer

deathknight="Grimdarque"
level="60"
race="worgen"
region="us"
server="proudmoore"
role="attack"
professions="herbalism=150/engineering=52"
talents="2333321"
spec="unholy"

covenant="night_fae"
soulbind="niya:1,322721/65:6/342270/70:5/320668/74:6/124:5/320660"
# soulbind=dreamweaver:2,319217/70:5/124:5/319211/65:6/74:6/319216
# soulbind=korayn:6,325066/88:6/325065/70:5/325073/121:5/250:5
# conduits_available=65:6/79:5/80:5/83:5/89:5/91:5/122:5/123:5/124:5/125:5/250:5/68:5/70:5/99:6/106:6/74:6/86:5/88:6/108:6/121:5
# renown=30

head=",id=182997,gem_id=173130,bonus_id=7188/6652/1485/6646/6935"
neck=",id=183040,bonus_id=7188/41/7193/1485/6646"
shoulder=",id=178820,bonus_id=7204/6652/1501/5868/6646"
back=",id=183033,enchant_id=6202,bonus_id=7188/6652/1485/6646"
chest=",id=171412,enchant_id=6230,bonus_id=6952/6649/6648/6758/1532"
shirt=",id=52019"
wrist=",id=179354,bonus_id=7209/6652/7193/1501/5878/6646"
hands=",id=178775,enchant_id=6210,bonus_id=7207/6652/1501/5874/6646"
waist=",id=183025,bonus_id=7188/6652/7193/1485/6646"
legs=",id=178701,bonus_id=7211/6652/1501/5865/6646"
feet=",id=183027,bonus_id=7188/6652/1485/6646"
finger1=",id=178824,enchant_id=6168,gem_id=173130,bonus_id=7209/6652/6935/1501/5861/6646"
finger2=",id=178871,enchant_id=6168,bonus_id=7208/6652/7194/1501/5874/6646"
trinket1=",id=179350,bonus_id=7210/6652/1501/5878/6646"
trinket2=",id=184030,bonus_id=7188/6652/1485/6646"
main_hand=",id=179544,enchant_id=3368,bonus_id=7188/6652/1511/6646"

### Gear from Bags
#
# Cowled Batwing Cloak (213)
# back=,id=183034,enchant_id=6202,bonus_id=7188/6652/1485/6646
#
# Breastplate of Cautious Calculation (213)
# chest=,id=182987,bonus_id=7188/6652/1485/6646
#
# Strain-Soaked Breastplate (235)
# chest=,id=171412,enchant_id=6230,bonus_id=6953/6649/6650/6758/1532
#
# Rampaging Giant's Chestplate (213)
# chest=,id=182999,bonus_id=7188/6652/1485/6646
#
# Irradiated Undercoat (1)
# shirt=,id=169878
#
# Binding of Warped Desires (213)
# waist=,id=183015,bonus_id=7188/6652/7194/1485/6646
#
# Legplates of Unholy Frenzy (207)
# legs=,id=178739,bonus_id=7211/6652/1501/5865/6646
#
# Halkias's Towering Pillars (203)
# legs=,id=178818,bonus_id=7210/6652/1501/5861/6646
#
# Ardent Sunstar Signet (213)
# finger1=,id=183035,enchant_id=6170,bonus_id=7188/6652/7194/1485/6646
#
# Blood-Spattered Scale (203)
# trinket1=,id=179331,bonus_id=7209/6652/1501/5861/6646
#
# Stone Legion Heraldry (207)
# trinket1=,id=184027,bonus_id=7189/6652/1472/6646
#
# Overwhelming Power Crystal (216)
# trinket1=,id=179342,bonus_id=7207/6652/1501/5874/6646
#
# Macabre Sheet Music (213)
# trinket1=,id=184024,bonus_id=7188/6652/1485/6646
```

**Additional context**
This is happening on BloodMallet *and* HeroDamage as well, so possibly this is a SimC problem?

**Comment by seriallos** [comment]
Quick answer is that this is SimC and potentially specific to DKs. I can take a deeper look later or tomorrow but you might have a quicker answer if you report to SimC directly or ask around in Discords.

**Comment by nb41** [comment]
:+1: Will do.

**Comment by nb41** [comment]
Per the SimC folks, Mind Freeze isn't in the APL (the Blood and Frost numbers are from margin of error). So, in order to sim Niya's Tools: Poisons accurately on Casting Patchwerk (or any interrupt sim), the interrupt has to be added into the APL. (Not asking for this to be done, just relaying what they indicated; I realize you'd need to look at all of the classes and specs.)

**Comment by nb41** [comment]
Oh! They're adding it in, so it should show up in the nightly build.

**Comment by seriallos** [comment]
Cool, closing this out!
