### ISSUE TITLE
Possible gear compare bug

### ISSUE THREAD

**Issue by cls97** [seriallos/raidbots-issues#256]
**Describe the bug**
I simmed my 3 drops from the great vault, when I enable buffs and everything, 1 item stands out from the rest, when I disable them it doesnt, has to be a sim mistake there imo (see screenshots)

![image](https://user-images.githubusercontent.com/26996538/107490162-caada000-6b89-11eb-8e2c-21930047cd36.jpeg)

![image](https://user-images.githubusercontent.com/26996538/107490181-d0a38100-6b89-11eb-98ed-d3e632bc484c.jpeg)

**Comment by seriallos** [comment]
Please link the full sim URLs for both of those sims.
