### ISSUE TITLE
Condemn Conduit Juggernaut

### ISSUE THREAD

**Issue by Aerlionyx** [seriallos/raidbots-issues#257]
After upgrading my Condemn conduit from 200 to 213 I noticed a small upgrade in game but after re siming myself I got over 150 DPS and realised its because on Raidbots (Nightly) is reading the conduit wrong saying the gain is 3.8 crit chance when in reality it gives 1.9 crit chance per stack. 

Conduit in game: 
https://i.imgur.com/QrYJ1Rn.png
Conduit on Raidbots: 
https://i.imgur.com/AexULc1.png

**Comment by seriallos** [comment]
That's just a tooltip issue - the wowhead tooltip doesn't know that your character is Venthyr which halves the crit chance. This is taken into account in the sim.

The DPS difference is from something else. I would need to see both full sims, before and after, to figure out the DPS difference.

**Comment by Aerlionyx** [comment]
Before: https://www.raidbots.com/simbot/report/t42Reghve9JPFYURA926E8 
After: https://www.raidbots.com/simbot/report/jRCGwakAtM2re6XXyVkNGb

**Comment by seriallos** [comment]
Before sim has 4 empty sockets and the 200 conduit, after sim has those sockets filled and has the 213 conduit. The missing gems are the bulk of the DPS difference.

I edited your /simc input to have the sockets filled and the conduit back down at item level 200 to get this result: https://www.raidbots.com/simbot/report/6wNUVamUBCUvexThyxANeL

So once everything is controlled, you can see that the ilevel 200 -> 213 is an upgrade of about 20 DPS
