### ISSUE TITLE
Elemental Equilibrium - Resto Shaman

### ISSUE THREAD

**Issue by nsgocev** [seriallos/raidbots-issues#258]
The Elemental Equilibrium legendary doesn't seem to sim properly for Restoration Shamans.

1. The uptime of the buff is calculated really strange
2. It doesn't seem to add frost shock into the rotation to active the legendary

Link to a sample report: https://www.raidbots.com/simbot/report/6jLx1KfeCjdSd1xNwfKr4a

**Comment by seriallos** [comment]
This is better reported directly to SimC as that is the project that does the actual modeling: https://github.com/simulationcraft/simc/issues
