### ISSUE TITLE
Bloodthirst not enraging with fresh meat

### ISSUE THREAD

**Issue by weiweiqin0714** [seriallos/raidbots-issues#259]
**Describe the bug**
Bloodthirst is not enraging me on the first hit.

**To Reproduce**
Sim my Character:wuhandidit-tich

**Expected behavior**
I should be enraging on bloodthirst

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/6K6tEZu7m3ecK5cjmqAf8B

**Comment by seriallos** [comment]
I've forwarded this on to SimC: https://github.com/simulationcraft/simc/issues/5804
