### ISSUE TITLE
Lightforged Draenei Racial not casted

### ISSUE THREAD

**Issue by Anburix** [seriallos/raidbots-issues#260]
Hi,

As a Blood DK I tried to compare my Draenei to his lightforged cousin (since Bloodmallet ranks Lightforged at the top) but the sim was lower and I could not see the casts of the Light's Judgement either on the reports or on the HTML report.

The HTML Report : https://www.raidbots.com/simbot/report/tksB4j1cwvtXkssZx9VZfE/simc

Best Regards,

Jean

**Comment by seriallos** [comment]
I'm not a DK expert so I'd recommend double checking with theorycrafters/SimC devs in the DK Discord and/or reporting this directly to SimC (https://github.com/simulationcraft/simc/issues) - but it looks like the Blood APL only uses Light's Judgment if Unholy Strength is up. I assume this is just out-of-date for the new runeforges so it needs a little bit of updating by someone familiar with Blood DK APL.

**Comment by Anburix** [comment]
I was using the rune of sanguination to test it with the death certainty
legendary since fallen crusader is nerfed in pvp at 10% strength buff.

It sure can explain the issue!

Le mar. 23 févr. 2021 à 00:13, Dave Hendler <notifications@github.com> a
écrit :
