### ISSUE TITLE
Empyreal Ordinance Sim Bug

### ISSUE THREAD

**Issue by StandProud591** [seriallos/raidbots-issues#263]
When attempting to Sim my 210 Empyreal Ordinance the sim has it giving 0 intellect off the active use resulting in a massive DPS loss. Using the exact same string I copy and pasted my friends sim did not have this issue. The first image is a screen shot from my sim and the second is a screenshot from his sim. 
![Capture](https://user-images.githubusercontent.com/79766452/109398387-b3e9a600-790a-11eb-8fab-58133b8ce928.PNG)
![image](https://user-images.githubusercontent.com/79766452/109398415-dd0a3680-790a-11eb-8def-99b311d58262.png)

**Comment by seriallos** [comment]
The tooltip is just a display issue - they are provided by Wowhead and completely separate from the numbers that SimulationCraft uses for the actual sims.

To figure out why the sims are different, please provide a URL for each of those sims. It's likely a different sim configuration or differences between characters - but I need to be able to view the full report to be able to figure out what's different.
