### ISSUE TITLE
Gear Compare is not taking ilvl adjustments into consideration

### ISSUE THREAD

**Issue by Dalfiuss** [seriallos/raidbots-issues#27]
When running gear compare, Raidbots will use the base ilvl of the item added rather than the changed ilvl.

It appears that it is trying to change the ilvl in the input, but for some reason it isn't adjusting it in the results.

Using the same string in a regular sim is updating the ilvl as normal.

As an example:
https://www.raidbots.com/simbot/report/dh7BU1GDctvVp4qXByeQDk

A ran gear compare with a +20 ilvl version of one trinket and it was a significant dps loss.

**Comment by seriallos** [comment]
This is a general issue for tanks on just about any sim on Raidbots. I'm hoping to fix it this week.

Basically, single_actor_batch=1 doesn't work correctly for tanks (only the first actor gets hit by a boss). If you run that compare in advanced mode and turn off single_actor_batch, you get results that are more in-line with what's expected:

https://www.raidbots.com/simbot/report/e9JR9zkwo5tv2ghp3kByHT

My plan is to disable single_actor_batch for tanks this week once the nether light crucible stuff calms down a bit.

**Comment by Dalfiuss** [comment]
Awesome! Thanks for the info.
