### ISSUE TITLE
Support override.spell_data in custom SimC options

### ISSUE THREAD

**Issue by ascott18** [seriallos/raidbots-issues#270]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to simulate being bad at Soulforge Embers uptime. An easy way to do this is to bump up the cooldown on Flare.

**Describe the solution you'd like**
Be able to add `override.spell_data=spell.1543.cooldown=30000` to the custom SimC options section.

**Describe alternatives you've considered**
Simulate manually with SimC desktop

**Additional context**
"override" SimC options are not whitelisted by Raidbots:
![image](https://user-images.githubusercontent.com/5017521/110575074-29c3ed80-8113-11eb-979c-a8d69ce2a1c8.png)

**Comment by seriallos** [comment]
While generally not recommended, this is now possible using SimC Expert Mode: https://support.raidbots.com/article/15-simc-expert-mode
