### ISSUE TITLE
Grim Codex shows 0 damage after simming

### ISSUE THREAD

**Issue by GringoREGS** [seriallos/raidbots-issues#277]
**Describe the bug**

**To Reproduce**
1. Start a sim
2. Use Grim Codex as a item
3. Finish sim
4. See error, 0 damage

**Expected behavior**
That the grim codex use deals damage

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/8gybYJsv5ihKuLFNg4av2K

If you have a sim report that shows the problem, please provide the URL here
https://www.raidbots.com/simbot/report/8gybYJsv5ihKuLFNg4av2K/simc

**Character or /simc input**

For "Load from Armory":

* Region EU
* Realm Argent Dawn
* Character Name Enraptured

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**
I can't make a screenshot because of a snipping tool I use. When I hover the mouse and press print screen, it automatically activates the snipping tool, removing the pop up that states 0 damage. 

**Additional context**
Couple of days ago, I simmed some trinkets to the grim codex and saw that the grim codex dps was higher than the BiS trinkets. When I went to check again to see which BiS trinket was better suited with the Grim codex, it was suddenly worse and then I noticed that the damage on the ilv 220 Grim Codex is shown as 0. I gave it a day or two but it's still portraying 0 damage.

**Comment by seriallos** [comment]
Tooltips are from Wowhead and are just used for reference. SimulationCraft itself uses its own spell database and is properly simulating the damage for Grim Codex.

In the full HTML report you linked, check the Abilities table to see stats about damage from the item:

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1010294/117737219-3ebe0b00-b1ae-11eb-8ac0-d9f05371f33b.png">
