### ISSUE TITLE
Bug on Trincket Inscrutable Quantium Device;

### ISSUE THREAD

**Issue by Aztheiloth** [seriallos/raidbots-issues#279]
Inscrutable Quantium Device; no matter what choice (crit, hast or maes) you pick, simulation is always with crit. I cannot notice my real dps if some another stat happens!!
- Dungeons Trinckets
- Unbound Changeling Proc

**Comment by seriallos** [comment]
IQD and Unbound Changeling are different items. The IQD stat proc is determined by your character stats so the proc will only change if the overall stats on your gear change.
