### ISSUE TITLE
The conduit "Adaptive Armor Fragment" is not unlocked by SimC import

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#281]
**Describe the bug**
The new conduit "Adaptive Armor Fragment" is not unlocked in Top Gear if a character that has already learned it is imported.

**To Reproduce**
1. Import the supplied character data.
2. See that the conduit "Adaptive Armor Fragment" is not selectable unless "unlock all conduits" is enabled.

**Expected behavior**
The conduit should be unlocked (and have the correct item level).

**Character or /simc input**
For "Load from SimC Addon": https://pastebin.com/XjpEvJPh

**Additional context**
It seems like this is the conduit as returned by `C_Soulbinds.GetConduitCollection(1)`:
```
  [9]={
    conduitID=284,
    conduitType=1,
    conduitItemLevel=200,
    conduitItemID=187507,
    conduitSpecSetID=1,
    conduitRank=5,
    conduitSpecIDs={
    }
  },
```
So the part in the /simc output should be `284:5` for my profile.

**Comment by seriallos** [comment]
This is by design. The default Top Gear mode is to display conduits that are tagged for your spec and Adaptive Armor Fragment is not tagged for Ret. Looks like Blizzard has tagged it for tanks so it will show up when your character is in a tanking spec.

**Comment by cremor** [comment]
@seriallos Where do you see this tank flag? Ingame this conduit shows without any spec icon, just like the spec independent covenant ability conduit, It's the second one in this screenshot:

![grafik](https://user-images.githubusercontent.com/116314/124313168-c4d44d80-db70-11eb-8658-2fd95fa8db1d.png)

**Comment by seriallos** [comment]
I use the game data files (DBCs extracted directly from the game files) to generate this data. I haven't updated in a few days so it's possible a hotfix updated the spec requirements for that conduit. If it's been updated in the game data, Raidbots will automatically adjust once I rebuild the info. This will happen by next week at the latest, might happen earlier.

**Comment by cremor** [comment]
I have a theory why you only see the tank specs in the data files: According to the dungeon journal the world boss drops the conduit only for tank specs.

**Comment by cremor** [comment]
@seriallos Any update on this issue?
Adaptive Armor Fragment is still not shown for Ret Paladin without using "unlock all conduits". It is at least competitive in M+ scenarios now, sometimes even the best option. So I think it should be available in the UI by default.

**Comment by seriallos** [comment]
This never changed in the game data. It's likely the SpecSetID indicates the loot spec required for the conduit to drop, not the specs that can use it.

Unfortunately I don't have any plans on changing this behavior as there's not really any clean way to do it in the Raidbots codebase without some really substantial work. The game data drives a lot of the UI and while I have the capability for some surgical overrides, this one would require more significant tweaking (would need to create a brand new SpecSet and properly inject/override that) which isn't currently in my plans.
