### ISSUE TITLE
Crafted Items miss second stat

### ISSUE THREAD

**Issue by Sheps30** [seriallos/raidbots-issues#282]
I dont know if its intended or not, but the ilvl230 crafted stuff dosnt show/sim with the second stat u can choose.

![Screenshot 2021-07-05 075337](https://user-images.githubusercontent.com/43088242/124423866-49d48800-dd66-11eb-85fd-6e4683d70b5e.jpg)

**Comment by seriallos** [comment]
This should be fixed now
