### ISSUE TITLE
Bag of Munitions

### ISSUE THREAD

**Issue by BogdanGP7** [seriallos/raidbots-issues#284]
**Describe the bug**
Bag of Munitions - Necrolord Hunter legendary is not being simmed right.

**Expected behavior**
Explosive shots to appear in damage breakdown, dps to be higher that a basic stat stick item.

**Link a sim with the problem (if available)**
If you have a sim report that shows the problem, please provide the URL here

https://www.raidbots.com/simbot/report/86yWe9vZ1JdttX72u4Gymr

**Comment by seriallos** [comment]
Looks like Bag of Munitions has not been implemented in SimC yet. Once it gets implemented, it should work properly.
