### ISSUE TITLE
Casters trinket "Tome of Insight" 220 ilvl isn't correct stats

### ISSUE THREAD

**Issue by VladRuda** [seriallos/raidbots-issues#285]
Hi all.
I've realised that information about this trinket isn't correct because it's shows that it has +304 crit, but at retail it's only 176 crit.
I think it's because yours site get information from ptr.
ptr - https://ptr.wowhead.com/item=186156/tome-of-insight?bonus=6652:7695:1492:6646&ilvl=220
retail - https://www.wowhead.com/item=186156/tome-of-insight?bonus=6652:7695:1492:6646&ilvl=220
Over all, thank you for yours work. You're the best.

**Comment by seriallos** [comment]
Tooltips are from Wowhead and are separate from SimC. SimC is always more up-to-date than Wowhead tooltips (they often lag behind by a few days). Check a full HTML report to see what the sim is actually doing, not the tooltips.

While possible, it's extremely rare that SimC uses the wrong stats in a simulation.

**Comment by seriallos** [comment]
I'll also probably be switching back to retail tooltips soon. In the first week or two, the Wowhead PTR tooltips tend to be more up-to-date than the retail ones.

And again, the Wowhead tooltips have no bearing on the actual simulation. It's using its own data.
