### ISSUE TITLE
Prepared Buff Momentum

### ISSUE THREAD

**Issue by Roxxtex** [seriallos/raidbots-issues#286]
When i quicksim my dh with the "momentum" talent the buffuptime table tells me that "prepared" from the skill "vengeful retreat" reduces its cooldown by 10 sec. buts its actualy only 5 sec. (and seems to be buggy in the game i dont get any cd reduction at all)

**Comment by seriallos** [comment]
Without seeing the sim, I'm 99% confident it's just a tooltip issue. Wowhead tooltips are just used for information and can lag behind or not be 100% correct. SimC itself uses its own data and rarely has this kind of problem.

Check the "Full HTML Report" and look at the Buffs section - you can expand each ability and see far more detail on how SimC is modeling the ability/buff.
