### ISSUE TITLE
Droptimizer doesn't exclude already equipped item

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#289]
**Describe the bug**
The Droptimizer doesn't detect that my gloves are from the new raid and still considers them for upgrades when I run the raid sim.

**To Reproduce**
1. Go to https://www.raidbots.com/simbot/report/ncVE6hcwB7qr4GNuB9SXy9
2. Click on 'Run in Droptimizer' for any of the two results.
3. Run Droptimizer for the heroic raid.
4. See that it doesn't exclude the gloves from The Nine boss.
5. Run it
6. See that it simmed the gloves

**Expected behavior**
It should detetct that I already have the gloves equipped and exclude them.

**Additional context**
Maybe related to the domination socket.

**Comment by seriallos** [comment]
Should be fixed now. Thanks for the report!
