### ISSUE TITLE
Trait "Fluffy, Go" crashes relic compare when used as 3rd crucible tier

### ISSUE THREAD

**Issue by Ugrel** [seriallos/raidbots-issues#29]
Use of the survival hunter trait "Fluffy, Go" in a third crucible tier crashes the relic compare tool with a series of odd rogue aura errors, and a (more relevant) error indicating the first copy line containing "Fluffy, Go" is unrecognized.  I think the comma is causing a problem.  Elimination of all relic lines containing "fluffy, go" allows the same sim to be run normally, but of course then you can't sim that third tier trait.

**Comment by seriallos** [comment]
Can you share some simc input or a region/realm/character?

I think I know what the problem is but would like to be able to confirm I have it fixed.

**Comment by seriallos** [comment]
Went ahead and deployed a fix so it should be good to go. If I failed to fix it, let me know!

**Comment by Ugrel** [comment]
Looks like it does indeed work now- sorry for the late response, I had to step out for the evening.  But yes, looks good- much appreciate the fast response and quick turnaround on the fix!


________________________________
