### ISSUE TITLE
Use Item Inscrutable Quantum Device

### ISSUE THREAD

**Issue by Msszup** [seriallos/raidbots-issues#290]
**Describe the bug**
Use Item Inscrutable Quantum Device show 25s buffs.

**In game**
It's actually only 20 seconds.
So it is overrated as a trinket and will have incorrect simulation values (I think).
But I'm not sure if it's just a display BUG.
https://www.raidbots.com/simbot/report/bTZwSP1e3TCKF6p9rMCUoh

**Comment by seriallos** [comment]
Using IQD during bloodlust grants a 25 second buff, using it outside of lust is just 20 seconds.

It's a weird item with lots of edge cases!
