### ISSUE TITLE
Top Gear does not select best domination shard combination when 'Domination Shard Set Bonuses' are disabled

### ISSUE THREAD

**Issue by revolive** [seriallos/raidbots-issues#293]
**Describe the bug**
Using Top Gear with "Domination Shard Set Bonuses" disabled does not produce the best result as it still seems to favor shard sets for simulation instead of checking all combinations.

**To Reproduce**
1. Open Top Gear
2. Select "Replace Existing Gems/Enchants"
3. Select the nine base shards (not upgraded versions)
4. Disable "Domination Shard Set Bonuses" in "Simulation Options"

The result should have the three DPS shards selected, as this results in the highest DPS. But the combinations of the shards only seem to favor sets, witch results in lower DPS. Manually selecting only the three DPS shards results in higher DPS.

**Link a sim with the problem (if available)**

Sim with all nine base shards selected to overwrite => 7,752 DPS
https://www.raidbots.com/simbot/report/rcdekN2pNirRDC1WDfUKfT

Sim with just the three DPS shards selected to overwrite => 7,768 DPS
https://www.raidbots.com/simbot/report/gZ5guAJN8DVSUCuP7CYoXe

Best regards

**Comment by seriallos** [comment]
This is now fixed, Top Gear won't care about set bonuses when they are disabled
