### ISSUE TITLE
Domination Shards and Domination Shard Set Bonuses are not included when enabled in Quick Sim

### ISSUE THREAD

**Issue by Xyphin** [seriallos/raidbots-issues#294]
**Describe the bug:**
"Domination Shard Set Bonuses", and the shard effects themselves, are not included in quick sim when "Domination Shard Set Bonuses" is checked for a character with a socketed domination shard or valid domination set bonus. In my case, Soul Fragment and Chaos Bane did not contribute to the simulation (not in the summary, not in the full HTML report). 

**To Reproduce:**
1. Open Quick Sim
2. Enable "Domination Shard Set Bonuses" in "Simulation Options"
3. Check the Damage Breakdown and Buff Uptime sections for Domination Shard/Set Bonus details 

**Expected behavior:**
The result should include bonuses from a valid domination shard set and the individual shards themselves.

**Link a sim with the problem (if available):**
Sim taken ~30 minutes ago - domination shard bonuses are not working:
[https://www.raidbots.com/simbot/report/cc1gEhaAZdFQShGVUDDVZC](https://www.raidbots.com/simbot/report/cc1gEhaAZdFQShGVUDDVZC)

Sim taken 21 hours ago - domination shard bonuses were working:
[https://www.raidbots.com/simbot/report/v9MvLcDXg2aVCEPTHra5hR](https://www.raidbots.com/simbot/report/v9MvLcDXg2aVCEPTHra5hR)

**Comment by seriallos** [comment]
Dungeon Slice now automatically disables the set bonuses since it is simulating a dungeon environment where the set bonuses are not active. This change was not present in last week's Weekly build which is what the older sim was using.
