### ISSUE TITLE
Top Gear appears to only apply Domination Rune Word bonuses to the equipped set of gear

### ISSUE THREAD

**Issue by raphaelsk** [seriallos/raidbots-issues#295]
**Describe the bug**
Top Gear appears to only apply domination rune word bonuses (like Chaos Bane) to the current set of gear, and not to any combination of other gear, even if you manually have selected the same shards that you have equipped. As a result, Top Gear always finds the current set of gear to be the "best" by a significant (nearly 5%) margin.

**To Reproduce**
1. Take /simc output with a shards of domination 3-piece rune word bonus enabled.
2. Run Top Gear by selecting an additional trinket as a potential item, turning on replace gems, selecting the shards you currently have equipped in current gear (to avoid the issue in #291), and enabling shard rune word bonuses.
3. Top Gear reports that the current gear is the best by a significant margin.
4. Change your equipped trinkets to include the one you put as an option in step 2. (So, if you had trinkets A and B enabled initially, and told Top Gear to try out trinket C, then this time, select trinkets A and C).
5. Run /simc again, and drop the result into Top Gear.
6. Run Top Gear as you did in step 2, but select your original trinket as an option (so if you equipped trinkets A and C now, add trinket B as an option.)
7. Top Gear reports that the current gear (that is, using trinkets A and C) is the best by a significant margin.

**Expected behavior**
Given that the current gear is allegedly the best by nearly 5% in both cases, Top Gear should consistently show the same "best gear".

**Link a sim with the problem (if available)**
Trinket 1: Overwhelming Power Crystal
Trinket 2: Soul Cage Fragment
Trinket 3: Titanic Ocular Gland
Top Gear with trinkets 1 and 2 equipped, and 3 as an option: https://www.raidbots.com/simbot/report/knZBa9MuuCVTeAKZSwBhev
Top Gear with trinkets 1 and 3 equipped, and 2 as an option: https://www.raidbots.com/simbot/report/eFLBAr3zZjRYDg1oCebYFH

**Character or /simc input**
SIMC inputs available from the report pages.

**Screenshots**
N/A

**Additional context**
The reason there are 4 combos in both these sims is that i haven't enchanted my boots, but told Raidbots to apply an enchant. The enchant here (Soul Treads) doesn't affect DPS. You'll note that, in both Top Gear reports, the combination that represents the currently equipped gear set but with the boot enchant applied allegedly does nearly 5% less DPS!

**Comment by seriallos** [comment]
Your sims have "Replace Existing Gems/Enchants" enabled and you have lower tiers of Domination Shards selected so non-equipped gear sets are being tested with a weaker set bonus.

Unchecking the checkbox results in the sim you were expecting: https://www.raidbots.com/simbot/report/um4ap8oRFgqNPHarsPcb9V

**Comment by raphaelsk** [comment]
Ah ok, that makes sense. Thx.
