### ISSUE TITLE
[QUESTION] Change default Warlock pet - or at least compare pets ?

### ISSUE THREAD

**Issue by DylanCa** [seriallos/raidbots-issues#298]
**Is your feature request related to a problem? Please describe.**
If I remember correctly, I could use "default_pet=felhunter" or something around this to force the summoned Warlock's pet to be a Felhunter instead of an Imp. I would like to know if this is possible in the current state of Raidbots ? Or at least be able to dismiss the current pet & "actions+=summon_pet,felhunter"

If it already exists, then my bad, and thank you for this !

**Comment by seriallos** [comment]
You can now use `default_pet=` in the Custom APL and SimC Options section on the site.
