### ISSUE TITLE
Korthian Gear ranks in Top Gear tooltips are off by one

### ISSUE THREAD

**Issue by Rubio9** [seriallos/raidbots-issues#299]
**Describe the bug**
Korthian Gear should have ranks 1 through 6, but they show up in RaidBots tooltips as ranks 0 through 5.
It looks like the code to parse rank# from the bonus_id for it is subtracting 7692 (the value for rank 1) so for a rank 1 item, its bonus_id - 7692 = 7692-7692 = rank 0.  And so on for other ranks.
Everything else works and sims correctly but the wrong rank# is confusing.

**To Reproduce**
1. Import data with Korthian gear
2. Compare tooltips for gear shown in the Top Gear selection grid with tooltips in game.
3. See that actual Rank 1/6 reports as Rank 0/6, and so on.

**Comment by seriallos** [comment]
This is an issue on Wowhead's side. I reported it a while back and they know it's an issue.
