### ISSUE TITLE
Gear compare- chest piece issue

### ISSUE THREAD

**Issue by Gennbu17** [seriallos/raidbots-issues#3]
On my Ele shaman and DH when I try to replace the chest piece it will not work with any of the normal armor pieces. On my Shaman I could replace the chest with pvp gear somehow, however this was not the case for my demon hunter. 
I've had no issues correctly replacing gloves,legs, trinkets and cloak so far. Only seems to effect the chest piece.

![image](https://cloud.githubusercontent.com/assets/25933778/23174726/e57b00aa-f822-11e6-9fd7-3771239d4516.png)

**Comment by seriallos** [comment]
Really sorry for the delay, I didn't have notifications properly set up for this repo.

This was an issue with weird chest slot types and should be fixed.

Thanks for the report!
