### ISSUE TITLE
First Blood is using the wrong icon in Raidbots

### ISSUE THREAD

**Issue by Shirofune** [seriallos/raidbots-issues#30]
It's currently using this icon:

https://www.raidbots.com/icon/36/ability_deathwing_bloodcorruption_death.jpg

While it should be this one:

http://es.wowhead.com/spell=206416/primera-baja

Very minor bug, but a bug nonetheless.

Greetings and thanks.

**Comment by seriallos** [comment]
Unfortunately, it looks the Blizzard API provides the wrong icon for this talent. At some point I may look into importing data from client data which would be able to get this right but it's a pretty low priority.

I'll keep this in mind to see if there is some kind of manual override I can apply to my automation but it may just be the kind of thing that's difficult for me to create a permanent solution for.

**Comment by seriallos** [comment]
This should be fixed in an upcoming release as I'm finally importing data directly from the client and sidestepping the API with the incorrect info.
