### ISSUE TITLE
Top Gear with empty prismatic socket and specific shards selected shows wrong error

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#300]
**Describe the bug**
When an item with an empty prismatic socket and specific Shards of Domination are selected for Top Gear it shows a "Check your gem configuration" error that doesn't make sense.

**To Reproduce**
1. Go to https://www.raidbots.com/simbot/report/ddrsxdasWS2KuYUvafWyJX
2. Click on "Run sim again"
3. Select either "Shard of Bek" or "Shard of Tel" or "Shard of Oth".
4. See error that is shown in both the "prismatic gems" and the "Shards of Domination" sections. That error doesn't make any sense since there is only one empty prismatic socket and a prismatic gem is selected to fill it.

**Expected behavior**
Selecting those Shards of Domination shouldn't have any impact on the sim since there are no empty domination sockets and "Replace Existing Gems/Enchants" is not selected.

**Character or /simc input**
For "Load from SimC Addon": https://pastebin.com/DKwzKKBK

**Comment by seriallos** [comment]
Thanks for the report. This should now be fixed!
