### ISSUE TITLE
Dom set bonus not being applied in sim

### ISSUE THREAD

**Issue by himerope69** [seriallos/raidbots-issues#302]
I'm simming myself with the blood set bonus, and it seems the set bonus is not being applied. 

To reproduce. 

1. Use my SimC output below.
2. Leave everything default, but choose the 213 ilevel chest piece which will enable the blood set bonus and let it pick between these two options.
3. Notice that the chest piece *without* the set bonus sims 669 dps higher.  Given the power of these bonuses, this is clearly wrong.

I think this is related to a separate bug.  When I equipped the head slot item without any gem socketed, then only chose blood gems as options for the empty socket, raidbots would not let me run a sim because it didn't think any of the gems matched.  This is incorrect.  You can socket any gem in any piece, and I confirmed in game that the blood bonus is active with gems in the head/chest/gloves slots.

```
# MiscDruid- Balance - 2021-08-07 13:10 - US/Sargeras
# SimC Addon 9.1.0-01
# Requires SimulationCraft 910-01 or newer

druid="MiscDruid"
level=60
race=highmountain_tauren
region=us
server=sargeras
role=spell
professions=alchemy=175/herbalism=150
talents=1122322
spec=balance

covenant=venthyr
# soulbind=nadjia_the_mistblade:8,331586/269:6:0/331576/259:7:0/331579/271:8:0/254:7:0/331580/280:5:0/352366/272:7:0/352373
soulbind=theotar_the_mad_duke:9,336239/271:8:0/336140/280:5:0/336184/283:8:0/262:8:0/336245/263:5:0/351748/254:7:0/351750
# soulbind=general_draven:3,340159/271:8:0/319982/273:7:0/332755/254:7:0/284:8:0/332754/280:5:0/352365/259:7:0/352417
# conduits_available=261:7/262:8/263:5/264:7/265:7/266:8/267:5/268:7/269:6/270:7/273:7/274:7/275:7/276:7/280:5/284:8/257:6/258:6/259:7/260:6/254:7/255:7/256:6/271:8/272:7/283:8
renown=57

head=,id=186330,gem_id=187061,bonus_id=7189/6652/1472/6646
neck=,id=186291,bonus_id=7188/6652/7574/1485/6646
shoulder=,id=172255,bonus_id=6893/7461,drop_level=60,crafted_stats=49/40
back=,id=186289,bonus_id=7189/6652/1472/6646
chest=,id=186296,gem_id=187059,bonus_id=7186/6652/1459/6646
wrist=,id=186297,bonus_id=7189/6652/7574/1472/6646
hands=,id=186295,gem_id=187057,bonus_id=7189/6652/1472/6646
waist=,id=172320,gem_id=173128,bonus_id=7474/6649/6648/6935/7451/1559
legs=,id=179324,bonus_id=7354/7359/6652/1540/6646
feet=,id=178797,enchant_id=6211,bonus_id=7375/7359/6652/1540/6646
finger1=,id=178736,enchant_id=6168,bonus_id=7622/7359/6652/7575/1566/6646
finger2=,id=178869,enchant_id=6168,bonus_id=7389/7359/6652/7194/1540/6646
trinket1=,id=186423,bonus_id=7189/6652/1472/6646
trinket2=,id=179350,bonus_id=7603/7359/1550/6646
main_hand=,id=186405,enchant_id=6229,bonus_id=7188/6652/1485/6646

### Gear from Bags
#
# Hood of Refracted Shadows (226)
# head=,id=178817,bonus_id=7354/7359/6652/7194/1540/6646
#
# Passably-Forged Credentials (200)
# neck=,id=185954,bonus_id=6652/7574
#
# Draught of Deep Focus (225)
# neck=,id=178927,bonus_id=7086/6718/6647/6648/1522/6935
#
# Freshly Embalmed Jerkin (249)
# chest=,id=178744,enchant_id=6230,bonus_id=7592/7359/6652/1563/6646
#
# Loyal Kvaldir's Handwraps (226)
# hands=,id=186295,bonus_id=7189/6652/1472/6646
#
# Devourer Hide Belt (220)
# waist=,id=187380,bonus_id=6652/7576/7695/1492/6646
#
# Vision of Unending Growth (235)
# legs=,id=172318,bonus_id=7099/6758/6647/6649/1532
#
# Balance of All Things (235)
# legs=,id=172318,bonus_id=7107/6650/6648/6758/1532
#
# Ursoc's Fury Remembered (225)
# legs=,id=172318,bonus_id=7094/6718/6649/6650/1522
#
# Viscera-Stitched Footpads (223)
# feet=,id=178731,bonus_id=7599/7359/41/1537/6646
#
# Shard of Annhylde's Aegis (239)
# trinket1=,id=186424,bonus_id=7188/6652/1485/6646
#
# Skulker's Wing (226)
# trinket1=,id=184016,bonus_id=7187/6652/1498/6646
#
# Wakener's Frond (197)
# trinket1=,id=181457,bonus_id=6652/1472/5894/6646
#
# Instructor's Divine Bell (194)
# trinket1=,id=184842,bonus_id=6652/1472/5891/6646
#
# Tome of Insight (220)
# trinket1=,id=186156,bonus_id=6652/7695/1492/6646
#
# Ebonsoul Vise (226)
# trinket1=,id=186431,bonus_id=7189/6652/1472/6646
#
# Gnarled Staff of the Elder Shaman (213)
# main_hand=,id=186405,bonus_id=7186/6652/1459/6646
#
# Xav's Pike of Authority (229)
# main_hand=,id=178865,enchant_id=6229,bonus_id=7643/7359/6652/1543/6646
#
# Scithewood Scepter (236)
# main_hand=,id=178709,enchant_id=6229,bonus_id=7673/7359/6652/1550/6646
#
# Mawsworn Sentry's Cudgel of the Aurora (163)
# main_hand=,id=186146,bonus_id=7453/1706,drop_level=60
#
# Guarm's Lost Chew Toy (239)
# off_hand=,id=186418,bonus_id=7188/6652/1485/6646
```

**Comment by seriallos** [comment]
I'll take a closer look at this later (have to run in a minute) but it's probably IQD - it's common when using IQD that a small change in gear can adjust your total secondary stats which changes which IQD buff you get during bloodlust. The different buffs can result in dramatic swings in DPS.

There are no known issues with set bonuses at this time so it's 99% likely that IQD is causing the weirdness. Try swapping out IQD for another trinket and re-run the sims to see if that results in unexpected behavior. You can also run Quick Sims and then look for the IQD and Shard buffs/abilities to verify what's happening.

**Comment by himerope69** [comment]
Similar result, even without IQD.  It narrows the gap to ~200 dps, but still recommends no set bonus.  There's a fairly large ilevel difference on the two chests, but it's highly unlikely that 20 ilevels on one item is going to sim 200 dps over the set bonus. 

Moreover, running the set bonus set in quick sim shows no damage from the set bonus effect when you look at the breakdown of damage done.
![Capture](https://user-images.githubusercontent.com/32182820/128612012-edc2e6dd-066a-4be0-9d31-e40ef3b7865c.JPG)

**Comment by seriallos** [comment]
OK, had some more time to look at it. The set bonuses are powerful but they do scale based on the upgrade level of the gems - looks like the 36 item levels + the mastery IQD buff is better than the 213 chest with the base level of gems. However, upgrading the gems does make the 213 chest better. I'm not seeing any problems with SimC, you can verify that the set bonus is active in the sims in the Quick Sims below - I think you were overvaluing the set bonuses at a base level compared to a 36 item level upgrade.

To get a sense of the power of things, I started with a baseline - the 213 chest, no gem, eternal stats added (to match the 249 chest). I ran these all as Quick Sims so you can look at the reports to confirm that the Blood Link damage is there or not.

[Baseline (no set bonus, 213 ilevel chest, eternal stats) - 7,074 DPS](https://www.raidbots.com/simbot/report/hyot6Qd4QGqaph7Et2eDQJ)

[Baseline with set bonus - only adds Shard of Jaz which does not add DPS on its own - 7,375](https://www.raidbots.com/simbot/report/xaPxavEC7AycuYFkPUMGNV)

[249 chest - 7,554 DPS](https://www.raidbots.com/simbot/report/wgMRtfSgtcj7aHjCHEPLVX)

The higher ranks of shards results in pumping up the set bonus (here's a [top gear sim](https://www.raidbots.com/simbot/report/b8S3u4Q3oY6fL4QEBqndvh) playing with this)

Rank 1: 7,376 DPS
Rank 2: 7,542 DPS
Rank 3: 7,707 DPS
Rank 4: 7,870 DPS
Rank 5: 8,035 DPS

So as soon as the gems are rank 2, the 213 chest beats the 249 chest.
