### ISSUE TITLE
Top Gear saying no upgrades

### ISSUE THREAD

**Issue by Thereisone** [seriallos/raidbots-issues#303]
After opening my great vault I compared all the choices like I always do every reset, There is an item In the vault that I currently have equipped at 220, and it's an option in the vault for 252. Its main stat is easily an upgrade. The boot slot is also an upgrade but top gear seems to be bugged and not running enough sims or something.  

https://pastebin.com/5TBG54NW  There is the raw simc output.

**Comment by seriallos** [comment]
Can you link the URL of the actual sim?

Quick guess is that you have some other setting that is changing other things around (conduit item level override, gem/enchant replacement, shard replacement) that is causing the difference. To verify, I need to see the actual report, not just the SimC input.

When I run that input with default settings, it shows the boots and trinket as upgrades: https://www.raidbots.com/simbot/report/xkDm12TU87Y9tNX3hHJWjG

**Comment by Thereisone** [comment]
https://www.raidbots.com/simbot/report/i81vfUcdL8sAnpUPBBSuJg

**Comment by seriallos** [comment]
Your equipped gear has rank 3 or 4 Domination Shards which means the rank 3 set bonus but the sim is configured to "Replace Existing Gems" and you have rank 1 shards selected - this means that every combination will have the rank 1 shard set bonus which is substantially weaker than what's in your gear right now.
