### ISSUE TITLE
Let us manually pick a value on The Duke's Mad Tea

### ISSUE THREAD

**Issue by Zeilar** [seriallos/raidbots-issues#304]
**Is your feature request related to a problem? Please describe.**
Having it be random isn't ideal if you want to minmax the sims, which most people who are simming want to. Hence why you can override things like the Changeling and Cabalist's Hymnal trinkets.

**Describe the solution you'd like**
Add this setting somewhere, perhaps at the additional ones at the bottom?

**Describe alternatives you've considered**
At the very least a string we can copy and modify easily so people don't need to look this up all the time.

**Comment by seriallos** [comment]
You can override this in the Custom APL and SimC Options section:

e.g., `shadowlands.party_favor_type=haste` 

Full docs and other available options: https://github.com/simulationcraft/simc/wiki/ExpansionOptions#91---chains-of-domination-options

**Comment by Zeilar** [comment]
Thank you providing an alternative, still would've preferred to see it available in the UI however. Hopefully you'll put it on the ticket list still.
