### ISSUE TITLE
No Theotar's last rank buff selector

### ISSUE THREAD

**Issue by rufotamo** [seriallos/raidbots-issues#306]
Since last rank of Theotar's Souldbind, Party Favors, can be obtained. It would be great that the users could have a selector for each one of the stats you can get from it.

Since this  buff grants you a 3% of a single stat, it would  be amazing to simulate for each one of the stats to config our armor based on it.

Thanks!

**Comment by seriallos** [comment]
Check https://github.com/seriallos/raidbots-issues/issues/304 for the Custom APL string that can control this.
