### ISSUE TITLE
Bug with Felblade talent - Havoc DH

### ISSUE THREAD

**Issue by Kaptajnu** [seriallos/raidbots-issues#307]
When I try to sim anything with the talent Felblade, on my level 35 Havoc Demon Hunter, it bugs out and says:
"Player Kapblind could not find spell data for action felblade_damage" and the sim crashes.

Could anybody help me with this bug? 

Thanks!

**Comment by seriallos** [comment]
Characters below max level are not officially supported by Raidbots or SimC. Some classes/specs work better than others - it's up to SimC class module maintainers. In this case, I don't believe that DHs are well supported when below max level.
