### ISSUE TITLE
Top Gear only takes domination set bonus into account for equipped gear

### ISSUE THREAD

**Issue by thecakebandito** [seriallos/raidbots-issues#308]
**Describe the bug**
When simming top gear, only the dom socket pieces equipped will have their set bonus activated. 

**To Reproduce**
1. Simulate a character with two domination socket pieces, one equipped and one in the inventory.
2. Simulate again, with the pieces switched.
3. See significantly different results based on which piece is equipped.

**Expected behavior**
The two items in the sims below should sim very close together, but they don't as one doesn't have the set bonus activated. 

**Link a sim with the problem (if available)**

Compare these two sims:

https://www.raidbots.com/simbot/report/wPz7jwgXtsysZVT1P9qgE4
https://www.raidbots.com/simbot/report/rFajFG721GFeKP6GBUVry6

**Character or /simc input**

Paste your /simc input

**Screenshots**
![image](https://user-images.githubusercontent.com/16545486/129778055-40a08aa7-ad3d-4c62-9e22-76c548e59f64.png)

**Comment by seriallos** [comment]
Your equipped gear has Desolate Shard of Dyz (rank 3 shard) equipped but you have Shard of Dyz (rank 1 shard) selected in the Enhancements section. This means any gear with an empty socket will use the rank 1 shard resulting in the less powerful shard set bonus.

Re-running with Desolate Shard of Dyz selected shows a much closer sim where the only difference is the secondaries on the helm: https://www.raidbots.com/simbot/report/gJ6fPxRykhQjAuuDZhaTQc
