### ISSUE TITLE
The Nine Mythic Leather boots

### ISSUE THREAD

**Issue by Alyuwu** [seriallos/raidbots-issues#309]
It's either not simming with domination sockets/set bonus, or not simming with some stats from what I can see.

Using the exact same boots from heroic says it's a 300 dps increase over the mythic ones
https://www.raidbots.com/simbot/report/ucJN4CtKcgACJUKB2MR7HV

**Comment by seriallos** [comment]
That sim has the normal and heroic versions of the boots, not mythic - is that the sim you meant to link?

**Comment by seriallos** [comment]
That sim also doesn't have any Shards of Domination chosen down the in Enhancements section. If no shards are chosen, none will be added to empty sockets.

Reopen if you have a sim clearly showing the problem (ideally a very simple sim where only the boots are being compared, not a sim with lots of other things chosen)

**Comment by Alyuwu** [comment]
That was the incorrect sim, this is the one I meant to link
https://www.raidbots.com/simbot/report/w1X15bWNADetsb56thGcLr

**Comment by seriallos** [comment]
IQD gonna IQD.

Your equipped gear has you at 730 haste and 729 mastery. This means that on pull, IQD will proc the big haste buff.

Change the boots to lower level version, and you have 728 haste and 729 mastery. So on pull, IQD will proc the mastery buff.

That's the only difference between the sims - looks like big mastery IQD buff on pull is significantly more powerful than the stat difference on the items.

**Comment by Alyuwu** [comment]
So sims for iqd only go based off of your highest secondary stat, not the highest or second highest like ingame?

**Comment by seriallos** [comment]
During bloodlust is always uses the highest stat and provides a longer version of that buff. Sims always start with bloodlust. It picks between two random stats when not in bloodlust.

**Comment by Alyuwu** [comment]
Ah, I didn’t know that. Makes a lot more sense now. Ty
