### ISSUE TITLE
Different versions of the same buff are not shown in the "buff uptime" section

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#313]
**Describe the bug**
The trinket buff [Worthy](https://www.wowhead.com/spell=355794/worthy) is a static buff but can have different versions based on the highest stat. If more than one version is active during a sim the "buff uptime" section only counts and shows the version with the highest uptime.

**To Reproduce**
1. Check the report https://www.raidbots.com/simbot/report/2mWGMcnHoS9Jzgzw9asxNJ
2. See that the buff "Worthy" is shown as a constant buff.
3. Check the report https://www.raidbots.com/simbot/report/jnaPVTFdfTYkF4FaBj3pGX
4. See that the buff "Worthy" is only shown with a 67.9% uptime.
5. Check the detailed SimulationCraft report and see that there is actually a second "Worthy" buff with 32.08% uptime.

**Expected behavior**
The buff "Worthy" should be shown with 100% uptime in both reports.
Or at least it should show a second buff entry for the version with less uptime in the second report.

**Link a sim with the problem (if available)**
See repro steps above.

**Character or /simc input**
See repro steps above.

**Comment by seriallos** [comment]
I'll take another look at this but I think it may not be feasible to fix (if I recall the details correctly). There's some complexity with how the game tracks this buff (a single spell ID despite the different stats that can proc) and with how SimC tracks things internally. Changing the report to fix Worthy (by grouping on name, not ID) breaks a bunch of other stuff.

That said, I will take another look at some point to see if there might be a more clever solution.

**Comment by seriallos** [comment]
We'll see if this pops up again in Dragonflight. Not currently planned to fix.
