### ISSUE TITLE
Veng dh blind faith absurdly high sim

### ISSUE THREAD

**Issue by gougoutte** [seriallos/raidbots-issues#317]
**Describe the bug**

I sim my single target dps and it's over 44k. I think the problem is the versatility buff from the legendary is way too high. it should start from 0% and build to ~25% ish
**To Reproduce**
sim character winterlong on zul'jin with blind faith legendary

**Expected behavior**
sim probably around 6k dps

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name
US Zul'jin Winterlong
For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
Can you link a specific report?

My quick guess is that you have the sim configured with a high number of bosses and/or a very short timespan.

When I run a single target 5 minute sim I see about 4-5k DPS: https://www.raidbots.com/simbot/report/tMivza2SyQ2R1n9YDYPYrk

**Comment by seriallos** [comment]
There was a bug in SimC itself causing this. Should be fixed now.
