### ISSUE TITLE
Power Cord of Lethtendris : Affliction Warlock Legendary

### ISSUE THREAD

**Issue by morph4037** [seriallos/raidbots-issues#32]
Just a small bug it seems, I'm trying to use the "Top Gear" function and it's not registering [Power Cord of Lethendris](http://www.wowhead.com/item=132457/power-cord-of-lethtendris) at all when selecting the items for the gear sets. It shows as an option to click although I get asked for a second static legendary and at the end calculation screens the belt doesn't show up in the summary. Wish I could be more articulate with the issue, just hope it helps. 

Thanks.

**Comment by seriallos** [comment]
Can you provide the full SimC input you're using?

**Comment by morph4037** [comment]
[Warlock Gear.txt](https://github.com/seriallos/raidbots-issues/files/1374469/Warlock.Gear.txt)

There was a few changes, I had a set of legs and a helm in the original one. I'm still getting the same belt issue with this newer SimC input though.

**Comment by seriallos** [comment]
You don't have alternate pieces for your legendary legs or rings. You need a second pair of legs or a third ring to be able to be able to assemble a full set of gear that uses the Power Cord.
