### ISSUE TITLE
[BUG] Unbound Changling Icon/Image Issue

### ISSUE THREAD

**Issue by jeffcross** [seriallos/raidbots-issues#322]
This is not a big deal but I wanted to point it out. The icon shown in the report for Unbound Changling is incorrect. 

To reproduce this, sim a Shadow Priest (not sure if this shows up weird for other classes) with an Unbound Changling and see the icons that show up in the output. The tooltip shows the correct image but the image used for the report icon is incorrect.

Here's a link to a sim showing the issue: https://www.raidbots.com/simbot/report/hM9VtzyvZt8oVH9Gb2Z2FD

Here's a screenshot showing the issue using the same report linked above. You can see I have Unbound Changling and the Soulletting Ruby equipped.
![Screen Shot 2021-12-29 at 12 52 25 PM](https://user-images.githubusercontent.com/3952325/147694547-43d1ce42-f237-47c1-8d48-6295f2c12255.png)

Again, not a big deal but wanted to report the issue. Thank you for all that you do!

**Comment by jeffcross** [comment]
Looks like it is using this image for the icon: 

https://www.raidbots.com/static/images/icons/56/spell_animaardenweald_nova.png

I believe it should be using this icon:

https://www.raidbots.com/static/images/icons/56/inv_pet_spectralporcupinered.png

**Comment by seriallos** [comment]
There's a complex system of icon overrides that exists in WoW that I haven't reproduced on Raidbots. Wowhead does have it implemented which is why the tooltips are correct.

It's been on my list for a while but is a pretty low priority because it's not used in a ton of cases.

**Comment by jeffcross** [comment]
@seriallos Makes sense, man. Just wanted to point it out but looks to be a known issue. I'll close this out!

Thanks again for all you do! Keep up the good work!
