### ISSUE TITLE
Domination shards are disabled but still counted for combination number

### ISSUE THREAD

**Issue by Mirimes** [seriallos/raidbots-issues#326]
**Describe the bug**
I wanted to sim some gear from my bag but while not selecting anything raidbots says there are 127 combinations. When i try to add just a trinket the nuber of iteration is too big and i can't sim.
I tried to start the sim without selecting anything to see what those 127 combinations were and found out it compares all the shards possibilities even tho i unchecked the "Domination shards" option.

**To Reproduce**
- Have a character with 9.1 raid gear
- Have a trinket in the bag
- Try to sim current gear + trinket

**Expected behavior**
I expect that domination shards would not be part of the sim at all, so my gear is just 1 combination

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/ua1MXJ7dkVV2s7iL8egERt

**Character or /simc input**
```
# Mirimes - Beast Mastery - 2022-02-23 11:20 - EU/Runetotem
# SimC Addon 9.1.5-01
# Requires SimulationCraft 910-01 or newer

hunter="Mirimes"
level=60
race=draenei
region=eu
server=runetotem
role=attack
professions=mining=150/engineering=95
talents=2122213
spec=beast_mastery

covenant=night_fae
soulbind=niya:1,322721/140:7:1/342270/175:7:1/320687/173:8:1/157:8:1/320659/185:7:1/352502/282:7:1/352503
# soulbind=plasmasogni:2,319217/157:8:1/185:7:1/319211/140:7:1/283:7:1/319214/319191/253:7:1/352779/175:7:1/352786
# soulbind=korayn:6,
# conduits_available=183:8/185:7/189:7/192:8/224:7/252:8/251:8/140:7/188:7/199:7/223:8/226:7/253:7/178:7/181:7/282:7/175:7/157:8/173:8/283:7/166:8/170:7
renown=80

head=,id=186304,gem_id=187314,bonus_id=7188/6652/1485/6646
neck=,id=178927,gem_id=173128,bonus_id=7716/7451/6649/6647/1559/6935
shoulder=,id=186305,gem_id=187313,bonus_id=7188/6652/1485/6646
back=,id=186439,enchant_id=6202,bonus_id=7189/6652/1472/6646
chest=,id=186303,enchant_id=6214,gem_id=187318,bonus_id=7188/6652/1485/6646
shirt=,id=151116
tabard=,id=178336
wrist=,id=186365,bonus_id=7188/40/7574/1485/6646
hands=,id=186345,bonus_id=7188/40/1485/6646
waist=,id=186301,gem_id=187315,bonus_id=7188/6652/1485/6646
legs=,id=186307,bonus_id=7188/40/1485/6646
feet=,id=186343,enchant_id=6211,gem_id=187312,bonus_id=7188/6652/1485/6646
finger1=,id=186290,enchant_id=6170,bonus_id=7188/6652/7574/1485/6646
finger2=,id=178781,enchant_id=6166,bonus_id=7622/7359/6652/7574/1566/6646
trinket1=,id=186432,bonus_id=7188/42/1485/6646
trinket2=,id=186430,bonus_id=7188/41/1485/6646
main_hand=,id=186414,enchant_id=6196,bonus_id=7858/7753/1472

### Gear from Bags
#
# Gabbia Cranica di Ombracciaio (239)
# head=,id=186341,bonus_id=7188/6652/1485/6646
#
# Cotta di Maglia del Combattente Trionfante (242)
# chest=,id=178794,bonus_id=7590/7359/41/1556/6646
#
# Mitene dei Sussurri Ancestrali (239)
# hands=,id=186308,bonus_id=7188/6652/1485/6646
#
# Fibbia del Costrutto Cerimoniale (246)
# waist=,id=186338,bonus_id=7188/40/1485/6646
#
# Gambali Foderati del Lanciere di Aradne (239)
# legs=,id=186307,bonus_id=7188/6652/1485/6646
#
# Reliquia delle Distese Ghiacciate (246)
# trinket1=,id=186437,bonus_id=7188/1485/6646
#
# Proiettore di Fusione Direzionale (239)
# main_hand=,id=186413,bonus_id=7188/6652/1485/6646
```

**Screenshots**
![image](https://user-images.githubusercontent.com/86809157/155303178-d6b7d303-8934-40b4-8253-ea72d94c35e8.png)
![image](https://user-images.githubusercontent.com/86809157/155303283-62ef8ddf-401d-47ba-89c0-509eab92c228.png)
![image](https://user-images.githubusercontent.com/86809157/155303622-30186cc4-0104-44a6-9630-4d59b67a227d.png)

**Additional context**
There were no enhancement selected neither the replace existing gems/enchantsd checked

**Comment by Mirimes** [comment]
It worked, thanks :) but in the end i saw that the dom shards check doesn't do anything, is it correct? I would expect to see the old dom shards part in which i could select or unselect shards... it's not a part that i have interest in now, tbh, so to me it could be ok just resetting everything. Probably just a message in the page could work.

**Comment by seriallos** [comment]
I removed the UI in Top Gear for 9.2 since the shards are no longer useful for current content. I've also fixed the site so that any shards that were selected from pre-9.2 are no longer simulated. Should be all good now as long as the site gets reloaded.
