### ISSUE TITLE
Crystallic Sockets

### ISSUE THREAD

**Issue by FenrylSaylem** [seriallos/raidbots-issues#327]
Crystallic sockets get auto replaced with Haste/Versatility Clusters when enabling the "Replace" option.
But they cannot hold anything but the Spheroids.

Example:
https://www.raidbots.com/simbot/report/rtWUeVovagiq6WBTQ48BX3

**Comment by seriallos** [comment]
Fixed now. For the moment, these sockets will basically be ignored by Top Gear.

Thanks for the report!
