### ISSUE TITLE
Frame of the Flase Margrave Not Simming Correctly/Not Being Acknowledged 

### ISSUE THREAD

**Issue by sadbuni** [seriallos/raidbots-issues#328]
Hello,

I am currently simming my character and the sim seems to be blatantly wrong. 

https://www.raidbots.com/simbot/report/vgFdRPy5Qk6e9WbpUVQGAS

Shoulders are simming close to a +400 DPS increase when they should be around +100.

**Comment by seriallos** [comment]
Took me a while to see the problem too!

I'll look at adding a notification/warning when you're wearing armor of the wrong type.
