### ISSUE TITLE
Soul Treads enchant shows as "speed" in result list

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#330]
**Describe the bug**
The [Soul Treads](https://www.wowhead.com/spell=323609/soul-treads) boot enchant shows as "speed" in the top gear results list.

**To Reproduce**
1. Run a top gear sim with boots options.
2. Check result list

**Expected behavior**
Boots should be shown with "fall damage" or something similar.

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/kTX8BdnNWqfRcjo61Wbar5

**Screenshots**
![grafik](https://user-images.githubusercontent.com/116314/157894378-730f8222-9277-4090-8ca8-b9b531879ee5.png)

**Comment by seriallos** [comment]
Should be fixed now. I hadn't looked at this enchant since early in the alpha when it was actually a movement speed enchant!
