### ISSUE TITLE
Phearomones do not appear in DK Legendaries

### ISSUE THREAD

**Issue by Mazuake** [seriallos/raidbots-issues#331]
When you add Legis to sim your DK, Phearomones dont appear. In my Attachment it's just the helmets to present the problem. But the Legi don't show in Neck or Shoulders either.

Navigation: Top Gear -> Add Runecarving Legendaries (Crit/Mastery, 291 in my example).

![2022-03-27 15_08_44-Top Gear - Raidbots](https://user-images.githubusercontent.com/47572181/160282915-521c58b0-a038-4d2d-87ed-453d2283c7fc.png)

I hope the view infos are enough for you to understand the problem :) 
I give you my simc to, just in case you need it.
[simc.txt](https://github.com/seriallos/raidbots-issues/files/8357672/simc.txt)

Best Regards

**Comment by seriallos** [comment]
While the legendary power is named "Phearomones", the actual crafted items are named "Nightmare." Some of the crafted items have different names than the legendary power for flavor or to make more sense in different slots ("Wristguards of the Abomination" vs "Grips of the Abomination")

<img width="408" alt="image" src="https://user-images.githubusercontent.com/1010294/160295044-557778d7-0824-45e8-80a9-de87566fef07.png">
