### ISSUE TITLE
Survival Hunter has a Sim Issue with Moonlit Prism

### ISSUE THREAD

**Issue by Ashenovil** [seriallos/raidbots-issues#333]
In the Sim, Moonlit Prism stacks up with Kill Comand, this does not occur in the actual game, please fix

**Comment by seriallos** [comment]
Please report this to the SimC project as that contains the actual code/logic for simulation: https://github.com/simulationcraft/simc/issues

You might also have luck asking around in Hunter Discord as Hunter theorycrafters and SimC devs pay a bit more attention there.
