### ISSUE TITLE
Havoc DH Sim - Annihilation always up outside of Metamorphosis

### ISSUE THREAD

**Issue by gonzoinc** [seriallos/raidbots-issues#338]
**Describe the bug**
Annihilation is always up even though it is only supposed to be available during Metamorphosis

**To Reproduce**
Ran sim on my DH Alt and found Annihilation  was up for the entire default simc boss fight 5 min long, Annihilation  was being used even before the first Metamorphosis

**Expected behavior**
Annihilation   is only available during Metamorphosis

**Link a sim with the problem (if available)**
If you have a sim report that shows the problem, please provide the URL here
https://www.raidbots.com/simbot/report/xz6Nxec69fexvWTRsHwezG/simc

**Character or /simc input**
Default

**Comment by seriallos** [comment]
You have the Demonic talent which drops you into Demon Form after Eye Beam - this gives you more time available where you can cast Annihilation. You can see in the Sample Ability Log that Annihilation is only cast while Metamorphosis is up:

https://www.raidbots.com/simbot/report/xz6Nxec69fexvWTRsHwezG

If you still think there is an issue, the best place to report potential issues with the simulation is with the actual SimulationCraft project itself, not Raidbots. I don't do much work on the actual class modules, that's done by SimC devs: https://github.com/simulationcraft/simc
