### ISSUE TITLE
crafted necklaces do not show options for secondary stat when comparing gear

### ISSUE THREAD

**Issue by wafflelag** [seriallos/raidbots-issues#339]
When comparing gear and adding craftable items like Deadly Sinvyr Necklace (crit with second random/targetable secondary stat) or Quick Oxxein Necklace there is no (popup dropdown) choice for the second secondary stat.

**Comment by seriallos** [comment]
Should be fixed now. I just made a quick fix for now and Gear Compare will show both single stat and double stat options - the double stat options will just use the first state and ignore the second stat. But the basic functionality is in place now for those items that have one fixed stat and one dynamic stat.
