### ISSUE TITLE
Can't find any character for Bladefist/Kul-Tiras US server

### ISSUE THREAD

**Issue by LewNuhC** [seriallos/raidbots-issues#34]
Raidbots cant find the armory for any character I try to sim on the servers Bladefist/Kul-tiras US

**Comment by seriallos** [comment]
Can you provide some character names?

**Comment by LewNuhC** [comment]
Chupakhazra-Bladefist, Xervatez-Bladefist, Zogu-Bladefist, Udderlyholy-Bladefist

**Comment by seriallos** [comment]
Thanks for the extra info!

It looks like this is an issue on Blizzard's side (issue with the API that Raidbots uses but is not an issue with the Armory website itself). They know about it and are investigating so hopefully it clears up soon.

**Comment by seriallos** [comment]
Also, the simulation craft add-on should work without issue on the website as a workaround until Blizz gets the issue fixed on their side.

**Comment by LewNuhC** [comment]
Alright tyvm
