### ISSUE TITLE
Incorrect Fated Heroic Item Level

### ISSUE THREAD

**Issue by Luciiite** [seriallos/raidbots-issues#340]
**Describe the bug**
Heroic Fated items across all 3 raids are showing and simming as item level 297.

**To Reproduce**
Open Droptimizer and view items from Castle Nathria, Sanctum of Domination, or Sepulcher of the First Ones.

**Expected behavior**
Items from Heroic Fated raid should be item level 298.

**Comment by seriallos** [comment]
Do you have a /simc input or Armory link with a character that has one of these items? Game data from the dungeon journal indicates 297 which is why I used those values but I haven't seen any actual drops from a verified source.

**Comment by seriallos** [comment]
Got confirmation and also saw that Blizz updated the dungeon journal. This is now updated in Droptimizer.
