### ISSUE TITLE
Enforcer's Stun Grenade

### ISSUE THREAD

**Issue by JPearson4110** [seriallos/raidbots-issues#343]
Enforcer's Stun Grenade not showing correct values

my 288 ilevel in game showing +173 Vers raidbots showing at +89 vers

**Comment by seriallos** [comment]
Please provide a link to a sim report URL and/or input from the /simc addon and I can take a look.

The most likely thing is that it's a tooltip issue and not actually an issue in the actual simulation. More info on tooltips being out-of-date: https://github.com/seriallos/raidbots-issues/issues/288

**Comment by JPearson4110** [comment]
# Missedmark - Marksmanship - 2022-08-16 15:46 - US/Area 52
# SimC Addon 9.2.5
# Requires SimulationCraft 920-01 or newer

hunter="Missedmark"
level=60
race=pandaren
region=us
server=area_52
role=attack
professions=leatherworking=100/skinning=150
talents=1132233
spec=marksmanship

covenant=necrolord
# soulbind=plague_deviser_marileth:4,323074/323090/323081/323095/352109
# soulbind=emeni:5,342156/323921/324440/323918/351089/351094
soulbind=bonesmith_heirmir:10,326514/192:11:1/326507/175:11:1/326512/283:10:1/170:11:1/326572/188:10:1/350899/173:10:1/350936
# conduits_available=143:7/183:10/185:10/188:10/192:11/189:11/199:10/224:10/223:10/251:10/252:10/253:10/226:10/175:11/178:11/181:11/282:11/166:11/170:11/173:10/157:10/283:10
renown=80

head=,id=172325,gem_id=173130,bonus_id=8122/7882/8156/6647/6648/1588/6935
neck=,id=180115,gem_id=173130,bonus_id=7359/6652/7580/7798/1586/6646
shoulder=,id=188856,bonus_id=6652/7359/8765/8152/8270/1518/6646
back=,id=142206,enchant_id=6204,bonus_id=7359/8286/8765/8136/8138/6652/3183/6646
chest=,id=188858,enchant_id=6230,bonus_id=6652/7359/8765/8153/8256/1518/6646
wrist=,id=172329,enchant_id=6222,gem_id=173127,bonus_id=7014/7882/8156/6648/6650/1588/6935
hands=,id=188861,bonus_id=6652/8764/8094/8154/1518
waist=,id=168983,bonus_id=7359/40/7579/8765/8136/8137/8268/3142/6646
legs=,id=188860,bonus_id=8116/7770/6652/7359/8155/1492
feet=,id=168982,enchant_id=6211,bonus_id=6652/8765/8136/8137/8269/3145/6646
finger1=,id=142171,enchant_id=6168,bonus_id=8281/8765/6652/7579/7749/7578/3167/6646
finger2=,id=178872,enchant_id=6168,bonus_id=7800/7359/6652/7578/1592/6646
trinket1=,id=186432,bonus_id=8758/6652/1537/6646
trinket2=,id=109996,bonus_id=7359/6652/8765/8270/3183/6646
main_hand=,id=185783,enchant_id=6196,bonus_id=7828/7359/42/1595/6646

### Gear from Bags
#
# Lavalink Helm (288)
# head=,id=109983,bonus_id=7359/8253/8765/8136/8116/6652/7578/3173/6646
#
# Shadowsteel Facecage (291)
# head=,id=186341,bonus_id=8758/8118/8116/6652/7579/1537/6646
#
# Cabochon of the Infinite Flight (288)
# neck=,id=185820,bonus_id=8281/8765/7359/6652/7578/1605/6646
#
# Amulet of the Last Guardian (288)
# neck=,id=142207,bonus_id=8281/8765/6652/7578/7749/3167/6646
#
# Godstalker's Pauldrons (285)
# shoulder=,id=188856,bonus_id=6652/8765/8266/8152/1505
#
# Godstalker's Pauldrons (278)
# shoulder=,id=188856,bonus_id=6652/7359/7786/8152/1498
#
# Drape of Titanic Dreams (288)
# back=,id=185781,enchant_id=6204,bonus_id=8281/8765/8136/8138/7359/42/1605/6646
#
# Duplicating Drape (288)
# back=,id=185843,bonus_id=8281/8765/8136/8138/7359/6652/1605/6646
#
# Confiscated Bracers of Concealment (288)
# wrist=,id=185816,bonus_id=8281/8765/8136/8138/7359/6652/7579/1605/6646
#
# Tortured Assistant's Bindings (278)
# wrist=,id=178767,bonus_id=7800/8136/8138/7359/6652/7579/1592/6646
#
# Gavel Pounders (288)
# hands=,id=185794,bonus_id=8267/8765/8136/8117/7359/6652/1605/6646
#
# Tactical Wildfire Battlegear (291)
# waist=,id=172328,bonus_id=7015/7882/8156/6649/6647/1588/6935
#
# Clasp of Waning Shadow (278)
# waist=,id=178700,bonus_id=7786/8136/8137/7359/6652/7579/1592/6646
#
# Mekgineer's Utility Belt (288)
# waist=,id=169060,bonus_id=7359/6652/7579/8267/8765/8136/8137/3139/6646
#
# Clasp of Unity (265)
# waist=,id=190466,bonus_id=6652/7579
#
# Striders of Restless Malice (278)
# feet=,id=178745,enchant_id=6212,bonus_id=7786/8136/8137/7359/6652/1592/6646
#
# Rylakstalker's Treads (291)
# feet=,id=172323,enchant_id=6211,bonus_id=7010/7882/8156/6649/6647/1588
#
# Doomstride Footguards (285)
# feet=,id=142132,bonus_id=8266/8765/6652/7749/8136/8137/3164/6646
#
# Rebooting Bit Band (288)
# finger1=,id=168977,bonus_id=7359/6652/7578/8281/8765/3139/6646
#
# Bloodoath Signet (272)
# finger1=,id=178871,bonus_id=7359/6652/7579/7798/1586/6646
#
# Logic Loop of Maintenance (288)
# finger1=,id=169076,bonus_id=7359/6652/7579/8281/8765/3139/6646
#
# Seal of the Panoply (278)
# finger1=,id=185840,enchant_id=6168,bonus_id=7800/7359/6652/7578/1595/6646
#
# Dreadfire Vessel (272)
# trinket1=,id=184030,bonus_id=8763/6652/1537/6646
#
# Miniscule Mailemental in an Envelope (288)
# trinket1=,id=185846,bonus_id=8267/8765/7359/6652/1605/6646
#
# So'leah's Secret Technique (262)
# trinket1=,id=190958,bonus_id=7781/7359/6652/1579/6646
#
# Enforcer's Stun Grenade (288)
# trinket1=,id=110017,bonus_id=7359/6652/8267/8765/3173/6646

### Weekly Reward Choices
#
# Self-Repairing Cuisses
# legs=,id=168974,bonus_id=7359/6652/8258/8765/8136/8116/3155/6646
#
# Logic Loop of Synergy
# finger1=,id=169156,bonus_id=7359/6652/7579/8286/8765/3155/6646
#
# Streamslither Chestguard
# chest=,id=109887,bonus_id=7359/8258/8765/8136/8116/6652/3189/6646
#
# Oscillating Ouroboros
# finger1=,id=186376,bonus_id=8758/6652/7580/1537/6646
#
# Aradne's Lancer Legguards
# legs=,id=186307,bonus_id=8758/40/8118/8116/1537/6646
#
# Greaves of Extermination
# feet=,id=186306,bonus_id=8758/6652/8118/8137/1537/6646

**Comment by seriallos** [comment]
It's an issue with Wowhead's tooltip. It's fine in the sim.

https://www.raidbots.com/simbot/report/8o6i3ZyZ4E71AexN4Bn4v1/simc

<img width="370" alt="image" src="https://user-images.githubusercontent.com/1010294/185011556-69c3f650-1094-4a62-84bb-ecf402fa7ff3.png">
