### ISSUE TITLE
Missed a nerf update

### ISSUE THREAD

**Issue by MrFirus** [seriallos/raidbots-issues#345]
The jeweled signet of melandrus was recently nerfed but still shows as unnerfed when trying to sim

**Comment by seriallos** [comment]
It's properly updated in the sim (this commit grabbed the hot fixes after the change went live: https://github.com/simulationcraft/simc/commit/ec1451545909b3cadd8da535757cd75a59800c3e)

Tooltips might not be up-to-date. Those are from Wowhead which is separate from SimC.

It's still a very good ring post-nerf for some classes/specs (rogues, ferals).

A bit more info on tooltips being out-of-date: https://support.raidbots.com/article/17-a-tooltip-is-wrong-is-the-sim-wrong
