### ISSUE TITLE
Droptimizer recommends 265-Set-pieces - owning 265 and 272 allready

### ISSUE THREAD

**Issue by Chesslion** [seriallos/raidbots-issues#346]
https://www.raidbots.com/simbot/report/pWQzMhXVsrtRUS7YfYkhrc

Droptimizer recommends 265er-Set-pieces, but my Warlocks owns 265-set-chest and 272-set-shoulder allready.

**Comment by seriallos** [comment]
Not quite sure what's going on here - my guess is that the Cleave Add fight style isn't super well supported by the Destro Lock SimC module. 

Running Patchwork is less surprising where it's not dropping the set bonus: https://www.raidbots.com/simbot/report/dS5aaHEGpRCkC229E92QN3

Different modules have different levels of support for fight styles. Patchwerk is always going to be supported but others will be a question mark. I suggest asking around in your class Discord to see if anyone there knows more.
