### ISSUE TITLE
Is Dungeon Slice profile includes Season 4's Bounty stats?

### ISSUE THREAD

**Issue by Voxxel** [seriallos/raidbots-issues#348]
I wonder if I can sim my character for M+ on Raidbots properly. 
The S4's mythic+ addition, "Bounty: [stats]" that we choose at the start of a dungeon is largely modifies the outcome. Is it included silently (best stat for every spec) in the Dungeon Slice profile for Top Gear maybe? I don't see any way to choose the starting secondary stat in the option but for example picking the haste buff only at the start instantly adds 2% haste - so this Bounty makes a big difference in M+ stat weighting. 

Can you include at least the initial Bounty values into the M+ profile (Dungeon Slice) please - if it's not included already, silently? Is Dungeon Slice beta should be used for measuring M+ performance or what other profile do you recommend for it?

**Comment by seriallos** [comment]
DungeonSlice is a generic "M+ like" simulation that has sections of trash and bosses - it does not simulate any specific dungeon or affix. There's a more detailed explanation of exactly what it simulates here: https://medium.com/raidbots/mythic-simming-with-dungeon-slice-68a834880975 (this article is a bit older and some of the timings have changed - but the basic idea is still correct).

To get a sense of which bounty is best for your character, you can use this snippet in Raidbots Advanced mode: https://gist.github.com/seriallos/cc3e877a744090847a3847e9a00826b0

There's no single best method to sim M+ - it's a complicated topic and your best bet will be to check out your class Discord for best practices / pitfalls / etc: https://www.wowhead.com/discord-servers#class-discord-servers
