### ISSUE TITLE
Arcane mage sims

### ISSUE THREAD

**Issue by Kev2236** [seriallos/raidbots-issues#352]
So basically if I sim arcane mage it only casts Frostbolt the entire 5mins of the sim. I tried simming on Top Gear and on Quick Sim with same results.

I am using the latest SimulationCraft addon, it seems to correctly recognize the talents I am using, but only casts Frostbolts.

I also get the following error related to my trinket: "Centaurí missing 'use_item' action for item "moonlit_prism" (slot=trinket2)
Disable this warning by adding 'use_item' actions into the action priority list for the actor(s), or add "use_item_verification=0" to your list of options passed to Simulationcraft."

If you need any more information please let me know. Thanks

![image_2022-10-26_154331540](https://user-images.githubusercontent.com/105082779/198144095-281f93b3-ac8d-4c1b-aee6-560ab297f67c.png)

**Comment by seriallos** [comment]
SimC does not have an APL for arcane yet. It's being worked on but may not work until Dragonflight.

For more info, check your class Discord.
