### ISSUE TITLE
Top Gear no longer runs after Dragonflight patch.

### ISSUE THREAD

**Issue by MarshallBuhl** [seriallos/raidbots-issues#353]
**Describe the bug**
When I try to do a gear comparison between two pieces in the same slot, I get:
 "Top Gear requires at least two combinations. Make sure to select some additional items, enhancements, or talents."  I have this issue on all of my characters.  In this particular case, I was trying to compare my wrist pieces.

**To Reproduce**

**Expected behavior**
I expect the simulations to run, but they wont.

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

=====================================================
```
# Fossil - Arcane - 2022-10-29 12:02 - US/Medivh
# SimC Addon 10.0.0-1
# WoW 10.0.0.46340, TOC 100000
# Requires SimulationCraft 1000-01 or newer

mage="Fossil"
level=60
race=gnome
region=us
server=medivh
role=spell
professions=alchemy=175/herbalism=150
spec=arcane

talents=B4DAU3BjZ/IAySQ6AmAmsjvQ+JQgWikIJFg0OQiIiIhEgWChkAAAAAAAAAAAAQSSSIhkkA

# Saved Loadout: Arcane Mage - Mythic+
# talents=B4DAU3BjZ/IAySQ6AmAmsjvQ+JQgWikIJFg0OQiIiIhEgWChkAAAAAAAAAAAAQSSSIhkkA
# Saved Loadout: Arcane Mage - Raid
# talents=B4DAU3BjZ/IAySQ6AmAmsjvQ+JQgWikIJFg0OQiIiIhEgWChkAAAAAAAAAAAAQSSSIhkkA

covenant=kyrian
soulbind=pelagos:7,328266/34:8:1/328261/48:9:1/328265/40:8:1/26:8:1/328257/51:8:1/351146/61:8:1/351149
# soulbind=kleia:13,329791/51:8:1/334066/29:8:1/328258/45:8:1/26:8:1/329781/40:8:1/351488/283:9:1/351491
# soulbind=forgelite_prime_mikanikos:18,
# conduits_available=17:8/18:8/21:8/32:8/36:8/51:8/53:8/55:8/249:8/40:8/20:8/30:8/34:8/23:8/29:8/58:8/26:8/45:8/48:9/61:8/283:9
renown=80

head=,id=190620,bonus_id=43/7578/8133/8116/1531/6646
neck=,id=190635,bonus_id=8115/6652/7579/1491
shoulder=,id=190346,bonus_id=8111/7957/6652/1478
back=,id=190605,bonus_id=8113/6652/1485
chest=,id=190341,enchant_id=6265,gem_id=189731,bonus_id=8115/7947/6652/1491
shirt=,id=2575
tabard=,id=65906
wrist=,id=190348,enchant_id=6220,bonus_id=8115/7933/6652/7579/1491
hands=,id=190343,enchant_id=6205,bonus_id=8115/6652/1491
waist=,id=190464,bonus_id=6652/7578
legs=,id=190345,bonus_id=8114/6652/1488
feet=,id=184127,bonus_id=6652/8133/8137/1570/6646
finger1=,id=190632,enchant_id=6168,bonus_id=8115/6652/7579/1491
finger2=,id=188053,enchant_id=6168,bonus_id=6652/7579/8093/1492
trinket1=,id=190726,bonus_id=8142/6652/1488
trinket2=,id=190374,bonus_id=6652
main_hand=,id=192429,bonus_id=8115/6652/1491

### Gear from Bags
#
# Lucky Fishing Hat (22)
# head=,id=19972
#
# Wristwraps of Anguish (285)
# wrist=,id=186355,bonus_id=6652/7578/8133/8138/1531/6646
#
# Nat Pagle's Extreme Anglin' Boots (22)
# feet=,id=19969,enchant_id=18
#
# Nat's Lucky Fishing Pole (12)
# main_hand=,id=45858

# Checksum: 664f4b4e
```
=====================================================
**Screenshots**
![image](https://user-images.githubusercontent.com/6042843/198841568-7620ff33-7144-43f7-89d3-badfa077be45.png)

**Additional context**

**Comment by seriallos** [comment]
Hmm, I'm not able to reproduce that in my own tests. There might be some crufty data that I didn't properly clean up in the transition to Dragonfilght code.

Two things to try:

- Does it work in a different browser that you don't usually use?
- Try the Reset tool to get back into a clean state: https://www.raidbots.com/reset
