### ISSUE TITLE
Unable to sim top gear protection warrior

### ISSUE THREAD

**Issue by Frogger1314** [seriallos/raidbots-issues#356]
**Describe the bug**
Attempting to sim Top Gear as a prot warrior throws error: "Invalid SimC Input:
Error: Actor 'Tastytwinkie': Player 'Tastytwinkie' unable to create action: dragon_roar".

Note that "Dragon Roar" is now "Thunderous Roar" so perhaps that's where the issue lies. I also did not have that talent selected, so it didn't even appear in the simc string output.

**To Reproduce**
1. Copy simc string from addon as protection warrior.
2. Go to Top gear and input string.
3. Select great vault items.
4. Click "Find Top Gear".
5. Error occurs

**Expected behavior**
Go through top gear process as normal, dragon roar should no longer be an option at all, and should not affect any builds without the new thunderous roar talent.

**Link a sim with the problem (if available)**

N/A, cannot sim it at all

For "Load from SimC Addon":

`#` Tastytwinkie - Protection - 2022-11-01 11:20 - US/Proudmoore
`#` SimC Addon 10.0.0-1
`#` WoW 10.0.0.46366, TOC 100000
`#` Requires SimulationCraft 1000-01 or newer

warrior="Tastytwinkie"
level=60
race=human
region=us
server=proudmoore
role=tank
professions=blacksmithing=100/mining=150
spec=protection

talents=BkEAU3BjZ/IAySQ6AmAmsjvQ+JgAAAAASSSkkQSJpkgWBRgQRiElkEgAAtQSCIQIAAAAAAAABAAlG

`#` Saved Loadout: Prot ST
`#` talents=BkEAU3BjZ/IAySQ6AmAmsjvQ+JgAAAAASSSkkg0SKCKNEhIUEClkEgIA0CJJgAhAAAAAAAARAAoUaA
`#` Saved Loadout: Prot M+
`#` talents=BkEAU3BjZ/IAySQ6AmAmsjvQ+JgAAAAASSSkkQSJpkgWBRgQRiElkEgAAtQSCIQIAAAAAAAABAAlG

covenant=kyrian
`#` soulbind=pelagos:7,328266/186:11:1/328261/5:11:1/328265/284:11:1/8:11:1/328257/154:11:1/351146/49:11:1/351149
`#` soulbind=kleia:13,329791/334066/329784/329779/351489
soulbind=forgelite_prime_mikanikos:18,333950/50:11:1/331609/8:11:1/331726/5:11:1/27:11:1/333935/52:11:1/352186/283:11:1/352188
`#` conduits_available=11:11/12:11/14:11/50:11/52:11/64:11/154:11/169:11/186:11/284:11/8:11/9:11/13:11/191:11/5:11/7:11/10:11/27:11/49:11/283:11
renown=80

head=,id=188942,bonus_id=6652/8764/8094/8151/1518
neck=,id=178927,gem_id=173128,bonus_id=8130/7882/8156/6649/6648/1588/6935
shoulder=,id=188941,bonus_id=6652/8759/8095/8152/1524
back=,id=199921,enchant_id=6202,bonus_id=7359/8286/8765/8136/8138/6652/3155/6646
chest=,id=185784,enchant_id=6214,bonus_id=8765/8136/8116/7359/6652/8256/1615/6646
wrist=,id=189777,enchant_id=6222,bonus_id=6652/7578/8759/8132/8138/1550/6646
hands=,id=188937,enchant_id=6210,bonus_id=6652/8272/7359/8765/8154/1524
waist=,id=169057,gem_id=173128,bonus_id=6652/7580/8765/8136/8137/8270/3149/6646
legs=,id=189778,bonus_id=8759/6652/8132/8116/1550/6646
feet=,id=171413,enchant_id=6207,bonus_id=6969/6649/6650/8156/7882/1588
finger1=,id=169158,enchant_id=6166,gem_id=173128,bonus_id=6652/8765/8284/3149/6646/7580
finger2=,id=169159,enchant_id=6166,gem_id=173128,bonus_id=6652/8765/8284/3149/6646/7580
trinket1=,id=186438,bonus_id=8761/6652/1524/6646
trinket2=,id=142167,bonus_id=8765/6652/7749/8270/3177/6646
main_hand=,id=168963,enchant_id=6229,bonus_id=7359/6652/8765/8214/3149/6646
off_hand=,id=185811,bonus_id=8765/7359/6652/8228/1615/6646

`#``#``#` Gear from Bags
`#`
`#` Helm of Phantasmal Scars (288)
`#` head=,id=142126,bonus_id=8253/8765/6652/7578/7749/8136/8116/3167/6646
`#`
`#` Charm of Eternal Winter (304)
`#` neck=,id=183040,bonus_id=8759/6652/7578/1576/6646
`#`
`#` Cartel Xy's Proof of Initiation (291)
`#` neck=,id=189827,bonus_id=8758/6652/7580/1537/6646
`#`
`#` Perfectly-Forged Credentials (226)
`#` neck=,id=187552,bonus_id=6652/7574
`#`
`#` Wine-Stained Mantle (288)
`#` back=,id=142215,bonus_id=8281/8765/41/7749/8136/8138/3167/6646
`#`
`#` Drape of Titanic Dreams (288)
`#` back=,id=185781,bonus_id=8281/8765/8136/8138/7359/6652/1605/6646
`#`
`#` Deathmaker (291)
`#` back=,id=173242,enchant_id=6202,bonus_id=6964/7882/8156/6648/6649/1588
`#`
`#` Ashjra'kamas, Shroud of Resolve (155)
`#` back=,id=169223,bonus_id=6591/1472
`#`
`#` Breastplate of the Infinite Infantry (291)
`#` chest=,id=188938,enchant_id=6214,bonus_id=6652/8758/8094/8153/1511
`#`
`#` Airborne Abductor's Vambraces (304)
`#` wrist=,id=186316,bonus_id=8759/6652/7579/8132/8138/1550/6646
`#`
`#` Painbringer Waistguard (291)
`#` waist=,id=171418,gem_id=173127,bonus_id=6962/6647/6649/6935/8156/7882/1588
`#`
`#` Legplates of the Infinite Infantry (291)
`#` legs=,id=188940,bonus_id=6652/7749/8765/8155/8254/1511/6646
`#`
`#` Greaves of Acid Resistance (304)
`#` feet=,id=169055,enchant_id=6207,bonus_id=7359/6652/8272/8765/8136/8137/3155/6646
`#`
`#` Greaves of Acid Resistance (288)
`#` feet=,id=169055,bonus_id=7359/8267/8765/8136/8137/6652/3139/6646
`#`
`#` Ritualist's Treasured Ring (304)
`#` finger1=,id=183037,bonus_id=8759/6652/7578/1576/6646
`#`
`#` Seal of Darkshire Nobility (288)
`#` finger1=,id=142171,enchant_id=6166,bonus_id=8765/6652/7578/7749/7579/8281/3167/6646
`#`
`#` Scars of Fraternal Strife (298)
`#` trinket1=,id=188253,bonus_id=6652/8764/1537/6646
`#`
`#` Salvaged Fusion Amplifier (278)
`#` trinket1=,id=186432,bonus_id=8757/6652/1524/6646
`#`
`#` Codex of the First Technique (262)
`#` trinket1=,id=185836,bonus_id=7781/7359/6652/1579/6646
`#`
`#` Cosmic Aspirant's Medallion (242)
`#` trinket1=,id=186966,bonus_id=7485/1556/6646
`#`
`#` Enforcer's Stun Grenade (304)
`#` trinket1=,id=110017,bonus_id=7359/6652/8272/8765/3189/6646
`#`
`#` Remote Guidance Device (288)
`#` trinket1=,id=169769,bonus_id=42/8267/8765/3139/6646
`#`
`#` Faulty Countermeasure (272)
`#` trinket1=,id=137539,bonus_id=6652/7749/7784/3151/6646
`#`
`#` Cosmic Gladiator's Eternal Aegis (249)
`#` trinket1=,id=188775,bonus_id=7534/1521/6646
`#`
`#` Cosmic Aspirant's Insignia of Alacrity (242)
`#` trinket1=,id=186942,bonus_id=7492/1556/6646
`#`
`#` Gavel of the First Arbiter (311)
`#` main_hand=,id=189862,enchant_id=6228,bonus_id=6652/8159/8762/1550/6646
`#`
`#` Peon's Mining Pick (43)
`#` main_hand=,id=116913
`#`
`#` Jaithys, the Prison Blade (298)
`#` main_hand=,id=186410,enchant_id=6229,bonus_id=6652/7748/8764/1537/6646
`#`
`#` Blacksmith Hammer (1)
`#` main_hand=,id=5956
`#`
`#` Beacon of Hope (36)
`#` off_hand=,id=9393,bonus_id=6710,drop_level=30

`#``#``#` Weekly Reward Choices
`#`
`#` Terestian's Signet Ring
`#` finger1=,id=142172,bonus_id=7359/8286/8765/6652/7578/3183/6646
`#`
`#` Logic Loop of Division
`#` finger1=,id=169157,bonus_id=7359/8286/8765/6652/7578/3155/6646
`#`
`#` Inescapable Dread
`#` trinket1=,id=142161,bonus_id=7359/8272/8765/42/3183/6646
`#`
`#` Infinity's Last Bulwark
`#` off_hand=,id=186416,bonus_id=8757/6652/1524/6646
`#`
`#` Disintegration-Proof Waistband
`#` waist=,id=186317,bonus_id=8756/6652/7575/8131/8137/1511/6646

`#` Checksum: a403f3d1

**Screenshots**

![issue](https://user-images.githubusercontent.com/1490818/199271074-f7a1b310-6940-4843-92f4-a657c129b274.PNG)

**Additional context**

I know prepatch is full of bugs, so take your time :) Also, I escaped the pound signs in the simc string for better readability, it comes out properly from the addon

**Comment by seriallos** [comment]
Prot warrior hasn't been updated in SimC. I suggest keeping tabs on the warrior Discord for any updates as they will be tracking individual specs more closely.
