### ISSUE TITLE
Is SimC using the correct stats?

### ISSUE THREAD

**Issue by MarshallBuhl** [seriallos/raidbots-issues#357]
**Describe the bug**
I think this or a similar bug was reported and the discussion was closed months ago  (#288).  This is a recent problem, because it wasn't doing this before the prepatch.  When I hover over a piece of gear in my WoW Character window, the stats are different from what Top Gear shows.  I use the SimC addon to paste in my configuration.  This is for gear I've had for months and happens on multiple toons.  I have also loaded my configuration from the Armory and get the same disagreement.

In the previous bug report, it was suggested that we use QuickSim and check "the Full HTML Report linked in the sidebar and find the item/spell/ability - you should be able to dig into a detailed table that will include all calculated aspects."

When I look at the Raw Input and the Original Addon Input, I see names and IDs of my gear, but nothing that say what the individual stats are.

**To Reproduce**

Use the SimC addon to copy your configuration.  Paste it into Top Gear (or any other tool).  Hover over an item displayed in the WoW character screen and note the stats.  Do the same in the Top Gear tool and you will see they are different.  You don't even need to run the Monte Carlo analysis.

**Expected behavior**

I expect the displayed stats to be the same in WoW and in Top Gear.

**Link a sim with the problem (if available)**

(https://www.raidbots.com/simbot/report/tHxsAfzWp5hFpUd7bpJBBu)

**Character or /simc input**

For "Load from Armory":

* Region: US
* Realm / Server: Medivh
* Character Name: Fossil

For "Load from SimC Addon":

```
# Fossil - Arcane - 2022-11-03 12:00 - US/Medivh
# SimC Addon 10.0.0-1
# WoW 10.0.0.46366, TOC 100000
# Requires SimulationCraft 1000-01 or newer

mage="Fossil"
level=60
race=gnome
region=us
server=medivh
role=spell
professions=alchemy=175/herbalism=150
spec=arcane

talents=B4DAU3BjZ/IAySQ6AmAmsjvQ+JQgWikIJFg0OQiIiIhEgWChkAAAAAAAAAAAAQSSSIhkkA

# Saved Loadout: Arcane Mage - Mythic+
# talents=B4DAU3BjZ/IAySQ6AmAmsjvQ+JQgWikIJFg0OQiIiIhEgWChkAAAAAAAAAAAAQSSSIhkkA
# Saved Loadout: Arcane Mage - Raid
# talents=B4DAU3BjZ/IAySQ6AmAmsjvQ+JQgWikIJFg0OQiIiIhEgWChkAAAAAAAAAAAAQSSSIhkkA

covenant=kyrian
soulbind=pelagos:7,328266/34:8:1/328261/48:9:1/328265/40:8:1/26:8:1/328257/51:8:1/351146/61:8:1/351149
# soulbind=kleia:13,329791/51:8:1/334066/29:8:1/328258/45:8:1/26:8:1/329781/40:8:1/351488/283:9:1/351491
# soulbind=forgelite_prime_mikanikos:18,
# conduits_available=21:8/30:8/36:8/40:8/51:8/53:8/17:8/18:8/20:8/32:8/34:8/55:8/249:8/23:8/26:8/29:8/58:9/45:8/48:9/283:9/61:8
renown=80

head=,id=190620,bonus_id=43/7578/8133/8116/1531/6646
neck=,id=190635,bonus_id=8115/6652/7579/1491
shoulder=,id=190346,bonus_id=8111/7957/6652/1478
back=,id=190605,enchant_id=6203,bonus_id=8113/6652/1485
chest=,id=190341,enchant_id=6265,gem_id=189731,bonus_id=8115/7947/6652/1491
shirt=,id=2575
tabard=,id=65906
wrist=,id=186355,enchant_id=6220,bonus_id=6652/7578/8133/8138/1531/6646
hands=,id=190343,enchant_id=6205,bonus_id=8115/6652/1491
waist=,id=190464,bonus_id=6652/7578
legs=,id=190345,bonus_id=8114/6652/1488
feet=,id=184127,enchant_id=6207,bonus_id=6652/8133/8137/1570/6646
finger1=,id=190632,enchant_id=6168,bonus_id=8115/6652/7579/1491
finger2=,id=188053,enchant_id=6168,bonus_id=6652/7579/8093/1492
trinket1=,id=190726,bonus_id=8142/6652/1488
trinket2=,id=190374,bonus_id=6652
main_hand=,id=192429,enchant_id=6228,bonus_id=8115/6652/1491

### Gear from Bags
#
# Lucky Fishing Hat (22)
# head=,id=19972
#
# Comfortable Slumberwraps (285)
# wrist=,id=184131,bonus_id=6652/7579/8133/8138/1570/6646
#
# Oracular Wrists (252)
# wrist=,id=190348,enchant_id=6220,bonus_id=8115/7933/6652/7579/1491
#
# Nat Pagle's Extreme Anglin' Boots (22)
# feet=,id=19969,enchant_id=18
#
# Nat's Lucky Fishing Pole (12)
# main_hand=,id=45858

# Checksum: 971177f7t
```

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
Sounds like you didn't look at the Full HTML Report. "Raw Input" and "Original Addon Input" are different and not useful for this purpose.

The link is in the sidebar of a Quick Sim:

![image](https://user-images.githubusercontent.com/1010294/199843856-19bdb9c2-aaf6-42ad-ae09-43ec061def8b.png)

Scroll down and open the Gear section

![image](https://user-images.githubusercontent.com/1010294/199843970-880786f5-08d4-4516-ae6d-4fa470d8296e.png)

Check the text stats (not the tooltip, those are from Wowhead)

![image](https://user-images.githubusercontent.com/1010294/199844152-d5ac4c76-7e59-49a7-ad83-683aeaa99136.png)

If there are differences, please provide screenshots from the game to indicate which items are incorrect and let me know what the right stats should be.

**Comment by MarshallBuhl** [comment]
I ran a Top Gear sim in which the pants showed as rare (blue) in WoW, but was epic (purple) in Top Gear.

**Comment by seriallos** [comment]
If there are differences, please provide screenshots from the game to indicate which items are incorrect so I can take a closer look

**Comment by MarshallBuhl** [comment]
It appears that the bug is in what is displayed on the screen--not what it used for the simulations.  I'm attaching screenshots of the WoW character screen and the simulation results.  The Top Gear character screen shows the wrist piece as an epic piece in the graphic, but shows it as blue in the tool tip.  It also shows stats as 28-Arm, 21-Agi, 31-Sta, 25-Haste, and 15-Mastery.  The game tooltip shows a blue piece with stats: 34-Arm, 24-Agi, 37-Sta, 31-Haste, and 18 Mastery.  In the Gear section of the full report, it uses the same values as the WoW tooltip shows of the character screen--not what the gear-selection screen in Top Gear shows.

So, the sims seem to be using the correct date.  It's just the UI that is messed up.  I have seen this problem with literally (not virtually!) dozens of items.

WoW screen shot:

![WoWScrnShot_111322_164457](https://user-images.githubusercontent.com/6042843/201546791-ce77eac3-1590-400c-b119-50e753f8cc5a.jpg)

Top Gear graphic screen shot:

![Screenshot 2022-11-13 16 44 43](https://user-images.githubusercontent.com/6042843/201546796-65828038-7d1a-4c9d-b86f-7bb080101cfc.png)

Top Gear gear data screen shot:

![Screenshot 2022-11-13 17 04 56](https://user-images.githubusercontent.com/6042843/201546823-797e03ab-6151-442f-b393-8ea3ba57221d.png)

**Comment by seriallos** [comment]
Right, that's precisely what is described in https://github.com/seriallos/raidbots-issues/issues/288 - this is an issue with Wowhead tooltips and is only a display issue. Raidbots and SimC do not use the tooltip data in the actual simulation.

**Comment by MarshallBuhl** [comment]
Thank you for that response.  It's good to know that the sims use the correct data.

Just so you know, I _love_ this service and use it many times a day.

**Comment by seriallos** [comment]
OK, this one _was_ my fault. Raidbots was using tooltips for beta, not live. Should be fixed now.
