### ISSUE TITLE
Warlock Demonology Spamming Shadow Bolt

### ISSUE THREAD

**Issue by kurayami-hina** [seriallos/raidbots-issues#358]
**Describe the bug**

When doing quick sim with demonology Warlock, the sim is spamming Shadow Bolt and is not using any other spell.

**To Reproduce**

* Go to the quick sim
* You can then either enter the /simc input or any warlock demonology character
* Run the sim with the base information ( don't change any settings )
* Wait for sim to run
* Sim will display low DPS and will only use Shadow Bolt 

**Expected behavior**

When running the sim, we should see higher DPS and warlock demonology should not just use Shadow Bolt

**Link a sim with the problem (if available)**

URL of a sim with the problem : https://www.raidbots.com/simbot/report/q8vAzdA7KjXCMvWrHMUr4o

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc) : EU
* Realm / Server : Hyjal
* Character Name : Sacasouri

For "Load from SimC Addon":

```
# Sacasouri - Demonology - 2022-11-07 02:07 - EU/Hyjal
# SimC Addon 10.0.0-1
# WoW 10.0.0.46455, TOC 100000
# Requires SimulationCraft 1000-01 or newer

warlock="Sacasouri"
level=60
race=worgen
region=eu
server=hyjal
role=spell

spec=demonology

talents=BoQAU3BjZ/IAySQ6AmAmsjvQ+BIJRiEINlIINJJkCAAAAAQCkAIRCJJSLJJIAAAAAAA

# Saved Loadout: icy veins
# talents=BoQAU3BjZ/IAySQ6AmAmsjvQ+BIJRiEINlIINJJkCAAAAAQCkAIRCJJSLJJIAAAAAAA

covenant=night_fae
# soulbind=niya:1,322721/220:7:1/342270/168:7:1/320687/162:7:1/320660
soulbind=tisserêves:2,319217/160:7:1/204:7:1/319211/205:7:1/283:7:1/319216/319191/206:7:1/352779/171:7:1/352786
# soulbind=korayn:6,
# conduits_available=220:7/214:7/208:7/201:7/202:7/203:7/204:7/205:7/206:7/207:7/211:7/212:7/174:7/168:7/144:7/171:7/221:7/162:7/283:7/222:7/160:7
renown=80

head=,id=188009,bonus_id=40/7579/8146/1472
neck=,id=178827,bonus_id=6805/6652/7578/1550/4785
shoulder=,id=190980,bonus_id=8109/6652/7955/1472
back=,id=185781,bonus_id=8278/8765/8136/8138/7359/6652/1595/6646
chest=,id=109903,bonus_id=7359/8247/8765/8136/8116/6652/3153/6646
wrist=,id=173249,bonus_id=7025/7882/8156/6649/6648/1588/6935
hands=,id=188008,bonus_id=43/8146/1472
waist=,id=190469,bonus_id=6652/7579
legs=,id=188010,bonus_id=6652/8146/1472
feet=,id=142148,bonus_id=7359/8264/8765/8136/8137/6652/3157/6646
finger1=,id=178824,bonus_id=6805/6652/7579/1550/4785
finger2=,id=178736,bonus_id=6805/6652/7579/1550/4785
trinket1=,id=110002,bonus_id=7359/6652/8264/8765/3163/6646
trinket2=,id=178772,bonus_id=6805/6652/1550/4785
main_hand=,id=168973,bonus_id=7359/8189/8765/40/1656/6646

### Gear from Bags
#
# Couronne de conservateur korthien (220)
# head=,id=186666,bonus_id=7695/6652/7578/1492/6646

# Checksum: e8b9d2bc
```

**Screenshots**

Here a screenshot showing the Shadow Bolt only sim : 
![image](https://user-images.githubusercontent.com/48050703/200206887-fa9fd32a-46f1-4842-9ace-3aba9d250aaf.png)

**Additional context**

**Comment by seriallos** [comment]
The Warlock module is not going to be updated for pre-patch. All effort from the SimC warlock volunteer developers is focused on level 70 Dragonflight content.

Best place for class/spec information is going to be your Class Discord. There's a pin in the #demonology channel indicating that SimC is not updated for pre-patch: https://discord.com/channels/146682622016356353/146683128411455488/1035191082696331274
