### ISSUE TITLE
Dracthyr sim ends with error trying to execute Fire Breath

### ISSUE THREAD

**Issue by brwilliams208** [seriallos/raidbots-issues#362]
Here is the message:

SimulationCraft 1000-01 for World of Warcraft 10.0.2.46658 Live (git build HEAD 13be81e607)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Non-channeling action fire_breath_damage for Player 'Ghidorasza' is trying to overwrite player-ready-event upon execute.

Possibly related to the fact that I can't execute empowered spells from an action bar in-game unless I use a macro? I'm using the canned sim, no custom script.

**Comment by seriallos** [comment]
Yeah, looks like there are some Evoker crashes in SimC right now. I would expect these to get looked at and resolved over the next couple of weeks.

Best place to report SimC crashes is directly on the SimC project: https://github.com/simulationcraft/simc/issues
