### ISSUE TITLE
Demonology warlock call dreadstalkers 

### ISSUE THREAD

**Issue by Raspbearry** [seriallos/raidbots-issues#366]
When running a quick sim as a demonology warlock, it is not accounting for call dreadstalkers ever being cast. The damage is not represented at all, on any quick sim fight style. 

**To Reproduce**
Run a quick sim as a demonology warlock

**Expected behavior**
Call dread stalker to be cast and damage to be seen caused by the summons units, the rest are working fine. 

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/3Ugi1yeorrdsogm8aLJcev

**Character or /simc input**

For "Load from Armory":

* Region - US
* Realm / Server - Windrunner
* Character Name - Lengwen

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
Do you have /simc input for your character? Looks like it might be a bug related to loading the character from Armory.

**Comment by Raspbearry** [comment]
I can definitely attempt it with a simc report when I get home from work

**Comment by seriallos** [comment]
Notified SimC devs about this and it looks like the lack of Tyrant in your build isn't handled well. Sounds like it should be fixable when they have some time.
