### ISSUE TITLE
bug with trinket : Gral's Discarded Tooth 

### ISSUE THREAD

**Issue by Eltorofuerte01** [seriallos/raidbots-issues#367]
**Describe the bug**
the proc damages of [Gral's Discarded Tooth] are not calculated on the simbot.

[Gral's Discarded Tooth](https://www.wowhead.com/item=192797?bonus=6652:1481:5865:8767&ilvl=379)

**Character or /simc input** 
https://www.raidbots.com/simbot/report/qEqHFhGt8WTmdT9ju6ugFe/simc

For "Load from Armory":

* EU
* Kirin Tor
* Eltorofuerte

**Comment by seriallos** [comment]
I'll pass this on to the SimulationCraft project. However, many world/quest trinkets won't end up being fully implemented since they usually are quickly replaced by M+/raid trinkets.
