### ISSUE TITLE
simc bug

### ISSUE THREAD

**Issue by LuxusDragnir** [seriallos/raidbots-issues#369]
**Describe the bug**

When I want to sim a stuff for my fury war, I copy/paste the text from the SimulationCraft addon but it infinity load, thing I have not when I want to sim from my sham or mage, only with my war I get this bug and when I asked to a guild mate to try with my text he can sim for me so I don't understand why I can't?

**Expected behavior**

What can I do to sim my items enchantement etc...

If you have a sim report that shows the problem, please provide the URL here
I don't know if it's gonna bug for you cause like I said, a guild mate can sim for my character without problem 
https://www.raidbots.com/simbot/topgear

**Character or /simc input**
```
# Gaaha - Fury - 2022-12-13 12:57 - EU/Hyjal
# SimC Addon 10.0.2-04
# WoW 10.0.2.46924, TOC 100002
# Requires SimulationCraft 1000-01 or newer

warrior="Gaaha"
level=70
race=tauren
region=eu
server=hyjal
role=attack
professions=blacksmithing=64/mining=80
spec=fury

talents=BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAABgSQQENhIBHQjIhkAJJhkQSkEJAJJJJpkWgEJJBAAAEA


head=,id=193663,gem_id=192987,bonus_id=7977/6652/7935/8816/1594/8767
neck=,id=193676,bonus_id=7977/6652/1594/8767/8783/8780
shoulder=,id=193802,bonus_id=7977/6652/8813/1594/8767
back=,id=193763,bonus_id=7977/6652/8815/1594/8767
chest=,id=190495,bonus_id=8836/8840/8902/8800,crafted_stats=36/32
tabard=,id=178120
wrist=,id=193813,bonus_id=7976/6652/7937/8815/1581/8766
hands=,id=192008,bonus_id=6652/1478/5858/8766
waist=,id=193650,bonus_id=7977/6652/7936/8814/1594/8767
legs=,id=193789,bonus_id=7978/7975/6652/8816,drop_level=70
feet=,id=193630,bonus_id=7977/6652/8814/1594/8767
finger1=,id=193696,bonus_id=7977/6652/7936/1594/8767
finger2=,id=193804,bonus_id=7977/6652/7936/1594/8767
trinket1=,id=193679,bonus_id=7978/7975/6652,drop_level=70
trinket2=,id=193719,bonus_id=7977/6652/1594/8767
main_hand=,id=193742,bonus_id=7977/40/1594/8767
off_hand=,id=193716,bonus_id=7977/6652/1594/8767

### Gear from Bags
#
# Chevalière griffée de la poussée de fièvre (292)
# finger1=,id=199017,bonus_id=7968/6652/7936/1769,drop_level=70

# Checksum: 6aa98d21
```

* Region EU, 
* Realm / Serveur: Hyjal
* Character Name : Gaaha

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

![image](https://user-images.githubusercontent.com/120467192/207311258-42bfc97c-0d48-47f0-9e99-11286ad80700.png)
If you copy/paste this text on a word page you can ctrl + click and you'll see the screen of the bug

**Comment by seriallos** [comment]
Try using the Reset tool: https://www.raidbots.com/reset

There are cases when a rare bug can cause issues with just one browser. Reset usually fixes it.
