### ISSUE TITLE
Paladin Tier Legs missing in Droptimizer

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#370]
**Describe the bug**
The Paladin Tier Legs are missing as possible loot from Sennarath in Droptimizer.

**To Reproduce**
1. Go to Droptimizer
2. Paste SimC input (see below)
3. Scroll down to leg items
4. Notice that only one item is listed, Tier legs are missing.
5. Run the sim.
6. Notice that tier legs are missing in the result too.

**Expected behavior**
Tier legs should be shown and simmed.

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/snSKjCZmhjr5S9TKVcNex9

**Character or /simc input**
https://pastebin.com/36FKRahP

**Comment by seriallos** [comment]
Thanks for the report. Should be fixed a little bit later today.
