### ISSUE TITLE
2-set bonus on primal storm sets not working

### ISSUE THREAD

**Issue by BrodyDowns** [seriallos/raidbots-issues#372]
The two set on the new primal storms sets, such as the [Shroud of Raging Tempests](https://www.wowhead.com/item-set=1523/shroud-of-raging-tempests), give 340 of your highest secondary stat. However, the tooltip on the RaidBots says 71. Additionally they do not sim any better than equivalent pieces of gear without the set so I suspect that bonus is not being added at all.

**Comment by seriallos** [comment]
On tooltips, see https://github.com/seriallos/raidbots-issues/issues/288

Unfortunately, non-raid set bonuses rarely get implemented in SimC. The devs are focused on raid/M+ endgame content/gear and the world quest/event items rarely match up.
