### ISSUE TITLE
Main and Off Hand show Legs as an option.

### ISSUE THREAD

**Issue by fiestysc** [seriallos/raidbots-issues#376]
Hi, when using top gear earlier today apparently my legs had turned into weapons :D 
![TopGear28122022](https://user-images.githubusercontent.com/121542926/209779237-1fb138e4-fd4f-4ca6-862b-e54901acc1d1.jpg)

**Comment by seriallos** [comment]
This is a bug in WoW itself. It happens when running /simc with your bank open.

Only current workaround is to move items into your bags, close your bank, and run /simc again.

Hopefully Blizzard fixes this bug soon.

**Comment by fiestysc** [comment]
Thank you :)
