### ISSUE TITLE
Exclude talent selection from generated combinations

### ISSUE THREAD

**Issue by Mitt-Rawmoney** [seriallos/raidbots-issues#381]
**Is your feature request related to a problem? Please describe.**
The Dragonflight talent tree changes make it difficult to sim talents due to the large number of possible combinations.

**Describe the solution you'd like**
In the create talent loadout screen, provide the option to exclude a talent from combinations produced by the generate combinations feature. This method should be fairly easy to implement and gives the user more control over what talents should be considered (or not).

**Comment by seriallos** [comment]
Already exists! Right-click an unselected node and it will exclude it.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/1010294/210158143-4fae3b52-c2a5-495d-8670-c6967bbfe2c3.png">
