### ISSUE TITLE
Survival hunter rotation issue

### ISSUE THREAD

**Issue by Rushinko** [seriallos/raidbots-issues#382]
**Describe the bug**
Harpoon is being cast on cooldown to proc terms of engagement, despite harpoon having a minimum range and this not being possible.

**To Reproduce**
Sim a survival hunter patchwork.
Look at the spell order
Harpoon is being cast on cooldown, even though it has a minimum range.

**Expected behavior**
Harpoon should not be cast more than once at the beginning of the fight

**Comment by seriallos** [comment]
Raidbots does not maintain the actual simulation software. For feedback or questions on the simulation, please open issues on the SimulationCraft project: https://github.com/simulationcraft/simc
