### ISSUE TITLE
Does not include the set bonus Enhancement Shaman

### ISSUE THREAD

**Issue by NevermindXP** [seriallos/raidbots-issues#383]
I have simmed my character including the Vault. The cloak is shown as the best upgrade, but the leg setitem with a much bigger Ilvl difference is even shown as a downgrade. Presumably the set bonuses are not included.

https://www.raidbots.com/simbot/report/rsuXjeR26pzsaMkhACRwua

![image](https://user-images.githubusercontent.com/120926138/210814079-7a206f07-b6d9-4175-834b-811f4b970fa6.png)
![image](https://user-images.githubusercontent.com/120926138/210814152-4c8b5f0e-3795-4fff-996f-4ad2ec11e143.png)

**Comment by NevermindXP** [comment]
im dumb

**Comment by seriallos** [comment]
Looks like Top Gear wasn't warning about missing enchants on legs. It should do that now which should help prevent this from happening!
