### ISSUE TITLE
Add Ruby Whelp Shell trinket options

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#386]
**Is your feature request related to a problem? Please describe.**
I'd like to easily configure which buffs my [Ruby Whelp Shell](https://www.wowhead.com/item=193757/ruby-whelp-shell) trinket uses.

**Describe the solution you'd like**
There should be a GUI option for it, similar to other trinket options.
Until it is fully figured out how the proc chances for each training level work I think it would be best if Raidbots allowed to input each proc weight, just like the SimulationCraft option is coded. Later that could maybe simplified to a training level input/selection.

**Describe alternatives you've considered**
Manually adding the option string to the "Custom APL and SimC Options" field works, but the user needs to know that this is possible and how the syntax needs to be.

**Additional context**
SimulationCraft option documentation ("dragonflight.whelp_training_weights"): https://github.com/simulationcraft/simc/wiki/ExpansionOptions
SimulationCraft commit that added the option: https://github.com/simulationcraft/simc/commit/e6d87e5a6502a13495e57734da5210ecdf140854
Explanation of the trinket: https://www.wowhead.com/news/how-to-train-your-ruby-whelp-shell-very-high-damage-or-stat-trinket-330947

**Comment by seriallos** [comment]
SimC devs are planning to make a friendlier option once they have done a bit more research. From discussions with them, this is fairly close (_probably_ days away) so I will be waiting until that is available as it's far more easily understood and less likely to cause confusion.

The weight based option is not nearly as intuitive and can easily be used to create scenarios that are not possible in the game (100% of an ability) so it will be left as an advanced feature that can be used in text only.

**Comment by cremor** [comment]
Options have been changed in SimulationCraft.
See https://github.com/simulationcraft/simc/blob/46e0220de192204d4ae3a04c3c6fc824af35f0c7/engine/player/unique_gear_dragonflight.cpp#L2972
and https://github.com/simulationcraft/simc/wiki/ExpansionOptions

**Comment by seriallos** [comment]
Yup, this is now added.
