### ISSUE TITLE
Shadowlands Enchantments

### ISSUE THREAD

**Issue by button1990** [seriallos/raidbots-issues#387]
Tooltips for Shadowlands Enchantments are showing as a larger number than in game.

Here is my report - https://www.raidbots.com/simbot/report/cEgyKfxVUAS8GSR3hZQwh3

Feet - Eternal Agility (I believe most other Enchantments are the same).

**Comment by seriallos** [comment]
It's an issue with Wowhead tooltips but not an issue in the sim: https://github.com/seriallos/raidbots-issues/issues/288

**Comment by button1990** [comment]
Ok thank you
________________________________
