### ISSUE TITLE
"copy and modify" button shows downgrades

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#388]
**Describe the bug**
An item with item level 418 is showing all item level options in the "copy and modify" button, even though it can't be upgraded ingame and all options are downgrades.

**To Reproduce**
1. Go to Top Gear
2. Import the /simc addon input from below.
3. See "copy and modify" button options on the 418 chest.

**Expected behavior**
It should not show any item level downgrade options - just the convert with catalyst option.

**Character or /simc input**
https://pastebin.com/2yx1Qc8s

**Screenshots**
![grafik](https://user-images.githubusercontent.com/116314/214363685-3ddf3aae-ca5d-41ee-aacb-33a0e327716c.png)

**Comment by seriallos** [comment]
What does that item tooltip look like in-game? Can you grab a screenshot?

**Comment by cremor** [comment]
Sure:
![grafik](https://user-images.githubusercontent.com/116314/214369717-ed5310d3-c33a-4a90-b636-91fcdfa0bcf2.png)

**Comment by seriallos** [comment]
Where did it come from?

It has a really weird bonus ID that indicates it is upgrade level 14 when the maximum upgrade level is 13. Is that from the vault?

**Comment by cremor** [comment]
Yes, it was from the vault.

**Comment by seriallos** [comment]
OK, this should be fixed later today when I deploy the updated game data for 10.0.5
