### ISSUE TITLE
Quick Sim Fury Warrior Error for Recklessness / Avatar Usage

### ISSUE THREAD

**Issue by EndlessCoffeeAddict** [seriallos/raidbots-issues#389]
https://www.raidbots.com/simbot/report/i8Ga4yRFVx6tEZDRMpVVTM

Quick Sim shows the use of Recklessness first and Avatar second for an Avatar buff duration of 28 sec. Now based on tool tip description for spells / talents I would agree that this is indeed how it should work, but unfortunately blizzard has made it so that casting Avatar at any point will set the buff duration to 20 seconds :(. However, casting Avatar first and then recklessness will indeed set the buff duration to 28 seconds.

This will impact Quick Sim calculations due the shortened CD of recklessness with current talent builds. Ex: Recklessness comes up ~4-5 seconds before second use of Avatar and would result in a avatar duration of 24 seconds vice the 28 seconds currently predicted by the simulation.

**Comment by Archimtiros** [comment]
A change was pushed a couple commits ago to cast Avatar first, but you're missing that change because you're simming Weekly instead of Nightly.

**Comment by seriallos** [comment]
In addition, Weekly will be updated tonight so it'll be fixed for everyone.
