### ISSUE TITLE
Unable to start Top Gear sim - "Error that Seri forgot to handle"

### ISSUE THREAD

**Issue by stopskii** [seriallos/raidbots-issues#391]
**Describe the bug**
Attempting to use Top Gear fails to do so and produces an error that reads "Error that Seri forgot to handle".

**To Reproduce**
1. Go to Top Gear on raidbots.com
2. Input a /simc addon output from ingame
3. Select gear options and click the "FIND TOP GEAR" button
4. See error "Error that Seri forgot to handle" shown next to the "FIND TOP GEAR" button.

**Expected behavior**
No error should be thrown, and the top gear simulation should go forward as intended.

**Link a sim with the problem (if available)**
Unable to provide a sim link as the sim never starts.

**Character or /simc input**
# Vasukîî - Devastation - 2023-01-31 13:34 - US/Area 52
# SimC Addon 10.0.5-01
# WoW 10.0.5.47884, TOC 100005
# Requires SimulationCraft 1000-01 or newer

evoker="Vasukîî"
level=70
race=dracthyr
region=us
server=area_52
role=spell
professions=alchemy=100/herbalism=100
spec=devastation

talents=BsbBnWR3R1Z1HmbUKIpvm3XXhTDCAAAAAAKaIJikEJkEJlkk0CSLkIhkwBIJJSESSC

# Saved Loadout: aoe M+
# talents=BsbBnWR3R1Z1HmbUKIpvm3XXhTDCAAAAAAKaIJikEJkEJlkk0g0CJJhkEIJJSESSC
# Saved Loadout: biggg M+
# talents=BsbBnWR3R1Z1HmbUKIpvm3XXhLgAAAAAAgiGSiIJRCJRSJJJNItQiESChkkIRIJJ

head=,id=193765,bonus_id=8970/7977/6652/7936/8822/8820/9144/1627/8767
neck=,id=193001,gem_id=192967/192987/192967,bonus_id=8836/8840/8902/8960/8783/8782/8802/8793/8846,crafted_stats=36/49
shoulder=,id=134480,bonus_id=8970/7977/6652/8822/8817/9144/3284/8767
back=,id=144111,enchant_id=6592,bonus_id=8974/7977/6652/8822/8819/9144/3308/8767
chest=,id=193422,enchant_id=6625,bonus_id=8836/8840/8902/8802/8845/8793,crafted_stats=36/40
wrist=,id=193693,enchant_id=6577,bonus_id=7977/6652/7936/8822/8819/9144/8972/1633/8767
hands=,id=200380,bonus_id=6652/8829/8970/7977/1482/8767
waist=,id=193425,bonus_id=8836/8840/8902/7936/8802/8846/8793,crafted_stats=32/49
legs=,id=200382,enchant_id=6541,bonus_id=6652/8827/8974/7977/1501/8767
feet=,id=193685,enchant_id=6613,bonus_id=7977/6652/8822/8818/9144/8973/1637/8767
finger1=,id=192999,enchant_id=6556,gem_id=192976,bonus_id=8836/8840/8902/8780/8802/8793/8846/8932/8960,crafted_stats=32/49
finger2=,id=193708,enchant_id=6556,bonus_id=8968/7977/6652/7937/9144/1620/8767
trinket1=,id=110007,bonus_id=8969/7977/6652/9144/3287/8767
trinket2=,id=133642,bonus_id=7977/6652/9144/8971/3287/8767
main_hand=,id=110039,enchant_id=6642,bonus_id=8974/7977/42/9147/3303/8767

### Gear from Bags
#
# Epaulets of Deceitful Intent (392)
# shoulder=,id=134480,bonus_id=8966/7977/6652/8822/8817/9144/3271/8767
#
# Goldscar Pelt (402)
# back=,id=133639,enchant_id=6589,bonus_id=8969/7977/6652/8822/8819/9144/3281/8767
#
# Sharpeye Chestguard (392)
# chest=,id=109888,enchant_id=6624,bonus_id=8966/7977/6652/8822/8820/9144/3277/8767
#
# Galerattle Gauntlets (405)
# hands=,id=193752,bonus_id=8970/7977/6652/8822/8817/9144/1627/8767
#
# Ohn'ahran Falconer's Cinch (382)
# waist=,id=192003,bonus_id=6652/7937/1485/5864/8767
#
# Ohn'ahran Falconer's Cinch (376)
# waist=,id=192003,bonus_id=6652/7936/1478/5865/8767
#
# Boots of Explosive Growth (402)
# feet=,id=193715,bonus_id=8969/7977/6652/8822/8818/9144/1624/8767
#
# Band of New Beginnings (382)
# finger1=,id=194082,enchant_id=6556,gem_id=192976,bonus_id=8837/8838/4785/8780/8802/8793/8850,crafted_stats=36/40
#
# Unstable Arcane Loop (398)
# finger1=,id=193633,bonus_id=8968/7977/6652/7937/9144/1620/8767
#
# Primal Ritual Shell (379)
# trinket1=,id=200563,bonus_id=6652/1481/5865/8767
#
# Infernal Writ (398)
# trinket1=,id=137485,bonus_id=8968/7977/6652/9144/3277/8767
#
# Spellboon Saber (415)
# main_hand=,id=193710,enchant_id=6633,bonus_id=8973/7977/6652/9147/1637/8767
#
# Koroleth's Crackling Dagger (405)
# main_hand=,id=193687,bonus_id=8970/7977/6652/9147/1627/8767
#
# Spellboon Saber (405)
# main_hand=,id=193710,bonus_id=8970/7977/6652/9147/1627/8767
#
# Sadana's Grisly Visage (392)
# off_hand=,id=110035,bonus_id=8966/7977/6652/9144/3277/8767

### Weekly Reward Choices
#
# Jeweled Signet of Melandrus
# finger1=,id=134542,bonus_id=9130/7977/6652/7936/9144/3300/8767
#
# Tideskorn Cinch
# waist=,id=134207,bonus_id=8974/7977/6652/7937/8822/8818/9144/3297/8767
#
# Furious Ragefeather
# trinket1=,id=193677,bonus_id=8973/7977/6652/9144/1637/8767

# Checksum: e701e8b9

**Screenshots**
![image](https://user-images.githubusercontent.com/6503457/215865625-4330da82-833e-48e7-ab0b-e7c9b4b29c36.png)
![image](https://user-images.githubusercontent.com/6503457/215866282-0718b092-9b68-4cbc-adc5-5524ce954e41.png)

**Additional context**
Browser dev tools produces an "error code 500 Internal Server Error" while trying to start the sim, then once it fails and the error is produced, it produces an "error code 429 TOO MANY REQUESTS"

**Comment by stopskii** [comment]
looks like its fixed now!

**Comment by seriallos** [comment]
Yeah, major backend issues. Resolved now.
