### ISSUE TITLE
No Catalyst Gear

### ISSUE THREAD

**Issue by Drathe** [seriallos/raidbots-issues#392]
When simming top gear and having set catalyst charges as available, the sims do not include any catalyst gear at all. The items in question are eligible and the charges of the catalyst have been set properly.

**To Reproduce**
1. Raid Bots Top Gear
2. Set Catalyst charges to positive
3. Attempt sim

**Expected behavior**
If Catalyst charges are above 0 and there are items equipped or selected, sim will run and show what items to change with the catalyst, even if multiple items are not selected. At the very least, new items that are not Tier sets but are Tier slots should be shown as the appropriate tier item.

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/pV5rzhqYuZNwsPFCoYU3d3

**Character or /simc input**

```
# Agdane - Devastation - 2023-02-07 18:25 - US/Thrall
# SimC Addon 10.0.5-01
# WoW 10.0.5.47967, TOC 100005
# Requires SimulationCraft 1000-01 or newer

evoker="Agdane"
level=70
race=dracthyr
region=us
server=thrall
role=spell
professions=mining=100/jewelcrafting=100
spec=devastation

talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAoohkISSkQSkUSSSDCkIhkIBJJSkkkkA

# Saved Loadout: Boss
# talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDkAAAAAAgiWKSiIJkQSkUSS0ICRCIJSQSiEJJJJ
# Saved Loadout: M+
# talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAoohkISSkQSkUSSSDCkIhkIBJJSkkkkA
# Saved Loadout: Mobility
# talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDSAAAAAAAaIJSCRQSkUSSCBSSiACQSSCSikA
# Saved Loadout: Rasz
# talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDkAAAAAAgiWKkISSkQSkUSS0CCEkIJSQSiEJJJJ
# Saved Loadout: AoE
# talents=BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAoohIJSkkQSkUSSSDSDJSIJSQSiESSSC

head=,id=200381,bonus_id=6652/7936/8822/7977/8820/8828/8970/1479/8767
neck=,id=193001,gem_id=192961/192961/192961,bonus_id=8836/8840/8902/8960/8783/8782/8802/8793/8846,crafted_stats=36/40
shoulder=,id=193424,bonus_id=8836/8840/8902/8802/8846/8791,crafted_stats=40/49
back=,id=144111,enchant_id=6598,bonus_id=7977/41/8822/8819/9144/8972/3301/8767
chest=,id=200378,enchant_id=6625,bonus_id=6652/8830/8974/7977/1495/8767
wrist=,id=193693,enchant_id=6577,bonus_id=7977/6652/7936/8822/8819/9144/8972/1633/8767
hands=,id=200380,bonus_id=7980/6652/8829/1485/8767
waist=,id=193425,gem_id=192961,bonus_id=8836/8840/8902/8780/8802/8846/8174/8790,crafted_stats=32/49
legs=,id=200382,enchant_id=6541,bonus_id=7980/6652/8827/1485/8767
feet=,id=134298,enchant_id=6607,bonus_id=7977/6652/8822/8818/9144/8969/3281/8767
finger1=,id=133638,enchant_id=6562,gem_id=192961,bonus_id=7977/6652/9144/8780/8972/3290/8767
finger2=,id=133679,enchant_id=6562,gem_id=192987,bonus_id=7977/6652/7935/9144/8972/3290/8767
trinket1=,id=133642,bonus_id=7977/6652/9144/8972/3290/8767
trinket2=,id=194301,bonus_id=6652/7981/1498/8767
main_hand=,id=195519,enchant_id=6643,bonus_id=6652/7980/1485/8767

### Gear from Bags
#
# Scaled Commencement Spaulders (398)
# shoulder=,id=193704,bonus_id=7977/6652/8822/8817/9144/8968/1620/8767
#
# Valdrakken Accord Tabard (1)
# tabard=,id=198732
#
# Mote of Sanctification (402)
# trinket1=,id=133646,bonus_id=8969/7977/6652/9144/3281/8767
#
# Sadana's Grisly Visage (402)
# off_hand=,id=110035,bonus_id=8969/7977/40/9144/3287/8767

### Weekly Reward Choices
#
# Blazebound Lieutenant's Helm
# head=,id=193765,bonus_id=8974/7977/6652/7935/8822/8820/9144/1640/8767
#
# Mardum Chain Gloves
# hands=,id=134385,bonus_id=8973/7977/6652/8822/8817/9144/3294/8767
#
# Seal of Diurna's Chosen
# finger1=,id=195480,bonus_id=6652/7937/7980/1485/8767
#
# Decorated Commander's Cindercloak
# back=,id=195482,bonus_id=41/8825/8819/7980/1485/8767
#
# Quake-Detecting Seismostaff
# main_hand=,id=195497,bonus_id=6652/7980/1485/8767

# Checksum: 46634de
```

**Screenshots**
Screenshot of catalyst charges being set has been added. 
![2](https://user-images.githubusercontent.com/42984832/217392568-acc6ee50-ce19-4543-b461-5764e41bcd9a.PNG)

**Additional context**
Issue was noticed when attempting to sim Great Vault choices that included non-set but eligible items such as a higher ilvl helm. All item slots other than rings, trinkets, or weapons can be placed in the catalyst to change their stats, even if using the catalyst will not add a tier set bonus to most of them.

**Comment by seriallos** [comment]
Top Gear does not automatically convert and include items for comparison - you have to use the + menu (Copy and Modify) to convert the item and then select it.

![image](https://user-images.githubusercontent.com/1010294/217394914-b90264e1-06a7-402b-aeb1-606a0b31af79.png)

I'll update the Catalyst Charges panel to make it clearer similar to the Upgrade Budget panel.
