### ISSUE TITLE
Havoc DH - Fodder to the Flame vs Elysian Decree sim discrepancy?

### ISSUE THREAD

**Issue by kdubato** [seriallos/raidbots-issues#394]
I'm going to apologize up front if this is not the correct place to report what I'm about to report / ask a question.  If so, please feel free to close out.

I was simming an AOE build for Havoc Demon Hunter.  The only difference I made for the sim was one talent point ... Choosing [Elysian Decree](https://www.wowhead.com/spell=306830/elysian-decree) vs [Fodder to the Flame](https://www.wowhead.com/spell=329554/fodder-to-the-flame?spellModifier=388114).  Nothing else was different, just the one talent.

The issue / question I have is ... Why is raidbots buffing the damage of almost other standard havoc dh abilities when selecting Fodder to the Flame.  This talent does not not buff other dh abilities.   It simply calls a demon, and once it's killed, it explodes and does damage to surrounding enemies (and heals for 25%).

And the buffs are pretty considerable and consistent.  The screenshot below shows a side-by-side of the sims (extracted and ran in quick sim to show the damage numbers).  I ran this a few times, and the results are always the same.

At first, I was thinking maybe it was the [Any Means Necessary](https://www.wowhead.com/spell=388114/any-means-necessary) talent.  But that talent converts all schools of magic to chaos damage and buffs for mastery.   Maybe raidbots is not accounting for Arcane magic damage conversion? 

Apologies again if this is the wrong place for this, or if I'm missing something completely stupid (which is possible).  Both Simc copy pasta is provided below

![image](https://user-images.githubusercontent.com/987601/217688271-5736e4e0-6f02-4a6c-8a96-b5e7fb5d34d7.png)

[fodder-simc.txt](https://github.com/seriallos/raidbots-issues/files/10691498/fodder-simc.txt)
[elysian-decree-simc.txt](https://github.com/seriallos/raidbots-issues/files/10691496/elysian-decree-simc.txt)

**Comment by seriallos** [comment]
Looks like killing the demon from Fodder spawns a soul fragment that you can consume which grants bonus damage.

Looks like DH Discord has a deep dive on it: https://discord.com/channels/213770335735119873/660181958155960340/1047105516905705553
