### ISSUE TITLE
Engineering Wrist Sims low

### ISSUE THREAD

**Issue by AleatoricAgony** [seriallos/raidbots-issues#395]
I was doing droptimiser for HC Raid for Multitarget and it showed me 408 Kurog Wrist catalysed as 13% dps increase (30k Damage) over my 405 Haste Engi Wrists.
I know Haste is Not the Stat for AoE, but That Seemed a Little much.
![F8407B6C-FB1F-436C-A7F8-DFE4AFA3B30B](https://user-images.githubusercontent.com/125031064/218084741-4a1051ac-7f82-4261-b971-fead8334e724.jpeg)

**Comment by seriallos** [comment]
It's Breath of Neltharion on your wrists causing the issue. The sim uses that tinker pretty early in the fight which is a significant DPS loss compared to just doing your normal rotation. When the sim swaps in a normal wrist item without the tinker, your normal rotation is used with no Breath and it's way better.
