### ISSUE TITLE
Sands of Temporal Perfection trinket not correctly simming

### ISSUE THREAD

**Issue by Aradina** [seriallos/raidbots-issues#398]
**Describe the bug**
The trinket Sands of Temporal Perfection, available from the vendor in the Primalist Future, does not seem to sim it's effect at all. It spawns a pool near to the player granting haste and movement speed.

**To Reproduce**
1. Sim the trinket Sands of Temporal Perfection as a Patchwerk sim. 

**Expected behavior**
The sim should account for the trinket, however it isn't listed in buffs and it sims as though it only gives stats.

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/tmoyngQk7N124uqSLKG88v/simc
Sim also includes healing trinket with same main stat amount, to confirm it isn't simming the effect.

**Character or /simc input**

Character doesn't have this item, issue discovered while checking the trinket, however it isn't limited to specific characters. 

**Additional context**
The trinket spawns a pool away from the player character, which the sim likely doesn't "move" onto.

A heavy movement sim does gain the relevant buff "movement" from the trinket, though still sims very low.
https://www.raidbots.com/simbot/report/fgswgXGeZGxVfTAyZKTCSF/simc

**Comment by seriallos** [comment]
Looks like the trinket isn't implemented in SimC. SimC devs tend to focus on the end-game dungeon and raid trinkets so it's not unusual that a solo/world trinket isn't fully supported.

You can report this issue directly to the SimC team: https://github.com/simulationcraft/simc/issues
