### ISSUE TITLE
Sabatons of Burning Steps wrong stats

### ISSUE THREAD

**Issue by cdim1991** [seriallos/raidbots-issues#4]
The data base has these boots as Haste/Mastery when they are Vers/Mastery.

**Comment by seriallos** [comment]
Yeah, this is an issue with WoWDB. I've reported it and am hoping for an update this week.

FYI, this does not affect the results of the simulation, it's just a tooltip error.  SimC should have the right data which you should be able to see in the Gear section of the Full HTML Report.
