### ISSUE TITLE
Please add a "Max All" button to Top Gear -> Item Upgrade Currency

### ISSUE THREAD

**Issue by lholbert** [seriallos/raidbots-issues#405]
**Is your feature request related to a problem? Please describe.**
The times where I want to maximize my gear based on my current currency, are minimal compared to when I just wanna find out what is the best upgrade I have in my bags (fully upgraded).  I typically am just going thru and clicking Max on every currency to do this.

**Describe the solution you'd like**
A "Max All" button added to the Top Gear -> Item Upgrade Currency

**Additional context**

**Comment by seriallos** [comment]
This was added a while back, I think around 10.2
