### ISSUE TITLE
Droptimizer item levels of normal and heroic dungeons not correct

### ISSUE THREAD

**Issue by Paojian** [seriallos/raidbots-issues#406]
**Describe the bug**
In Droptimizer, the item levels shown in normal and heroic dungeons are false.

**To Reproduce**
1. Go to https://www.raidbots.com/simbot/droptimizer
2. Click on 'Normal Dungeons'
3. Normal is set at 372 and Heroic at 385.

**Expected behavior**
Normal should be at 382 and Heroic at 389.

**Comment by seriallos** [comment]
Thanks for the report, this will be fixed within the hour.
