### ISSUE TITLE
small z-index issue

### ISSUE THREAD

**Issue by SpAxxxxxx** [seriallos/raidbots-issues#409]
**Describe the bug**
small bit of content just clipping on the nav. assuming just z-index issue
see image
https://gyazo.com/4024cd4994582eaa817cb5bac09a9b10
**To Reproduce**
1. Go to 'https://www.raidbots.com/simbot/topgear'
2. Click on 'open the additional settings'
3. Scroll down to 'near the bottom of the page'

**Expected behavior**
small bit of content just clipping on the nav. assuming just z-index issue

**Comment by seriallos** [comment]
Should be fixed shortly. Thanks for the report!
