### ISSUE TITLE
Unobtainable buff in Target dummy sim

### ISSUE THREAD

**Issue by razorbladehnt** [seriallos/raidbots-issues#410]
**Describe the bug**
Unobtainable buff in "Target dummy" sim

**To Reproduce**
1. Sim "Target dummy" with [Voice of the Silent Star](https://www.wowhead.com/item=204465) equipped

**Expected behavior**
Since its a "Target dummy" sim and no allies taking damage there should be no way to get cloak proc

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/1S5Aw4RbL4hHJKfJy4QVHZ

**Character or /simc input**

For "Load from Armory":

* EU
* Howling Fjord
* Стыга

For "Load from SimC Addon":

Paste your /simc input
https://pastebin.com/ETagApSd

**Screenshots**
![image](https://github.com/seriallos/raidbots-issues/assets/15623755/23c0c1d6-e65e-49fe-98ed-a0badacd77e6)

**Comment by seriallos** [comment]
This was fixed a few weeks ago. Target Dummy sets the new SimC options `dragonflight.voice_of_the_silent_star_enable=0` which disables the cloak proc
