### ISSUE TITLE
All Great Vault items at max upgrade

### ISSUE THREAD

**Issue by janpantel** [seriallos/raidbots-issues#411]
**Describe the solution you'd like**
Similar to the existing "Select All Great Vault Items" button in the Top Gear it would be great to have a button "Select All Great Vault Items at max upgrade".

**Describe alternatives you've considered**
Currently you have to go through all items and upgrade them manually, which at this point of the patch is what most people are able to do with any heroic vault item.

**Additional context**
- none -

**Comment by cremor** [comment]
I would go a step further and request a "Upgrade all items to max" button. That would solve two use cases:
- Finding the best use of available upgrade currencies
- Finding the best upgraded Great Vault item
  (Just selecting upgraded Great Vault items, without also selecting upgraded equipped/bag items, might lead to a sub-optimal result.)

**Comment by seriallos** [comment]
This was added back around 10.2
