### ISSUE TITLE
Top Gear Tier piece 

### ISSUE THREAD

**Issue by button1990** [seriallos/raidbots-issues#412]
Hi, when simming top gear from great vault. I selected all items then changed shoulders to tier shoulders. 
 
I selected 4 piece tier set and have 1 charge available but it came back that my top gear is 3 piece and normal shoulders.

I have attached the report down below.

https://www.raidbots.com/simbot/report/pqh6xt26PouHAauuCw55mL

Regards

Steven

**Comment by seriallos** [comment]
Not sure what the issue is - I see that top result is 4 tier pieces (head, chest, hands, legs) and the non-tier shoulder.

**Comment by button1990** [comment]
Oh sorry I completely missed that! How embarrassing haha, I think it’s because the tooltip was saying I only had 3.

Sorry again and thanks
________________________________
