### ISSUE TITLE
Bug:  [16 June] Trinket tuning hofix is not in effect

### ISSUE THREAD

**Issue by Voxxel** [seriallos/raidbots-issues#413]
**Describe the bug**

Smoldering Howler Horn is still counting +2526 crit rating on ilvl 411 (adventurer 8/8) while it's only 1893 on live realms.
Probably other trinkets re-tuned in that hotfix are affected as well.

https://www.wowhead.com/news/trinket-tuning-hotfixes-june-16th-dragonflight-patch-10-1-333524

**Comment by seriallos** [comment]
Please verify that this is a data issue in SimC and not just an out-of-date Wowhead tooltip by following the steps here: https://github.com/seriallos/raidbots-issues/issues/288

**Comment by Voxxel** [comment]
So I get this result : 
 
![Untitled](https://github.com/seriallos/raidbots-issues/assets/3882152/f591d38a-d77f-423a-aa70-c2589bb692e6)

Does it mean the bug is on the simc github project instead of raidbots?

**Comment by seriallos** [comment]
That's still a Wowhead tooltip - any tooltip that shows up when you hover the mouse over it is from Wowhead.

To find out what the sim is doing with the actual proc ability, you need to look at the Abilities or Buffs section of the Full HTML Report.

As an example, here's a buff from Lariat in the report tables. Opening up the ability using the triangle will show the details that SimC used:

![image](https://github.com/seriallos/raidbots-issues/assets/1010294/a16feb58-d120-4da5-b85e-cb67c4ae680e)
