### ISSUE TITLE
Top Gear stage 2 & stage 3 messed up

### ISSUE THREAD

**Issue by Breakerzeus** [seriallos/raidbots-issues#414]
**Describe the bug**
when simming multiple options with Top Gear, after finishing stage 1 all the combinations are thrown overboard and it's simming just 1 combination for stage 2 and stage 3. also the Sim is very unlikely correct, with a couple of items upgraded to 447 I'd lose about 10k DPS. The items stay the same, just upgraded to 447 as it is possible since 10.1.5.

**To Reproduce**
1. Go to 'Top Gear'
2. copy some items to the upgraded 447 version (via +icon)
3. Select multiple items to generate a handful combinations 
4. let it sim!
5. check the combinations while machine is running, especially stage 2 & 3

**Expected behavior**
combinations will get fewer for stage 2 & 3 but should not be reduced to only 1 combination. Also it shouldn't be 10k DPS loss when adding itemlevel to the same items. It's just illogical.

**Link a sim with the problem (if available)**

https://www.raidbots.com/simbot/report/b3xJk62YnWvxcJMmSHbA9j

**Character or /simc input**

For "Load from SimC Addon":
```
# Bremsar - Demonology - 2023-07-09 17:33 - EU/Das Syndikat
# SimC Addon 10.1.0-10
# WoW 10.1.0.50000, TOC 100100
# Requires SimulationCraft 1000-01 or newer

warlock="Bremsar"
level=70
race=troll
region=eu
server=das_syndikat
role=spell
professions=alchemy=100/herbalism=100
spec=demonology

talents=BoQAAAAAAAAAAAAAAAAAAAAAAAIJRSCkWKHQkmkESJAAAAAokIJSiAkIJSKaJRCBAAAAAAJ

# Saved Loadout: Dungeon AoE
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJh0CAAAAAaRQCJKRSkI5ARaJROABAAAAAAJ
# Saved Loadout: Demo
# talents=BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJhUCAAAAAKRSSCCkEJkDkiWSSOABAAAAAAJ

# Attendant's Concocting Cover (441)
head=,id=202579,bonus_id=9410/9380/6652/9415/9224/9221/1498/8767
# Choker of Stolen Thunder (441)
neck=,id=206180,gem_id=192985/192948/192948,bonus_id=6652/9144/9334/1663/8767/9477/8782
# Amice of the Sinister Savant (447)
shoulder=,id=202531,bonus_id=6652/9382/9227/1504
# Mammoth-Trainer's Drape (441)
back=,id=193787,enchant_id=6592,bonus_id=6652/9223/9220/9144/9334/1663/8767
# Cursed Robes of the Sinister Savant (441)
chest=,id=202536,enchant_id=6625,bonus_id=6652/9231/9409/9334/1492/8767
# Vibrant Wildercloth Wristwraps  (447)
wrist=,id=193510,enchant_id=6574,gem_id=192919,bonus_id=8836/8840/8902/9405/9376/8793/9379/8960/9366/9413,crafted_stats=49/36,crafting_quality=5
# Grips of the Sinister Savant (441)
hands=,id=202534,bonus_id=6652/9230/9409/9334/1492/8767
# Sailcloth Waistband (447)
waist=,id=158346,enchant_id=6904,bonus_id=9382/6652/9415/9223/9219/9144/3317/8767
# Leggings of the Sinister Savant (444)
legs=,id=202532,enchant_id=6541,bonus_id=6652/9228/9410/9381/1501/8767
# Vibrant Wildercloth Slippers  (447)
feet=,id=193519,enchant_id=6613,bonus_id=8836/8840/8902/9405/9376/8791/9379/8960/9366,crafted_stats=36/49,crafting_quality=5
# Seal of Diurna's Chosen (421)
finger1=,id=195480,enchant_id=6556,gem_id=192948,bonus_id=6652/7981/1498/8767/8780
# Signet of Titanic Insight  (447)
finger2=,id=192999,enchant_id=6556,gem_id=192955,bonus_id=8836/8840/8902/8780/9405/8793/9376/9366,crafted_stats=32/49,crafting_quality=5
# Irideus Fragment (444)
trinket1=,id=193743,bonus_id=9381/6652/9144/1666/8767
# Neltharion's Call to Dominance (444)
trinket2=,id=204202,bonus_id=6652/9409/9381/1485/8767
# Illuminating Pillar of the Isles  (447)
main_hand=,id=194898,enchant_id=6643,bonus_id=8836/8840/8902/9405/8793/9376/8174/9366,crafted_stats=40/32,crafting_quality=5

### Gear from Bags
#
# Cloak of Coordination (29)
# back=,id=65274
#
# Ashjra'kamas, Shroud of Resolve (155)
# back=,id=169223,bonus_id=6603/1472
#
# Blood-Drenched Robes (424)
# chest=,id=206199,bonus_id=9324/6652/9223/9221/9144/1646/8767
#
# Phoenix-Plume Gloves (441)
# hands=,id=202578,bonus_id=9410/9380/6652/9224/9218/1498/8767
#
# Loop of Pulsing Veins (441)
# finger1=,id=159463,enchant_id=6556,bonus_id=6652/9414/9144/9334/3311/8767
#
# Loop of Vitriolic Intent (431)
# finger1=,id=134530,bonus_id=9331/6652/9413/9144/3310/8767
#
# Ominous Chromatic Essence (444)
# trinket1=,id=203729,bonus_id=9410/9381/6652/1498/8767
#
# Gavel of the First Arbiter (285)
# main_hand=,id=189862,bonus_id=8761/6652/8159/1524/6646
# finger1=,id=193000,ilevel=447,crafted_stats=32/36

### Additional Character Info
#
# upgrade_currencies=c:1792:121/c:2122:37/c:2245:2000/i:204194:7
#
# slot_high_watermarks=0:441:441/1:441:441/2:447:447/3:441:441/4:447:447/5:444:444/6:447:447/7:447:447/8:441:441/9:441:441/10:444:444/11:441:441/12:447:447/13:431:431/14:0:408/15:0:408/16:402:402
```

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
It's possible that /simc input from 10.1.0 will not work properly in all cases on the site right now. I'll be able to take a deeper dive into this later tonight or tomorrow.

**Comment by Breakerzeus** [comment]
I just loaded my character via the armory via raidbots and then converted it to simC input and added gear from bags. So that should work if the converter is working properly. And id did not. Same behavior as stated in OG post.

**Comment by seriallos** [comment]
Armory would have the same problem since it's still 10.1 item data.

I think EU servers are coming up now - when you have a chance, could you grab a new /simc input and see if it's still happening?

**Comment by Breakerzeus** [comment]
Already did that before server went down. If I import the simc input from ingame, it works. seems to be something with your converter if the character is pulled from armory. and maybe also when copying items to change sockets or stats.

**Comment by seriallos** [comment]
Are you saying that /simc after servers up are working but Armory conversion is still failing?

Can you link those sims, both the success and the failure? It's possible the Armory hasn't fully updated and is still using item bonuses from 10.1 which would have the upgrade problem.

**Comment by Breakerzeus** [comment]
yea well I can't reproduce it. If I take the same input (copy the original addon input) from the faulty sim, it now isn't reduced to 1 sim in stage 2. it starts with 136 combinations in stage 1, then 128 in stage 2 and 37 in stage 3. So I can't tell what happened in the meantime. But even the numbers are totally different now.

Faulty Sim: https://www.raidbots.com/simbot/report/bKBMpY2D6KTXfba7zkudWu

current sim: https://www.raidbots.com/simbot/report/9speRPBZ6XxYYHkNj2CAUm

**Comment by seriallos** [comment]
> Faulty Sim: https://www.raidbots.com/simbot/report/bKBMpY2D6KTXfba7zkudWu

You didn't select Grips of the Sinister Savant in that sim so only the equipped gear has the 4 set bonus.
 
> current sim: https://www.raidbots.com/simbot/report/9speRPBZ6XxYYHkNj2CAUm

This sim has the 4 set bonus.

**Comment by Breakerzeus** [comment]
omfg... ok so how quickly can we forget this? I'm so sorry. I'm closing this issue.

**Comment by seriallos** [comment]
Hah, my bad, I should've seen that earlier!
