### ISSUE TITLE
Cannot sim a 447 version of crafted ring

### ISSUE THREAD

**Issue by wheatbread** [seriallos/raidbots-issues#415]
# If your bug is related to an incorrect tooltip, check the Full HTML Results before reporting! https://github.com/seriallos/raidbots-issues/issues/288

**Describe the bug**
When I click the + sign on a 421 Signet of Titanic Insight in the sim, it will let me sim a 424 and 437 version, but not a 447 version.  The 447 option is grayed out, saying "cannot afford".   I'm not sure why it says this, as I have a spark of shadowflame and 34 aspect crests. 

I tried setting all item upgrade currency to max to see if that would fix it, but it did not. 

Here is a picture:

![image](https://github.com/seriallos/raidbots-issues/assets/548824/88ea8a92-89b3-4816-ae39-f30c99d80de4)

**To Reproduce**
Try to sim a character with a 421 signet of titanic insight and click the + sign. 

**Expected behavior**
To be able to click the + sign and sim a 447 version of the ring.

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here
Have not simmed it yet as I wished to sim the 447 version

**Character or /simc input**

https://pastebin.com/vrVtjRpq

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
Should be fixed in ~15 minutes or so. Raidbots wasn't properly handling the Aspect Crest -> Enchanted Aspect Crest conversion. Thanks for the report!
