### ISSUE TITLE
no option for not inclue the stats from Ominous Chromatic Essence

### ISSUE THREAD

**Issue by scorpionero** [seriallos/raidbots-issues#416]
Hi all,

The Raidbot includes stats from the trinket-Ominous Chromatic Essence" either is not in use. 
I've made 4 runs changing only the rune and stats from Ominous (as is no option for do not include when not in use). Please see the 3 screenshots attached with the results. Because of that can't properly sim which gear will be the best for use.

![image](https://github.com/seriallos/raidbots-issues/assets/139497780/1b0bc329-a076-4edf-a46b-80a0586c6f8d)
![image2](https://github.com/seriallos/raidbots-issues/assets/139497780/de6eaf2d-d49b-49c8-b8a6-3a4a2487628b)
![image3](https://github.com/seriallos/raidbots-issues/assets/139497780/32d7f886-d8c4-4f20-b6d8-865e50054b06)
![image4](https://github.com/seriallos/raidbots-issues/assets/139497780/9118e6a6-0ac8-4446-9fd9-193b55138f70)

**Comment by seriallos** [comment]
I'm not quite clear on what you are asking - do you want a "No Stats" option for the "Ominous Chromatic Essence Dragonflight" dropdown? If so, that's not currently possible in SimC, it always must have stats chosen.

Please rephrase your request and provide some full sim URLs rather than just screenshots.

**Comment by scorpionero** [comment]
yes, that is exactly what I'm asking for, "no stats", because where is the
point to choose stats for something that is not impact me?

Thanks

czw., 13 lip 2023 o 21:21 Dave Hendler ***@***.***>
napisał(a):

**Comment by seriallos** [comment]
The different choices will impact your DPS though it may not be a huge difference. You may need to run a simpler sim with fewer things changing to see the specific impact.

There are no plans for a "No Stats" option since that's not a realistic use case for the item.
