### ISSUE TITLE
Balance Druid sims not casting Convoke?

### ISSUE THREAD

**Issue by RavenMind** [seriallos/raidbots-issues#420]
I cannot find in the report where Convoke the Spirits is being cast for Balance Druid sims. I would expect the numbers to be somewhat higher than are being reported if it were being cast. I understand that in the Damage Breakdown, that Convoke may be being reported as the abilities that it casts, however, I'm not seeing it being cast at all in the Sample Ability log. Is it being used?
I've seen this behavior over multiple sims, run in various ways, and over several weeks.
Here is a link to my sim: https://www.raidbots.com/simbot/report/dDFan1HtSGWimcAMRJETu2
Honestly, I don't know if this is a bug or expected behavior, and wanted to ask about it more than make a bug report. Apologies if this is the incorrect forum for this issue. 
Thank you!

**Comment by seriallos** [comment]
I'm not an expert on the Balance APL but a quick look shows that Convoke isn't used when there are 4 or more targets. You ran a 40 second 6-target simulation.

Convoke shows up when the fight style is relevant:

1 target Patchwerk: https://www.raidbots.com/simbot/report/3iMHffyiAispHjkQfpXaaw
3 target Patchwerk: https://www.raidbots.com/simbot/report/5i6Vd5zRndsiE7ysyj5vky

At 4+ targets, it's not used:

4 targets: https://www.raidbots.com/simbot/report/kkck9WxHsMBtvWNNhQxsto

For more information on the theorycrafting/testing of the APL, you'd need to ask in the Druid Discord and/or consult the actual SimC repository: https://github.com/simulationcraft/simc

**Comment by RavenMind** [comment]
Ahh, I see. Thanks very much for the response & looking into it!
