### ISSUE TITLE
Profession droptimizer recommends already equipped items

### ISSUE THREAD

**Issue by carlwoodhouse** [seriallos/raidbots-issues#422]
https://www.raidbots.com/simbot/report/roJZKtvx9GpzuF95wXQNXm

Here droptimizer recommends i equip the crafted offhand, which i already have equipped. Presumably because the sim got better procs or something ... seems like it could just exclude already equipped things though ?

**Comment by seriallos** [comment]
Thanks for the report! I'll try to take a look at it this week.

**Comment by seriallos** [comment]
Should be fixed shortly (20-30 minutes).

It was a subtle error - basically Droptimizer thought a Haste/Mastery item was different than a Mastery/Haste item because it didn't know that the amount of stats would be the same regardless of which crafting slot the stat was put in.
