### ISSUE TITLE
Lua error in client.

### ISSUE THREAD

**Issue by casteffens86** [seriallos/raidbots-issues#423]
# If your bug is related to an incorrect tooltip, check the Full HTML Results before reporting! https://github.com/seriallos/raidbots-issues/issues/288

**Describe the bug**
When I log into WoW, a window opens up signaling a Lua error.

Message: Interface/AddOns/Raidbot/Raidbot.lua:66: attempt to call global 'RegisterAddonMessagePrefix' (a nil value)
Time: Wed Sep 13 18:42:18 2023
Count: 1
Stack: Interface/AddOns/Raidbot/Raidbot.lua:66: attempt to call global 'RegisterAddonMessagePrefix' (a nil value)
[string "@Interface/AddOns/Raidbot/Raidbot.lua"]:66: in main chunk

Locals: _G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined =[C]:-1
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 775
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 371
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface/FrameXML/UnitFrame.lua:929
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 MANA = "Mana"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface/FrameXML/FloatingChatFrame.lua:2388
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @Interface/FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @Interface/FrameXML/AutoComplete.lua:368
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 ToggleEncounterJournal = <function> defined @Interface/FrameXML/UIParent.lua:1135
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee attack that spends Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @Interface/FrameXML/ChatFrame.lua:1167
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MultiBar5Button11Shine4 = MultiBar5Button11Shine4 {
 }
 T

**To Reproduce**

**Expected behavior**

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
Looks like the wrong addon. There's a "Raidbot" addon that hasn't been updated since 2016 that is not affiliated with raidbots.com.

If you are looking for the SimulationCraft addon which can be used with raidbots.com, you can check this support article: https://support.raidbots.com/article/54-installing-and-using-the-simulationcraft-addon

**Comment by casteffens86** [comment]
TY!
