### ISSUE TITLE
Droptimizer is missing Crystalbinder Chestguard

### ISSUE THREAD

**Issue by hollo6** [seriallos/raidbots-issues#426]
**Describe the bug**
Crystalbinder Chestguard (Leather Chest from The Everbloom) is missing from Droptimizer options.
The item does exist in the drop table, listed in the dungeon journal and actually drops (just got it) but it's not listed by Droptimizer.

**To Reproduce**
1. Go to Droptimizer
2. Select All Dungeons or The Everbloom
3. Check Items to sim
4. Note Crystalbinder Chestguard is not listed and thus not being considered.

**Expected behavior**
It should appear as a loot option from this dungeon and be simmed accordingly.

**Link a sim with the problem (if available)**
N/A

**Character or /simc input**
Any leather class (I have checked all of them. /simc input or load from armory doesn't matter.

**Screenshots**
![image](https://github.com/seriallos/raidbots-issues/assets/365584/4e6ef2aa-f83e-4ad2-8ad0-d7bb8157eb26)

**Comment by seriallos** [comment]
Should show up shortly. Some of those old dungeons have weird dungeon journal data that I wasn't handling correctly in a few cases.
