### ISSUE TITLE
Item sets

### ISSUE THREAD

**Issue by CID-ROBIN** [seriallos/raidbots-issues#428]
I have two sets in my backpack. ( items at convert catalyst and seconds set pieces at character )
When i try sim new set ( season 3 ) when i add new pieces set in the raidbots page window Items sets not have reaction and write unable to generate valid combination and it I have select new set pieces or not have. All time is it same and i don't try sim how much is new set better than old set with specific item level.

**Comment by seriallos** [comment]
Please provide your /simc input and the options you have selected. You can also run a sim with some of the items and post that with information on the items/settings you had to change to get it to run.

**Comment by CID-ROBIN** [comment]
I use this imput data:

# Cid - Affliction - 2023-12-04 12:29 - EU/Thunderhorn
# SimC Addon 10.2.0-01
# WoW 10.2.0.52301, TOC 100200
# Requires SimulationCraft 1000-01 or newer

warlock="Cid"
level=70
race=goblin
region=eu
server=thunderhorn
role=spell
professions=alchemy=33/engineering=33
spec=affliction

talents=BkQAj5LiEN4VXhSin5RcWeAUggIJJRSCkiCRaJJhUAAAAAFAAAAAAAERjkEJSSiSSSAAJA

# Saved Loadout: relax
# talents=BkQAj5LiEN4VXhSin5RcWeAUgQCJJRSSQKpApRSQBAAAA0IBAAAAAASIQSSikIpJEAQC
# Saved Loadout: multi target M+
# talents=BkQAj5LiEN4VXhSin5RcWeAUggIJJRSCkiCRaJJhUAAAAAFAAAAAAAERjkEJSSiSSSAAJA
# Saved Loadout: single target RAID
# talents=BkQAj5LiEN4VXhSin5RcWeAUggIJJRSCkiCRaJJhUAAAAANAAAAAAASElQkkIJSaJRAAJA
# Saved Loadout: multi target Raid
# talents=BkQAj5LiEN4VXhSin5RcWeAUggIJJRSCkiCRaJJhUAAAAANAAAAAAASEFSSkIJJaJRAAJA

# Grimhorns of the Sinister Savant (441)
head=,id=202533,gem_id=192961,bonus_id=6652/9229/9409/9334/1498/8767/9413
# Sunrise Circlet (437)
neck=,id=209916,gem_id=192988/192961/192961,bonus_id=6652/9551/1494/8766/9477/8782
# Mantle of Meticulous Plans (476)
shoulder=,id=207897,bonus_id=9639/6652/9506/9144/9567/1566/8767
# Shawl of the Sinister Savant (447)
back=,id=202528,enchant_id=6595,bonus_id=6652/9382/1504
# Cursed Robes of the Sinister Savant (441)
chest=,id=202536,enchant_id=6625,bonus_id=6652/9231/9334/1492/8767
# Red Martial Shirt (1)
shirt=,id=42378
# Hellscream's Reach Tabard (1)
tabard=,id=63378
# Fading Flame Wristbands (463)
wrist=,id=210204,enchant_id=6580,bonus_id=6652/9600/9505/7979/9563/1494/8767
# Grips of the Sinister Savant (441)
hands=,id=202534,bonus_id=6652/9230/9334/1492/8767
# Poisonroot Belt (473)
waist=,id=134423,bonus_id=9639/6652/9599/9506/9144/9566/9846/8767
# Leggings of the Sinister Savant (437)
legs=,id=202532,enchant_id=6541,bonus_id=6652/9228/7979/9329/1494/8767
# Sandals of the West Wind (441)
feet=,id=133370,bonus_id=6652/9223/9219/9144/9334/9458/8767
# Seal of the Regal Loa (470)
finger1=,id=159458,enchant_id=6556,bonus_id=9639/6652/9599/9144/9565/9834/8767
# Band of Callous Dominance (470)
finger2=,id=134528,enchant_id=6556,bonus_id=9639/6652/9599/9144/9565/9843/8767
# Irideus Fragment (437)
trinket1=,id=193743,bonus_id=6652/9144/9329/1659/8767
# Nymue's Unraveling Spindle (476)
trinket2=,id=208615,bonus_id=6652/7979/9567/1507/8767
# Jagged Iris Sica (476)
main_hand=,id=159133,enchant_id=6634,bonus_id=9639/6652/9147/9571/9840/8767
# Solena's Watchful Collection (463)
off_hand=,id=159669,bonus_id=9639/6652/9144/9559/9458/8767

### Gear from Bags
#
# Collar of Raking Claws (460)
# head=,id=134426,bonus_id=9562/9639/6652/9516/9506/9144/9466/8767
#
# Devout Ashdevil's Hatespikes (470)
# shoulder=,id=207270,bonus_id=6652/7979/9511/9565/1501/8767
#
# Frigid Conservator's Gown (444)
# chest=,id=210349,bonus_id=9553/9506/6652/1475/8767
#
# Anger-Spark Gloves (441)
# hands=,id=186460,bonus_id=9552/9505/41/9465/8767
#
# Devout Ashdevil's Tights (460)
# legs=,id=207271,bonus_id=6652/7979/9562/9512/1491/8767
#
# Belor'relos, the Suncaller (463)
# trinket1=,id=207172,bonus_id=6652/7979/9563/1494/8767
#
# Sol's Magestaff (463)
# main_hand=,id=119174,enchant_id=6634,bonus_id=9639/6652/9147/9563/9842/8767

### Additional Character Info
#
# upgrade_currencies=c:2707:105/c:1792:3586/c:2706:377/c:2245:1023/i:204195:58/i:198058:9/i:204193:95/i:198059:2/i:190453:6/i:204196:14/i:198056:1/i:204682:1/i:197921:4/i:204194:12/i:198048:7
#
# slot_high_watermarks=0:460:460/1:457:457/2:476:476/3:444:444/4:473:473/5:460:460/6:441:441/7:463:463/8:450:450/9:470:470/10:463:463/11:447:447/12:463:463/13:476:476/14:415:415/15:1:81/16:463:463

# Checksum: 216afcab


and after i choose this specific setting

table item sets in the section gear
devout set at minimum set bonus 4 set

sinster set at minimum set bonus 0 set


select head, chest, hands, legs at convert catalyst ( free items in my backpack )
all enchants and 6 specific gems at haste amd mastery with two with primary stat

sim option
fight style patchwerk
number of bosses 10 bosses
fight length 40 sec
simC version nightly

other is default

Sim write: 
cannot make combinations with enough item set bonuses

when i set catalist charges at 4 you give me chance start sim but How i have know what he need set when he don't write it me?

**Comment by seriallos** [comment]
Got it, I understand the confusion. I'll look into adding some better warnings about this scenario to let you know to try adding catalyst charges.

**Comment by seriallos** [comment]
Top Gear will now include the option of updating catalyst charges if this scenario is encountered.
