### ISSUE TITLE
PvP Season 3 (Conquest) gear incorrectly showing Veteran track upgrades in Droptimizer

### ISSUE THREAD

**Issue by Synkronos** [seriallos/raidbots-issues#429]
**Describe the bug**
Raidbots shows Conquest purchasable PvP gear as Veteran track and upgradeable to 463. In game, this gear has been hotfixed to be Champion track, so 8/8 upgrade should be at 476 ilvl.

**To Reproduce**
1. Go to Droptimizer
2. Click on "PvP Season 3 (Conquest)"
3. Click on the "Upgrade up to" dropdown
4. Displays incorrect Veteran track upgrades in the dropdown

**Expected behavior**
The "Upgrade up to" dropdown list should display Champion track upgrade, up to 476, to reflect the recently hotfixed ilvl of Conquest gear

**Screenshots**
![image](https://github.com/seriallos/raidbots-issues/assets/12526226/e2eb5b5e-20bf-4a9d-974e-14d96153000b)
Image showing champion track Conquest boots in-game

**Additional context**
Blue post announcing the change: https://us.forums.blizzard.com/en/wow/t/update-coming-to-gear-from-rated-pvp/1719592

**Comment by seriallos** [comment]
Thanks for the report! This is rolling out now, should be fixed in 20 minutes or so.
