### ISSUE TITLE
No artifact traits found from /simc input.

### ISSUE THREAD

**Issue by tatu77** [seriallos/raidbots-issues#43]
I'm getting this error and have no idea why. Simulationcraft is up to date (Last update was 11/02/2017) Is this due to the new patch today?

**Comment by seriallos** [comment]
Game addon API changed and the SimC addon needs to be updated. I think the SimC addon will get an update within ~12 hours but you can make the fix manually by deleting some code: https://medium.com/raidbots/temporary-fix-for-the-simc-addon-for-7-3-5-82118b734705
