### ISSUE TITLE
Droptimizer for Season 3 World PvP Using Wrong Items

### ISSUE THREAD

**Issue by Vaeryx99** [seriallos/raidbots-issues#430]
When trying to use the Dropitimizer for Season 3 World PvP, it only shows un-upgradeable ilvl 350 items, when the correct items for Season 3 World PvP are 431 and 450, and are upgradeable.  This makes the sim completely useless for comparing these items.

**Comment by seriallos** [comment]
A fix for this is rolling out now. Should properly handle the 431 and 450 levels. Thanks for the report!
