### ISSUE TITLE
Maul not showing up in quick sim for my bear

### ISSUE THREAD

**Issue by weirdodude1** [seriallos/raidbots-issues#431]
**Describe the bug**
Maul is not showing up anywhere on the quick sim report or the html version of the quick sim report.

**To Reproduce**
Run sim on character with guardian druid specialization.

**Expected behavior**
Expect to see maul as one of the top damage abilities.

For "Load from Armory":
US
Tanaris
Mood

**Additional context**
 It's been like this for awhile, I remember trying quick sims weeks ago and it didn't show maul then, either. Apparently something with WoW patch 10.2 has broken the reporting of maul use and damage. Other abilities and damage show up, just no maul.

**Comment by seriallos** [comment]
Please post a URL to a sim showing the issue.

**Comment by weirdodude1** [comment]
This is the quick sim for US/Tanaris/Mood my guardian druid. 
https://www.raidbots.com/simbot/report/rPv8xCXAFRfaeV5xtztAKC
and the html report for that
https://www.raidbots.com/simbot/report/rPv8xCXAFRfaeV5xtztAKC/simc

Maul isn't on there anywhere, I think it may be due to WoW changes on how maul and raze work. Thanks!

**Comment by seriallos** [comment]
Probable reason is that Rage of the Sleeper isn't taken and the SimC APL looks to expect that talent to be active. I'm having a hard time finding any recommended talent build that doesn't include Rage of the Sleeper so while this is a bug, it's likely going to be very low priority for the SimC team. I've passed this report onto them.
