### ISSUE TITLE
Jadefire stomp (WW talent) is not being found

### ISSUE THREAD

**Issue by Kristnovo** [seriallos/raidbots-issues#436]
Just trying to sim my monk to see if the heroic weapon I got in my vault is better than the weapon I have but all I get is errors.

https://www.raidbots.com/simbot/report/6uudr3QoKV1B8txL3QKDVG

**Comment by seriallos** [comment]
Because of the talent changes to WW monks, you'll need to either use /simc input from a 10.2.5 server or you will need to log in and log out of a 10.2.5 server for Armory lookups to have updated talents.
