### ISSUE TITLE
can't sim monk due to talent name changes

### ISSUE THREAD

**Issue by irqtoons** [seriallos/raidbots-issues#437]
# If your bug is related to an incorrect tooltip, check the Full HTML Results before reporting! https://github.com/seriallos/raidbots-issues/issues/288

**Describe the bug**
Talent name changes for monk from faeline stomp to jadefire stomp as well as a few others have made the sim crash

**To Reproduce**
!. /simc windwalker monk
2. attempt to run raidbots sim
3. crash

**Expected behavior**
says sim failed

**Link a sim with the problem (if available)**

[If you have a sim report that shows the problem, please provide the URL here](https://www.raidbots.com/simbot/report/pvS5sRGutBbYmbAAj5Gtmw)

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

# Monktoons - Windwalker - 2024-01-16 15:08 - US/Mal'Ganis
# SimC Addon 10.2.0-01
# WoW 10.2.5.52902, TOC 100205
# Requires SimulationCraft 1000-01 or newer

monk="Monktoons"
level=70
race=vulpera
region=us
server=malganis
role=attack
professions=herbalism=32/skinning=10
spec=windwalker

talents=B0QAoOod+N2jAX+OIKaOO9AefBAAAAAAARSkkElkIRAAAAgEJJFJASSiQikERCtikEJJtEAAAA

# Saved Loadout: wowhead
# talents=B0QAoOod+N2jAX+OIKaOO9AefBAAAAAAARSkkElkIRAAAAgEJJFJASSiQikERCtikEJJtEAAAA
# Saved Loadout: single target
# talents=B0QAoOod+N2jAX+OIKaOO9AefBAAAAAAAhEJJRLiEBAAAASkkUAkkkkk0SCERCtikQSSLBBAAA
# Saved Loadout: raid
# talents=B0QAoOod+N2jAX+OIKaOO9AefBAAAAAAAIRSS0iIRAAAAgEJJFAJJJJCJFJRkQrIJRSSLBAAAA

# Mystic Heron's Hatsuburi (470)
head=,id=207245,bonus_id=6652/9599/7979/9513/9565/1501/8767
# Chain of the Green Flight (463)
neck=,id=137311,bonus_id=9563/9639/6652/8783/10245/9144/9836/8767
# Mystic Heron's Hopeful Effigy (476)
shoulder=,id=207243,bonus_id=6652/9571/9639/9511/1507
# Cloak of Fading Echoes (470)
back=,id=134405,enchant_id=6592,bonus_id=9639/6652/9506/9144/9565/9843/8767
# Mystic Heron's Burdens (476)
chest=,id=207248,enchant_id=6625,bonus_id=6652/9571/9639/9515/1507
# Crystalline Tender's Wristbands (463)
wrist=,id=210375,enchant_id=6574,bonus_id=9506/6652/9600/9559/1494/8767
# Gloves of Vile Defiance (460)
hands=,id=137320,bonus_id=9562/9639/6652/9506/9144/9466/8767
# Salty Shell-Studded Girdle (473)
waist=,id=133368,bonus_id=9639/6652/9600/9506/9144/9570/9879/8767
# Mystic Heron's Waders (460)
legs=,id=207244,enchant_id=6490,bonus_id=6652/9562/9639/9512/1491
# Vigorous Sandstompers (470)
feet=,id=207838,enchant_id=6613,bonus_id=9569/9639/6652/9506/9144/1563/8767
# Seal of the Regal Loa (467)
finger1=,id=159458,enchant_id=6550,bonus_id=9568/9639/6652/9600/9144/9464/8767
# Lord Waycrest's Signet (470)
finger2=,id=158362,enchant_id=6550,bonus_id=9569/9639/6652/9600/9144/9834/8767
# Coiled Serpent Idol (470)
trinket1=,id=207175,bonus_id=6652/7980/9569/1501/8767
# Mirror of Fractured Tomorrows (470)
trinket2=,id=207581,bonus_id=9569/9639/6652/9144/1521/8767
# Obsidian Seared Facesmasher  (486)
main_hand=,id=190513,enchant_id=6643,bonus_id=8836/8840/8902/9405/9500/8795/9498,crafted_stats=36/32,crafting_quality=5
# Vulmir, the Northern Tempest (476)
off_hand=,id=156185,enchant_id=6642,bonus_id=7756/9567/9884/8767

### Gear from Bags
#
# Silent Tormentor's Hood (467)
# head=,id=207133,bonus_id=6652/9600/9508/7980/9568/1498/8767
#
# Hood of Perpetual Conflict (467)
# head=,id=207936,bonus_id=9568/9639/6652/9599/9506/9144/1554/8767
#
# Bladesworn Battle Standard (1)
# back=,id=181803
#
# Ashjra'kamas, Shroud of Resolve (155)
# back=,id=169223,bonus_id=6286/1472
#
# Moss-Covered Wingtip Shoes (463)
# feet=,id=159347,enchant_id=6613,bonus_id=9639/6652/9506/9144/9563/9458/8767
#
# Arch-Druid's Tainted Seal (463)
# finger1=,id=134487,enchant_id=6550,bonus_id=9563/9639/6652/9599/9144/9836/8767
#
# Bramble Bark Band (437)
# finger1=,id=209914,enchant_id=6550,bonus_id=6652/9599/9551/1494/8766
#
# Pocket-Sized Computation Device (81)
# trinket1=,id=167555,gem_id=167672/168742/168631,bonus_id=1481,gem_bonus_id=1472/5855/4784
#
# Rune of the Umbramane (418)
# trinket1=,id=209958,bonus_id=9545/6652/1462
#
# Smoldering Seedling (447)
# trinket1=,id=207170,bonus_id=6652/7982/9554/1478/8767
#
# Scythe of the Fallen Keeper (473)
# main_hand=,id=207792,bonus_id=6652/7980/9570/1504/8767
#
# Illuminating Pillar of the Isles  (463)
# main_hand=,id=194898,enchant_id=6640,bonus_id=8836/8840/8902/9405/8792/9498,crafted_stats=32/49,crafting_quality=5
#
# Igira's Flaying Hatchet (467)
# main_hand=,id=207787,bonus_id=6652/7980/9568/1498/8767
#
# Igira's Flaying Hatchet (454)
# main_hand=,id=207787,enchant_id=6640,bonus_id=6652/7982/9556/1485/8767
#
# Interloper's Mossy Skull (476)
# off_hand=,id=119176,bonus_id=9571/9639/6652/9144/9875/8767

### Weekly Reward Choices
#
# finger1=,id=162548,bonus_id=9574/9639/6652/9599/9144/9847/8767
#
# wrist=,id=159340,bonus_id=9573/9639/6652/9600/9506/9144/9844/8767
#
# main_hand=,id=159661,bonus_id=9571/9639/6652/9147/9840/8767
#
# Mystic Heron's Glovebills (467)
# hands=,id=207246,bonus_id=6652/7980/9568/9514/1498/8767
#
# Eternal Sentinel's Cord (473)
# waist=,id=207135,bonus_id=6652/9600/9508/7980/9570/1504/8767
#
# wrist=,id=210206,bonus_id=6652/9599/9508/7980/9569/1501/8767
#
### Additional Character Info
#
# upgrade_currencies=c:2708:107/c:2709:116/c:2707:43/c:2706:199/c:2245:391/i:190453:5/i:198048:1
#
# slot_high_watermarks=0:470:470/1:463:463/2:476:476/3:476:476/4:473:473/5:460:460/6:470:473/7:463:463/8:460:470/9:467:467/10:470:470/11:470:470/12:473:473/13:169:447/14:486:486/15:476:476/16:476:476

# Checksum: fbfc3a52

**Screenshots**

**Additional context**

Error: Actor 'Monktoons': Action 'chi_burst': Cannot parse expression from '!talent.jadefire_stomp': Cannot find talent 'jadefire_stomp'.
SimulationCraft 1020-01 for World of Warcraft 10.2.0.52808 Live (hotfix 2024-01-10/52808, git build HEAD eed0abd254)
Simulating... ( iterations=100000, threads=32, target_error=1.000, max_time=360, vary_combat_length=0.20, optimal_raid=0, fight_style=DungeonSlice )

**Comment by seriallos** [comment]
Because of the talent changes to WW monks, you'll need to either use /simc input from a 10.2.5 server or you will need to log in and log out of a 10.2.5 server for Armory lookups to have updated talents.

**Comment by irqtoons** [comment]
Hey,

I've definitely pulled my /simc from live server and it still gives me the error, didn't try using armory

I'll keep trying, thanks 🙂
________________________________

**Comment by seriallos** [comment]
Should be good now, I hadn't properly updated Nightly and Weekly.

**Comment by irqtoons** [comment]
Works now thanks!!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
