### ISSUE TITLE
Trying to sim my WW monk, and giving me errors  saying it can't find the talent Jade stomp Even when I don't have that talent in use in my build.

### ISSUE THREAD

**Issue by Bigbalue5150** [seriallos/raidbots-issues#438]
Error: Actor 'Mojomadness': Action 'chi_burst': Cannot parse expression from '!talent.jadefire_stomp': Cannot find talent 'jadefire_stomp'.
SimulationCraft 1020-01 for World of Warcraft 10.2.0.52808 Live (hotfix 2024-01-10/52808, git build HEAD eed0abd254)
Simulating... ( iterations=100000, threads=32, target_error=0.050, max_time=60, vary_combat_length=0.20, optimal_raid=1, fight_style=HecticAddCleave )

This was the exact error that is displayed everytime I try to sim my Toon today,

**Comment by seriallos** [comment]
Should be working now
