### ISSUE TITLE
Gear Compare does not apply settings from custom footers in expert mode properly.

### ISSUE THREAD

**Issue by mahranaka** [seriallos/raidbots-issues#439]
**Describe the bug**
Simulating via expert mode with custom footers from the MDT-sim export does work on Top-Gear and Droptimizer sims. If i send the same sim in a Gear Compare it results in much lower DPS. If we look at the html report that we can view in gear compare it shows that the pulls only last 10-20 seconds which is waay too low for a key level 28 sim. The Gear Compare does not seem to properly apply the settings from the weakauras export.

For reference:
Weakaura used to create the export: https://wago.io/Yya4XBbl-

MDT Dungeon route import for reference:
`!9vvxR1nmm0FqJcXXXF9A3OWyqwPUmy7btV3BCkz1nPKRtx3l93(SKDsCsVm460elPJo6yzvdXCVr30122DAY5)RPUuA0tDngT7NhVtZhf)6PVz0hAAg6)HD8C3qVPUIslm6tdUHXBp4SEV9R9TdashM8dFg2VR)rZ178P5TqOgVr)6b3KfC)S1zp5bmV3utm1CW6PPXrBVxpD0zF16ad6xMCUZrNwFa)kdpPMAk(wf8IhED2Uh25(zplrhPjdvzEfjQr32sTTTlyW2KOnyxMffeJYc0p3DWJ18hTOqlsKecKW8CqfOz(ocrTRmrebf5E5gqjfGb5mfyXn55saBdNvqLUaSkcm(Pi8iHv4pe5ffQ2JaVuzq7JkqUQaUiYpnKxsIezrbXaAPCPLaCKfp2kqjtHFtqLQMGWQIuDov0iUYDSbQ3agBzqQLOc)XIvYcqvB4CSlJufrxTH1kuoiQSI1NY2kfWMlaG12DOo2ljqrnxiygZAWJKuI1Uc7y29jisHmayah)Oorer2hokJ2aFy)hFyyPuxcPTiTiPvzAb2QslwAXtlrCrsDvy9mldhiX(IsYoTQCxBaQv7V(6r29XR0SK64nR6B6GcXy)DvY8rSebrKbcpfwegr2fK1uFP7Ol5fBHi8SMX16yMtSnCkExSSyJISol8lt9pAh6ttq1ER9zya7XfhUnmFeiLESR1)922ZwpoUmEfgHYBFl88UHjV99hcATE44VddFxMQQ7Hb2nXpVrkzLufVimPxYlc)tH2RQWrk3CLGkOvuUssvvfIWUbtvPXQb2Dnu)6yvw(bCzcgrQcHt4sIIRsbJ4kkkivQcjvk5kYLX9g7HX3F4C3JDUp9S11eE)PUxMRX)yTpbfT3y(3p`

The generated footer can be found in the sims linked below 

**To Reproduce**
1. Go to raidbots.com
2. Click on Gear Compare
3. Use the simc addon to get a simc export for the character in aoe talents
4. Paste that in Gear Compare
5. Make Gear sets to compare
6. Generate the export for the dungeon route sim with above weakaura from above route
7. Paste the export for the dungeon route sim into the footer of the enabled expert mode in Gear Compare
8. Run the sim
9. Repeat all these steps on Droptimizer and on Top Gear to get an example of a supposedly working simulation

**Expected behavior**
Droptimizer and Top Gear end up at around 256k DPS depending on the Gearset. This seems plausible.
Gear Compare should end up at approx. the same number.

**Real behavior**
The Gear Compare ends up at around 164k DPS. Its Pulls last only around 10-20 Seconds.

**Link a sim with the problem (if available)**
Simulation via Gear Compare (bugged): https://www.raidbots.com/simbot/report/dsmCuq3mEkicu9DsRa1oGR
Simulation via Top Gear (working(?), normal DPS numbers): https://www.raidbots.com/simbot/report/9HGiThGNoabqYN195Yt7iu
Simulation via Droptimizer (working(?)): https://www.raidbots.com/simbot/report/tFvDy6mHKTYRBkSxe1iZMo

**Character or /simc input**
Attatched as txt file
[# Moonflora - Balance - 2024-01-17 .txt](https://github.com/seriallos/raidbots-issues/files/13967341/Moonflora.-.Balance.-.2024-01-17.txt)

**Comment by seriallos** [comment]
This is an issue with your input, not Raidbots. `single_actor_batch=0` is not what you want when a sim uses `copy` which is how Gear Compare works.

Be very careful about using Expert Mode if you are not familiar with reading/writing your own SimC input: https://support.raidbots.com/article/15-simc-expert-mode
