### ISSUE TITLE
Norgannon's Prowess Trinket

### ISSUE THREAD

**Issue by Bonegrin** [seriallos/raidbots-issues#44]
The buff is showing a 0.

Equip: Your damaging spells have a chance to increase your Intellect by 0 for until cancelled.

Seems any trinket I compare it to shows as better, even ones I know are much lower.

**Comment by seriallos** [comment]
Can you share a report URL?

Is it just a tooltip issue? It's likely that it's simulating correctly (you may be able to check buffs/etc in the full HTML report) and it's just the tooltip showing incorrect information.

**Comment by Bonegrin** [comment]
Sure

https://www.raidbots.com/simbot/report/oystFDsyQdFrbATR3doSS6

It seems no matter the trinket it sims better than norgannon’s even though it is my #4 overall BIS trinket for Elem Shaman and Sheath of Az is like #15 or something.



Sent from Mail for Windows 10

**Comment by seriallos** [comment]
Looks like you haven't tweaked the "Additional Pantheon Trinkets in Raid" setting so it's running the fight without any procs of group Pantheon buff which is certainly making it appear less valuable.

You can open up the Simulation Options area on any screen and set the "Additional Pantheon Trinkets in Raid" to a number somewhat close to how many trinkets you have in your normal raid group to get a more accurate number.
