### ISSUE TITLE
Variable Pulse Lightning Capacitor

### ISSUE THREAD

**Issue by MBence99** [seriallos/raidbots-issues#441]
**Describe the bug**
Variable Pulse Lightning Capacitor doesn't proc in sims

**To Reproduce**
Just on gear compare select the trinket

**Expected behavior**
Proc trinket every so often

**Item in question**
https://www.wowhead.com/item=171640/variable-pulse-lightning-capacitor

**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/ii2BtrhRHqLf7ogPqeUnUi/simc

**Additional context**
Wanted to test out some timewalking trinkets to experiment with but i was trying to see if it was actually worth the effort. The gear compare results were too low in terms of dps so i checked the html breakdown and it seems it didn't proc once. This problem is probably the same for other timewalking trinkets as they are old items but upscaled, but i haven't tested it out myself for others, just wanted to give you guys a headsup.

**Comment by seriallos** [comment]
Yeah, that item is not implemented in SimC. Older items are definitely less likely to fully work (aside from basic stats). If a time walking item is potentially competitive with current endgame content it'll sometimes get updated but that scenario is pretty rare - similar to world quest items, most TW items end up being significantly outclasses by M+ or raid items.

This is also technically a SimC issue so the best place to post the issue would be on their issue tracker: https://github.com/simulationcraft/simc/issues

**Comment by seriallos** [comment]
More context from the SimC repo: https://github.com/simulationcraft/simc/issues/4994
