### ISSUE TITLE
Missing item in Gear Compare (Spirited Stag's Claymore)

### ISSUE THREAD

**Issue by Wanny** [seriallos/raidbots-issues#444]
**Describe the bug**
The Spirited Stag's Claymore isn't available in Gear Compare

**To Reproduce**
1. Go to '.Gear Compare'
2. Paste any result from SimulationCraft
3. Search for Spirited Stag's Claymore
4. Bam, it's not showing on the list

**Expected behavior**
The item to be available.

**Comment by seriallos** [comment]
I assume your character is a survival hunter? If so, should be fixed in 15-20 minutes.
