### ISSUE TITLE
Heroic dungeon gear is incorrectly showing on the Explorer instead of Adventurer track in Droptimizer

### ISSUE THREAD

**Issue by Synkronos** [seriallos/raidbots-issues#445]
**Describe the bug**
Heroic dungeon, Weekly Timerift and weekly token purchase Dreamsurge gear in the Droptimizer are on the incorrect track in the item upgrade dropdown.

**To Reproduce**
1. Go to 'Droptimizer' and load a character
2. Click on 'Normal Dungeons'
3. Click on 'Heroic'
4. Scroll down to 'Upgrade up to'
5. Dropdown list incorrectly shows Explorer track upgrades, which cap out at 476.
6. The same is true of 'Dreamsurges' -> second 'Dreamsurges' sub-select.
7. The same is true of 'Time Rifts' -> 'Time Rifts Weekly'

**Expected behavior**
The 'Upgrade up to' dropdown should show Adventurer track, which caps out at 489.

**Screenshots**
This is an image of the in-game Dungeon loot in the loot journal for Heroic, showing Adventurer track.
![image](https://github.com/seriallos/raidbots-issues/assets/12526226/21f5ce0e-2421-4637-9fd5-96e5c151a00d)

**Comment by seriallos** [comment]
Thanks for the report, should be fixed now
