### ISSUE TITLE
Top Gear  Item Search doesn't allow select Season 4 Items

### ISSUE THREAD

**Issue by karpana** [seriallos/raidbots-issues#449]
# If your bug is related to an incorrect tooltip, check the Full HTML Results before reporting! https://github.com/seriallos/raidbots-issues/issues/288

**Describe the bug**
When using the `Top Gear` capaility, when trying to bring in a Season 4 item (for the purposes of simming bullion purchases for example), most of the items (eg. Whispering Incarnate Icon) indicate they are "not valid for the current season.

![image](https://github.com/seriallos/raidbots-issues/assets/15716173/05e296b1-11ea-440b-bbd9-2a90e17aba08)

**To Reproduce**
1. Go to `Top Gear`
2. Click on the `Item Search`
3. Scroll down to type `Icon`
4. See the red warning indicating `Not a valid season item level`

**Expected behavior**
Items that are available in game for the current season should be searchable and selectable.

**Link a sim with the problem (if available)**
N/A

If you have a sim report that shows the problem, please provide the URL here
N/A

**Character or /simc input**
N/A

For "Load from Armory":

* Region (US, EU, etc)
* Ysera 
* Karpana

For "Load from SimC Addon":
N/A

Paste your /simc input

**Screenshots**
![image](https://github.com/seriallos/raidbots-issues/assets/15716173/a02255af-90ef-404a-aa17-8354a6e94f37)

**Additional context**
N/A

**Comment by seriallos** [comment]
Enter a valid item level for the season 4 upgrade track in the Level input. By default it uses the base item level which won't be a season 4 item level since these are all items from previous patches/seasons.

<img width="626" alt="image" src="https://github.com/seriallos/raidbots-issues/assets/1010294/912689f0-bcd0-4e2d-8742-fa95fa817f58">
