### ISSUE TITLE
[Bug] Error in Vibrant Wildercloth Shawl crafted item levels

### ISSUE THREAD

**Issue by F-Lambda** [seriallos/raidbots-issues#452]
Something's wrong with the crafting options for Vibrant Wildercloth Shawls, it thinks the valid item levels is much higher than it should be for the spark/crest combinations.

![image](https://github.com/seriallos/raidbots-issues/assets/21232805/2341c744-e9a1-4ff0-8a89-b5db5bf09588)

Toxified Armor Patch is also missing as an embellishment option.

![image](https://github.com/seriallos/raidbots-issues/assets/21232805/e0cf2305-6479-42c0-aad6-af458ba51f7a)

**Comment by seriallos** [comment]
Can you post your /simc input?

**Comment by F-Lambda** [comment]
This was the the simc for that sim. 

https://pastebin.com/tjwLXVsp

The weird ilvl no longer shows up when going back to "Run Sim Again" from the comparison that was eventually made, though you still can't add Toxified to the cape.

https://www.raidbots.com/simbot/report/w1fd4Kn97ZYjuKJwHaQKrB

**Comment by seriallos** [comment]
522 isn't an item level that can be crafted. Items will end up at 521 or 525. The UI indicates this with a warning:

<img width="424" alt="image" src="https://github.com/seriallos/raidbots-issues/assets/1010294/a54e38b1-6bcc-461c-a7c8-5345aeaecabf">

It still allows you to create the item for cases where you might want to test out something wild.

I will see if I can add some more safety checks to not show the funky upgrades.

Toxified can't be added to that item in-game. It can use Shadowflame but I think Toxified is limited to leather item.
