### ISSUE TITLE
Madness of the betrayer not Simming properly

### ISSUE THREAD

**Issue by LucaBlight80** [seriallos/raidbots-issues#454]
It appears the proc or stat weights or the whole trinket entirely is not simming properly. I have it at 515 on a WW monk. Adjusting the ilvl up on gear compare does not yield an increase, all other trinkets also sim nearly 20k dps higher than it. This seems to lead me to the conclusion that its not being simmed properly

**Comment by seriallos** [comment]
Many time walking trinkets are not implemented. You can report these directly to the SimC project but they tend to be a low priority - sometimes they can be competitive with current trinkets and in those cases they may get support in SimC.

Trinket implementation isn't something that I directly work on in Raidbots, it's handled in the SimC project itself:

https://github.com/simulationcraft/simc/issues
