### ISSUE TITLE
Ran arcane mage sims and it keeps casting arcane barrage

### ISSUE THREAD

**Issue by Ivan-karkit** [seriallos/raidbots-issues#456]
https://www.raidbots.com/simbot/report/922fZ9eey5abfEU8qqiJ4C

it reproduces every simc, but it works okay when i switch to icy

**Comment by seriallos** [comment]
SimC does not support pre-patch and is under heavy development for The War Within release. It's expected that sims are going to be unreliable until closer to The War Within launch / Season 1 opening.
