### ISSUE TITLE
[Request] Possiblity to get simc action sequence table as a return

### ISSUE THREAD

**Issue by Oldalf** [seriallos/raidbots-issues#48]
Outside of grabbing my stat weights and simming gear what I often used the client for was to look throught he sample sequence table to compare my rotation between logs and the table to find things I did wrong. Now that I've started using raidbots for the majority of my simming I no longer keep my client up to date so at least for me being able to see the action sequence table and some of the other statistics that were available in the client would be a most welcome feature.

**Comment by seriallos** [comment]
Raidbots always generates and links the full SimC report which has the sample sequence table. You can get there from the "Full HTML Report" link on any result page:

![image](https://user-images.githubusercontent.com/1010294/37538309-7c3ecac8-290d-11e8-90cc-d9967641c6e6.png)

**Comment by Oldalf** [comment]
aah cool, thanks!
