### ISSUE TITLE
Getting errors in Advanced tab now.

### ISSUE THREAD

**Issue by adamaj74** [seriallos/raidbots-issues#49]
All of a sudden, on all my characters, I'm getting this error when I try to run an advanced sim:

SimulationCraft 735-02 for World of Warcraft 7.3.5 Live (wow build 25901, git build HEAD b894578e3)
ERROR! Setup failure: Unknown option 'augmentation' with value ''

I have tried deleting the addons and reinstalling. Here is the raw input data from the error page:

single_actor_batch="1"
report_details="0"
desired_targets="1"
augmentation=""
flask=""
optimal_raid="true"
food=""
potion=""
iterations="10000"
fight_style="Patchwerk"
max_time="300"

hunter="Ûlf"
level="110"
race="voidelf"
region="us"
server="proudmoore"
role="attack"
talents="1313113"
spec="marksmanship"
artifact="55:0:0:0:0:1637:1:1524:21:1523:1:1522:1:1521:4:1337:1:1369:1:307:1:308:1:322:1:321:1:320:4:319:4:318:4:317:4:309:1:310:1:311:1:312:4:313:4:314:4:316:4:315:4"
crucible="1739:1778:312/1739:1774:313/1739:1778"
name="Ûlf"
head=",id=147142,bonus_id=3562/1497/3528"
neck=",id=147014,enchant_id=5890,bonus_id=3562/1497/3528"
shoulder=",id=152371,bonus_id=3614/43/1477/3336"
back=",id=147140,enchant_id=5435,bonus_id=3561/1482/3528"
chest=",id=147139,bonus_id=3561/1482/3528"
wrist=",id=140874,bonus_id=3573/41/1512/3336"
hands=",id=144303,bonus_id=1811/3630"
waist=",id=147055,bonus_id=3561/1502/3337"
legs=",id=147143,bonus_id=3561/1487/3336"
feet=",id=147045,bonus_id=3562/1507/3336"
finger1=",id=151641,enchant_id=5429,bonus_id=3459/3630,gem_id=151584"
finger2=",id=151972,enchant_id=5429,bonus_id=3613/1467/3336"
trinket1=",id=147017,bonus_id=3561/1487/3336"
trinket2=",id=141482,bonus_id=3466/1472"
main_hand=",id=128826,bonus_id=727,relic_id=3613:1462:3336/3613:1482:3337/3562:1502:3336,gem_id=152061/152092/147104"
copy="copy1,"Ûlf""
wrist=",id=152280,bonus_id=3613/1457/3528"

**Comment by Ugrel** [comment]
I too am getting:

augmentation="undefined"
flask="undefined"
optimal_raid="undefined"
food="undefined"
potion="undefined"

inserted into my advanced simc input.  I am also running the MM single target profile.

**Comment by seriallos** [comment]
Yeah, I broke advanced with the new consumable options. I'm working on a fix now.

**Comment by seriallos** [comment]
I've patched Advanced mode to ignore the consumable options which should fix this specific error. Looking into a long term solution here (probably removing these options from advanced mode as they can often cause more problems than they solve)

**Comment by adamaj74** [comment]
Thanks for the update! I'm mainly just relieved it wasn't something I did, lol.
