### ISSUE TITLE
Relic Compare: Demonology

### ISSUE THREAD

**Issue by ZMacDaddy** [seriallos/raidbots-issues#50]
The drop-down fields for relics don't autofill for Demonology like they do with Destruction and Affliction.

**Comment by ZMacDaddy** [comment]
# SimC Addon 1.9.1

warlock="Macaberesque"
level=110
race=goblin
region=us
server=thrall
role=spell
professions=alchemy=815/engineering=800
talents=1212123
spec=demonology
artifact=37:0:0:0:0:1183:1:1184:1:1185:1:1182:1:1181:1:1180:1:1179:4:1607:1:1178:4:1177:4:1176:4:1175:4:1712:1:1174:4:1173:4:1172:4:1171:4:1391:1:1170:1:1608:26:1606:1:1605:4:1354:1
crucible=1739:1774:1176/1739:1774:1176/1739:1780:1177

head=,id=151944,bonus_id=3612/1512/3336
neck=,id=151966,enchant_id=5437,gem_id=151583,bonus_id=3611/1808/1492/3336
shoulder=,id=151949,enchant_id=5883,gem_id=151583,bonus_id=3612/1808/1502/3528
back=,id=152172,enchant_id=5311,bonus_id=3611/1492/3336
chest=,id=152176,gem_id=151583,bonus_id=3611/1808/42/1492/3336
shirt=,id=151116
tabard=,id=40643
wrist=,id=151953,gem_id=151583,bonus_id=3611/1808/1497/3336
hands=,id=152173,bonus_id=3611/1517/3337
waist=,id=151942,bonus_id=3611/40/1487/3528
legs=,id=152175,bonus_id=3611/1487/3528
feet=,id=151940,gem_id=151583,bonus_id=3611/1808/1487/3528
finger1=,id=132452,enchant_id=5428,gem_id=151583,bonus_id=1811/3630
finger2=,id=132369,enchant_id=5428,gem_id=151583,bonus_id=1811/3630
trinket1=,id=154177,bonus_id=3985/3997
trinket2=,id=141482,bonus_id=3573/1522/3528
main_hand=,id=137246
off_hand=,id=128943,gem_id=155852/152035/152031,bonus_id=748,relic_id=3611:1497:3528/3611:1502:3337/3612:1502:3528

### Gear from Bags
#
# Grim Inquisitor's Death Mask (945)
# head=,id=152174,bonus_id=3611/43/1487/3528
#
# Crown of Relentless Annihilation (970)
# head=,id=151943,bonus_id=3612/1512/3336
#
# Hood of Eternal Disdain (1000)
# head=,id=132394,bonus_id=1811/3630
#
# Wakener's Loyalty (1000)
# head=,id=144385,bonus_id=1811/3630
#
# Chain of the Unmaker (960)
# neck=,id=152283,enchant_id=5437,bonus_id=3611/1492/3336
#
# Brysngamen, Torc of Helheim (940)
# neck=,id=133636,bonus_id=3536/1592/3528
#
# Prydaz, Xavaric's Magnum Opus (1000)
# neck=,id=132444,enchant_id=5437,gem_id=151584,bonus_id=1811/3630
#
# Grim Inquisitor's Shoulderguards (945)
# shoulder=,id=152177,enchant_id=5883,bonus_id=3611/1487/3528
#
# Lessons of Space-Time (1000)
# shoulder=,id=144369,bonus_id=1811/3630
#
# Recurrent Ritual (1000)
# shoulder=,id=132393,enchant_id=5883,bonus_id=3529/1811/3630
#
# Diabolic Shroud (950)
# back=,id=147181,enchant_id=5436,gem_id=151583,bonus_id=3563/1808/1532/3337
#
# The Master Harvester (1000)
# chest=,id=151821,bonus_id=3459/3630
#
# Magistrike Restraints (1000)
# wrist=,id=132407,bonus_id=3459/3630
#
# Sin'dorei Spite (1000)
# wrist=,id=132379,bonus_id=1811/3630
#
# Streten's Sleepless Shackles (1000)
# wrist=,id=132381,bonus_id=3459/3630
#
# Gloves of Unseen Evil (945)
# hands=,id=137506,bonus_id=3536/1597/3336
#
# Kazzak's Final Curse (1000)
# waist=,id=132374,bonus_id=1811/3630
#
# Power Cord of Lethtendris (1000)
# waist=,id=132457,bonus_id=1811/3630
#
# Enhanced Worldscorcher Cinch (950)
# waist=,id=151951,gem_id=151583,bonus_id=3611/1808/1492/3336
#
# Feretory of Souls (1000)
# waist=,id=132456,bonus_id=1811/3630
#
# Diabolic Leggings (940)
# legs=,id=147184,bonus_id=3563/1522/3336
#
# Pillars of the Dark Portal (1000)
# legs=,id=132357,bonus_id=1811/3630
#
# Mistbound Helarjar Footwraps (940)
# feet=,id=133608,gem_id=151583,bonus_id=3536/1808/1592/3528
#
# Norgannon's Foresight (1000)
# feet=,id=132455,bonus_id=3459/3630
#
# Alythess's Pyrogenics (1000)
# finger1=,id=132460,enchant_id=5428,gem_id=130220,bonus_id=1811/3630
#
# Loop of the Life-Binder (960)
# finger1=,id=152688,enchant_id=5428,bonus_id=3611/1502/3337
#
# Ring of Contempt (940)
# finger1=,id=134490,enchant_id=5428,gem_id=151583,bonus_id=3536/1808/40/1592/3528
#
# Zealous Tormentor's Ring (950)
# finger1=,id=152284,enchant_id=5428,bonus_id=3611/1492/3336
#
# Band of the Sargerite Smith (945)
# finger1=,id=152064,enchant_id=5429,gem_id=151584,bonus_id=3611/1808/1487/3528
#
# Soul of the Netherlord (1000)
# finger1=,id=151649,enchant_id=5429,gem_id=151584,bonus_id=3459/3630
#
# Sacrolash's Dark Strike (1000)
# finger1=,id=132378,enchant_id=5429,gem_id=151584,bonus_id=1811/3630
#
# Astral Alchemist Stone (935)
# trinket1=,id=151607,bonus_id=3609/600/3608
#
# Eye of Skovald (980)
# trinket1=,id=133641,bonus_id=3536/1632/3337
#
# Prototype Personnel Decimator (975)
# trinket1=,id=151962,bonus_id=3612/1517/3337
#
# Caged Horror (965)
# trinket1=,id=136716,bonus_id=3536/1617/3337
#
# Acrid Catalyst Injector (945)
# trinket1=,id=151955,bonus_id=3611/1487/3528
#
# Seth's Graphite Fishing Pole (60)
# main_hand=,id=25978,enchant_id=5930
#

**Comment by seriallos** [comment]
Think I see the issue. Some of the gear loading wasn't handling the off hand artifact correctly so this probably also affected prot pallies.

I'll take a crack at fixing it in the next couple of days when I have some free time.

Thanks for the report and details!

**Comment by ZMacDaddy** [comment]
Thanks for the prompt response! I'm glad it was of help.

**Comment by seriallos** [comment]
Fix is rolling out now, should be generally available in 10 minutes or so!

Please re-open if off hand artifacts are still having issues!
