### ISSUE TITLE
Relics incorrect in sim.

### ISSUE THREAD

**Issue by EMTGuy777** [seriallos/raidbots-issues#53]
I noticed in my sim that my artifact weapon wasn't the correct ilevel, and when I mouse over the weapon it says my relics aren't the correct ilevel either. 

https://www.raidbots.com/simbot/report/rVapdgayWur9HuGjiPJDEC

^Sim in question. 

https://imgur.com/a/z7KPgt5 < Screenshots of what the weapon/relic ilevel should be.

**Comment by seriallos** [comment]
Thanks for the report!

This is definitely on my short list to get fixed soon. Artifact item level is handled differently in 8.0.1 (just based on bonus ID, not based on relic data) and I think I should have a fix within a day or two.
