### ISSUE TITLE
On Advanced HTML Report - pls put Gear on main view

### ISSUE THREAD

**Issue by Malhier** [seriallos/raidbots-issues#54]
Using SimPermut and the Advanced Sim.  Looking at the top DPS choices through the Full HTML Report, you have to scroll down and open the Gear chevron to see the gear chosen for that copy.

Since the point of the sim (in this application) is to compare gear sets, could you put the gear set in a more immediately visible location in the report, such as under the "Results, Spec and Gear" chevron, which is both at the top and automatically open once you drill down into that copy?

**Comment by seriallos** [comment]
This specific request is likely better directed to https://github.com/simulationcraft/simc as the HTML report is generated by SimC itself, not Raidbots.

I _am_ looking at improving the Raidbots report page with more details like this but don't have any solid plans yet.
