### ISSUE TITLE
Saber's Eye of Agility missing from list

### ISSUE THREAD

**Issue by jeramiahsental** [seriallos/raidbots-issues#58]
Every other gem is available on the list (including the old 40 Agility version), but the 9 Agility version is missing.

![missing gem](https://user-images.githubusercontent.com/42282232/43980180-03ba58e8-9ca2-11e8-9995-656d30e4442e.png)

![missing gem 2](https://user-images.githubusercontent.com/42282232/43980279-6f5674ba-9ca2-11e8-957b-08ff0cacb9c2.png)

**Comment by seriallos** [comment]
Added back in!
