### ISSUE TITLE
Neck Items not being downloaded

### ISSUE THREAD

**Issue by ashcraft** [seriallos/raidbots-issues#59]
No matter what character I import from SimC, the stat weights screen tells me that it's unable to download my neck item. I've tried multiple times and reinstalled SimC, but to no avail.

**Comment by seriallos** [comment]
Can you provide a link to a report showing the issue? I'm also not entirely sure what "not being downloaded" means in your report.

**Comment by ashcraft** [comment]
I'm not sure how to get an actual report as it happens when I paste SimC stats and hit generate. I just did one on the character I'm on now and got the same thing. I'll attach an image of what is happening.
<img width="471" alt="capture" src="https://user-images.githubusercontent.com/4410762/43995263-6f5384d4-9d70-11e8-8e3b-a7f1ea04379c.PNG">

**Comment by ashcraft** [comment]
Just as a follow up, I tried again on my max level, and it went through. Sorry for the confusion/waste of time.

**Comment by seriallos** [comment]
I'm taking a deeper look - the fact that the behavior changed is interesting.

**Comment by ashcraft** [comment]
Thank you! I didn't do anything different than usual to make it happen. Open SimC, copy the text, paste, generate. Like I said it did go through this time on my max level doing the same sequence.

**Comment by seriallos** [comment]
This issue should be resolved shortly

Looks like a combination of SimC pruning its local database and Raidbots not being configured properly to look up items that were pruned.
