### ISSUE TITLE
Wrong Character picture in Sim results

### ISSUE THREAD

**Issue by SimonQR** [seriallos/raidbots-issues#60]
The picture of the simmed character shown in the results is not the right character.
This can be seen here: https://www.raidbots.com/simbot/report/aH9WdMfHBBdVvRqi9QjLRs
The picture is of my shaman that used to have the name of my druid. So when the names got switched the picture didn't update to the new character.

**Comment by seriallos** [comment]
The images come from Blizzard so there's nothing direct I can do.

Think the only things to try are to login and logout and hope that kicks the images to update. I believe it _should_ eventually update but it may take some time.

**Comment by SimonQR** [comment]
Fair enough. I just wanted to make sure I had not hit upon some edge-case ;)
