### ISSUE TITLE
Discord Bot is about 1k off from the website.

### ISSUE THREAD

**Issue by FranklyProven** [seriallos/raidbots-issues#61]
Hello,

I noticed that the website and the discord bot are a little off.

![website](https://user-images.githubusercontent.com/42592989/44436260-35199280-a582-11e8-87d7-0bf15123191e.PNG)

Above is the website

![discord](https://user-images.githubusercontent.com/42592989/44436261-35199280-a582-11e8-874c-614aac1862de.PNG)

Above is the discord bot.

Just a minor issue I saw I thought I would make aware.

**Comment by seriallos** [comment]
Can you provide a URL for those reports so i can look at them a bit more closely?

**Comment by FranklyProven** [comment]
Website: https://www.raidbots.com/simbot/report/8CNRoKRrMLHDq7TESBzqj6
Bot: https://www.raidbots.com/simbot/report/3hFzj1yjNw7R2juGV9MLWg

I noticed that the simulation details are a little off on these reports. That could be where the issue is.

**Comment by seriallos** [comment]
I think the website and the bot are handling "no buffs" slightly differently. I'll take a look.

**Comment by FranklyProven** [comment]
Sweet, thank you!

**Comment by seriallos** [comment]
Should be fixed now. Running the bot with `-nb` should properly disable all the class buffs.
