### ISSUE TITLE
Stamina scaling- Windwalker Monk

### ISSUE THREAD

**Issue by adrian-budau** [seriallos/raidbots-issues#64]
Could stamina be added when calculating scale factors for Windwalker monks?

Currently It sims at 0.5 damage per stamina which is quite a lot and it must be factored in item upgrades.

**Comment by adrian-budau** [comment]
I don't know if this is permitted or not, but bumping this. This fix is probably a oneliner and would fix some issues with Windwalker scaling impression (right now it seems to have the lowest scalings if you disregard Stamina).

**Comment by seriallos** [comment]
It's on my list to look at soon, just been bogged down in infrastructure work to make sure the site can stay up for raid release.

**Comment by adrian-budau** [comment]
Oh, ok. Sorry for to bug you then and thanks 👍

**Comment by Hinalover** [comment]
Yea Stamina is one of the few non-tank specs that value Stamina, so giving an exception just for Windwalkers is probably fine.

**Comment by seriallos** [comment]
This is now live!
