### ISSUE TITLE
Stat Weight report failed

### ISSUE THREAD

**Issue by Teradan99** [seriallos/raidbots-issues#66]
Link to report:
https://www.raidbots.com/simbot/report/41651TnqfKyk7W5Httqer8

**Comment by seriallos** [comment]
Thanks for the report. Looks like this is an intermittent failure that happens at a very low rate.

Running the same sim again should work if you run into this again.

(Basically, there's a rare timing condition in the Raidbots backend where a job can get "lost" if a few unlikely things happen in an unfortunate order)
