### ISSUE TITLE
Confused by Top Gear Result. Maybe a bug?

### ISSUE THREAD

**Issue by Starfira** [seriallos/raidbots-issues#67]
I got some new rings on my shaman as I leveled her and decided to run Top Gear to see which ones to use. I tossed in my legendary rings to see how they stacked up because I was curious and some of them had three secondary stats instead of two which I thought might make them still viable as a stat stick.

I was puzzled by the result however: 
https://www.raidbots.com/simbot/report/wYhEttPBGHjEEYPNWzfsBN
It really seems to like my legendary ring Soul of the Farseer but when I noticed my Insignia of the Grand Army ring had the same three secondary stats but in higher amounts I was was really perplexed. Why would it be valuing this particular ring above the others? 

I did a stats weight but it didn't really give me any good insight: https://www.raidbots.com/simbot/report/tKeopcyTkpRHpSaJ8Th8Go

I just don't get why if Soul of the Farseer is my top choice why Insignia of the Grand Army wouldn't be better since the secondary on it are all higher. 

Thanks for the help!

**Comment by domzae** [comment]
Because the sim isn't disabling the bonuses from the rings, you can safely delete your legiondaries - your 300+ rings are better

**Comment by seriallos** [comment]
Yeah, for ele the talent ring is still using the legendary effect. I've passed it on to SimC devs and it'll get fixed soon.

**Comment by seriallos** [comment]
Shaman module should no longer be simming legendary powers!
