### ISSUE TITLE
All sims except Advance do not use a feast for Arcane Mage.

### ISSUE THREAD

**Issue by dajogg** [seriallos/raidbots-issues#70]
Default settings; optimal raid buffs selected. Example:

https://www.raidbots.com/simbot/report/2ob1VnfyrbndNuD8711DoH

Using the same simc export from in-game across all sim types.

**Comment by seriallos** [comment]
SimC report shows that the default APL is using the captain's feast:

https://www.raidbots.com/simbot/report/2ob1VnfyrbndNuD8711DoH/simc

![image](https://user-images.githubusercontent.com/1010294/44962180-47c08f80-aed1-11e8-978e-7140525febae.png)
