### ISSUE TITLE
Discord Bot Iterations Issue

### ISSUE THREAD

**Issue by e9muzik** [seriallos/raidbots-issues#71]
The Raidbots discord bot is not completing the requested quantity of iterations. 

The default is currently set at 100,000 but isn't completing over 8,000. I've attached a screenshot of the sim that I've run with the option set at 100,000 and the link that shows the iterations completed

![image](https://user-images.githubusercontent.com/42910675/44956125-f8f10680-ae8c-11e8-8e65-2ececcf027d7.png)

https://www.raidbots.com/simbot/report/t1BZC2z1b2idrWRqphEkr7

**Comment by seriallos** [comment]
This is intended behavior. When using Smart Sim or when choosing 30k Iterations or higher, Raidbots runs SimC in "target error" mode - it will run until either 100k iterations OR the error margin is 0.05%. In this case, it does not take the full amount of iterations to reach the desired error.

Running with an error margin lower than 0.05% is not supported on Raidbots.
