### ISSUE TITLE
Incorrect 'azerite_level=' Parsing

### ISSUE THREAD

**Issue by ManagerWoW** [seriallos/raidbots-issues#73]
The "Load From Simc Addon" option is not correctly parsing the "azerite_level=" part of the neck. In the example below, the neck is set to '20' yet if you look in the profile of the linked report, it's blank. I verified it against the actual Simc program: stats, gear, and dps are different.

Report: https://www.raidbots.com/simbot/report/mNBSzMAsAjtNHBHPSygV83/simc

Reproduction:
1) Run a Quick Sim
2) 'Load From Simc Addon': https://pastebin.com/XBkUQPCE
3) Run

Side note: Can the text parser ignore the Source & Origin fields, so they don't need to be commented out every time?

**Comment by seriallos** [comment]
Hmm, where is that input from? "Load from Simc addon" is only really meant for input directly from the /simc addon and your input looks like it came from somewhere else (a simc report profile, maybe?).

There's probably an issue with the item names for each slot. I'll log an issue but right this second you'd probably need to make sure your input conforms to look precisely like what the addon outputs.

**Comment by ManagerWoW** [comment]
It's from the actual Simcraft program's Battle.net import. Raidbot's Battle.net import also gets the 'azerite_power=X' correctly.

Whenever the Simcraft addon is used, raidbots drops the neck item level number, and uses an extra bonus ID that isn't present from b.net imports ('1510' in this case).

**Comment by seriallos** [comment]
Only input from the SimulationCraft addon and importing directly from the Armory on Raidbots are supported at this time.
