### ISSUE TITLE
Offhand string missing from output of Show simc input > Download simc input

### ISSUE THREAD

**Issue by jwoodhouse** [seriallos/raidbots-issues#75]
Hi,
I'm trying to run a large sim, which is outside of the 300k iteration limit, so I want to download the raw simulationcraft input to run it locally.
However it looks like the string for the offhand weapon is being omitted entirely when downloading the input using the Download simc input option

I have tested this with multiple different choices of weapons, and even with just 1 weapon selected. The downloaded simulationcraft input only has a mainhand string, but not an offhand string.

Here is the initial string im using from the simc addon:
<span>#</span> SimC Addon 1.10.6
<span>#</span> 8.0 Note: reforge= is being used as a hacky way to capture item context. This will be changed in 8.1

warrior="charname"
level=120
race=voidelf
region=eu
server=turalyon
role=attack
professions=blacksmithing=150/alchemy=150
talents=2123123
spec=fury

head=,id=158057,bonus_id=1532/5136,reforge=28,azerite_powers=176/22
neck=,id=158075,bonus_id=4936/4929/4930/1508,reforge=11,azerite_level=19
shoulder=,id=159431,bonus_id=4819/1512/4786,reforge=23,azerite_powers=438/459
back=,id=159287,bonus_id=4779/1517/4783,reforge=23
chest=,id=158054,bonus_id=1532/5138,reforge=28,azerite_powers=437/462
wrist=,id=158359,bonus_id=4779/1512/4786,reforge=23
hands=,id=155890,bonus_id=4779/1517/4783,reforge=23
waist=,id=161889,bonus_id=1699,reforge=13
legs=,id=159456,gem_id=154127,bonus_id=4779/4802/1512/4786,reforge=23
feet=,id=159428,bonus_id=4779/42/1512/4786,reforge=23
finger1=,id=159461,enchant_id=5939,gem_id=154127,bonus_id=4779/4802/1517/4783,reforge=23
finger2=,id=163934,enchant_id=5939,bonus_id=1477/4783,reforge=54
trinket1=,id=158162,bonus_id=4803/1532/4786,reforge=28
trinket2=,id=159125,reforge=13
main_hand=,id=159634,bonus_id=4779/1512/4786,reforge=23
off_hand=,id=160972,bonus_id=4803/1527/4783,reforge=26

<span>#</span><span>#</span><span>#</span> Gear from Bags
<span>#</span>
<span>#</span> Chestguard of the Deep Denizen (340)
<span>#</span> chest=,id=159408,bonus_id=4819/1512/4786,reforge=23,azerite_powers=195/22
<span>#</span>
<span>#</span> Shoalbreach Crushers (330)
<span>#</span>hands=,id=158056,bonus_id=4803/1522/4785,reforge=27
<span>#</span>
<span>#</span> Grievous Gladiator's Greatsword (122)
<span>#</span> main_hand=,id=103141,reforge=14
<span>#</span>
<span>#</span> Vengeful Gladiator's Decapitator (85)
<span>#</span>main_hand=,id=33670,reforge=14
<span>#</span>
<span>#</span> Stormsteel Saber of the Fireflash (300)
<span>#</span> main_hand=,id=162655,bonus_id=1694/4927,reforge=13
<span>#</span>
<span>#</span> Grievous Gladiator's Greatsword (122)
<span>#</span> off_hand=,id=103141,reforge=14
<span>#</span>
<span>#</span> Vengeful Gladiator's Decapitator (85)
<span>#</span> off_hand=,id=33670,reforge=14
<span>#</span>
<span>#</span> Stormsteel Shield of the Aurora (300)
<span>#</span> off_hand=,id=161891,bonus_id=1704/4927,reforge=13
<span>#</span>
<span>#</span>Stormsteel Saber of the Fireflash (300)
<span>#</span> off_hand=,id=162655,bonus_id=1694/4927,reforge=13
<span>#</span>

Note that even if I try to download the simc input from Raidbots, without making any changes in the GUI, the off_hand string is also missing.

**Comment by seriallos** [comment]
Fixed!
