### ISSUE TITLE
[Request] Set Default Character

### ISSUE THREAD

**Issue by binlong** [seriallos/raidbots-issues#76]
I would like to be able to set default character so that I don't have to keep typing my character name every single time I want to sim myself.
For example, `!raidbots -setdefault character neverTypeAgain`

**Comment by gkopevski** [comment]
I am having a problem as well for setting the default char name. I transferred to another server and now It always pops my old name. Tried to make a fake request with curl to https://www.raidbots.com/api/discord/user/settings with OK response but still showing old nickname. Even tried to change localstorage item to the new nickname but still not getting it

**Comment by gkopevski** [comment]
Example of the prob: https://giphy.com/gifs/raidbotsnameproblem-l2vsnyadj8jhOJOajT

**Comment by seriallos** [comment]
@gkopevski I'm moving this to a new issue, this is a different issue and is not related to the Discord bot.

**Comment by seriallos** [comment]
Closing due to age. This is not currently on the roadmap.
