### ISSUE TITLE
ToS Item ilvl

### ISSUE THREAD

**Issue by PoPsPinto** [seriallos/raidbots-issues#8]
Stats are incorrectly displaying for Bonus id 3563 which is Mythic ToS. I noted that the bonus_id for all gear in that tier does not appropriately change the stats associated with each item. Raidbots knows what the gear is it just doesn't update the gear.

**Comment by seriallos** [comment]
I think I have this fixed for now at least on my side. Tooltips may still be wrong as it appears WoWDB has not fully updated their data for ToS
