### ISSUE TITLE
Waycrest Legacy set bonus not simulating

### ISSUE THREAD

**Issue by olofmage** [seriallos/raidbots-issues#81]
Hello!
Dont know if this is a simulationcraft bug or Raidbots bug, but the set Waycrest Legacy (from the trinket and ring) dosnt seem to give any DPS when simulating.

**Comment by seriallos** [comment]
I believe this was added to SimC about a month ago. But I also don't think it ever contributes to DPS since "Healer DPS APLs" aren't casting healing spells that would trigger the DPS component of the bonus.
