### ISSUE TITLE
Sim is wrong

### ISSUE THREAD

**Issue by Daaseslayer** [seriallos/raidbots-issues#82]
I dont know if its me who play better, than what your sim is avraging but my numbers are higher on avrage dps then what the sim says my dps is

**Comment by seriallos** [comment]
The DPS shown is the average of thousands of samples with whatever fight configuration you used. By default, it's a 5 minute patchwerk fight (no movement, no adds, etc). Your DPS on a fight with multiple targets could be higher, a shorter fight usually results in higher DPS, you may have unusually good RNG, talents may be different, etc.
