### ISSUE TITLE
Possible bug with Demo Stat Weights?

### ISSUE THREAD

**Issue by KormonK** [seriallos/raidbots-issues#87]
Was doing some stat weight sims for my Demo lock earlier and noticed something odd. Not sure if it's a bug or if I just hit a stat breakpoint.
https://www.raidbots.com/simbot/report/9GzAEDdjGLDBXoEcdyS71f
https://www.raidbots.com/simbot/report/dGPGqPPBNnL4gJ3vDe4Kqu
One has haste at 1.37 while the other is 0.37, and the only thing I changed was a ring, which is a 0.0% dps gain/loss.

Pyre from the Warlock Discord thinks I just hit a break-point where the value of haste plummets. It's either that or a bug. 

All I know for sure is that if I plug the 0.37 weight set into Pawn, that side-grade ring reads as a 32% upgrade, which I know isn't the case.

**Comment by seriallos** [comment]
This is most likely related to reorigination array stacks and some edge case or breakpoint weirdness.

There have been a few other reports for other classes that seem to always point back to reorigination array as the common thread. I'm still looking at various reports and strategies for handling this rationally on the site but don't have any concrete plans at the moment.

Also, if you're outside of the game, I recommend using Top Gear or Gear Compare to make gear decisions. Stat weights are approximations and can be flaky like this, especially for rings. Directly simming the gear is both more accurate and less volatile.
