### ISSUE TITLE
Character not updated

### ISSUE THREAD

**Issue by funkymonk94** [seriallos/raidbots-issues#89]
I had a faction change done at the start of the new expansion and when I went to find my rogue to run a simulation on her, it says that I'm still a worgen and that I'm level 44. Both of which are incorrect. My rogue is an orc at level 120. My druid, which I leveled second, shows everything correct but my rogue is wrong. Not sure what happened. Rogue is on proudmoor.

**Comment by W4gs** [comment]
Seems to be more an issue of the api, they do a complete re-caching every week. Tuesday it may resolve the issue

**Comment by seriallos** [comment]
Yeah, not much I can do about WoW Armory API updates - that's all on Blizz's side.

If using the website, I recommend using the SimulationCraft addon as it will always work and be up-to-date.
