### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Barleduc** [seriallos/raidbots-issues#9]
After requesting a password reset, I recieved an email containing a link to a password reset page. When I try to enter a new password (using the same email address as before), I get an error message like "invalid token or email". I have tried a couple of times without success. Creating a new account isn't possible because my username and email are "already in use" (which shows the account exists).

**Comment by seriallos** [comment]
Sounds like something funky is going on. I'm not seeing any obvious errors on my side and I'm able to reset my own password.

What's your Raidbots username?

If you can hop onto Discord and private message me, I can gather your email and the links you're using

**Comment by seriallos** [comment]
Dashes at the end of URLs and email clients that don't like that was the root of the problem. Figured it out and I'm now looking into removing the dashes as part of the URLs if possible.
