### ISSUE TITLE
Top Gear is incorrectly parsing gems

### ISSUE THREAD

**Issue by W4gs** [seriallos/raidbots-issues#90]
Top Gear: https://www.raidbots.com/simbot/report/3AsfWinPZmxRJrBzYeDaUJ
Sim: https://www.raidbots.com/simbot/report/ikdD2QKigjNFNNu3uMGGbV

Bracers and Belt are reporting as 11 mastery gems, but are actually 40 Agi and 40 Crit

**Comment by seriallos** [comment]
Looks the 11 mastery gem had gotten selected in the old gem/enchant settings and replaced your higher level gem in that Top Gear sim.

Gem/enchants UI recently got an update so this should be less likely to happen (and all non-BfA gems are gone as well)
