### ISSUE TITLE
[Request] Top Gear setting for "Always equip a piece with Reorigination Array"

### ISSUE THREAD

**Issue by nullKomplex** [seriallos/raidbots-issues#97]
Similar to the previous expansion's settings for tier and legendaries I was wondering if it would be possible to implement a checkbox to only sim gear sets with Reorigination Array to cut down on the number of combinations.

A similar feature may also be useful in future tiers.

Thanks in advance.

**Comment by seriallos** [comment]
At the moment with the upcoming holidays and the 8.1/Dazar'alor patch fairly close on the horizon, I'm not planning on any more Uldir specific work.

As far as I know right now, Dazar'alor will not have a system like Reorigination Array but I'm paying attention to see if there's some other kind of automatic catch-up/buff system that needs some controls.
