### ISSUE TITLE
Imbued Bionic Bifocals

### ISSUE THREAD

**Issue by Rhordric** [seriallos/raidbots-issues#98]
The Imbued Bionic Bifocals ID=166983 shows an extra set of ring one traits other than the engineering helm specific ones

**Comment by seriallos** [comment]
At the moment, there's no way to tell if a piece of gear is the 4-ring or 5-ring variant for items like the engineering goggles. There may be a method to handle this but it'll require some thinking and careful changes to make sure things don't break all over the place.

For the moment, if you don't select those traits it won't sim so it can be treated as just a display issue that won't affect sim results.
